(()=>{
 const origin='https://zerox-sixofire-api.westdark161208.workers.dev',api=origin+'/api/community',el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
 const token=()=>{try{return JSON.parse(localStorage.getItem('zerox-session')||'null')?.token;}catch{return null;}};
 const btn=(text,fn)=>{const b=el('button',text);b.type='button';b.onclick=fn;return b;};
 let generation=0,page=0,selected=null;
 async function call(path,options={}){const t=token(),g=generation;const r=await fetch(api+path,{...options,cache:'no-store',headers:{...(t?{Authorization:'Bearer '+t}:{}),'Content-Type':'application/json'},signal:AbortSignal.timeout(30000)});if(g!==generation||t!==token())throw Error('SESSION_CHANGED');const d=await r.json();if(!r.ok)throw Error(d.error);return d;}
 function dialog(title){const d=el('dialog',null,'zx-community-dialog');const close=btn('Cerrar ×',()=>d.close());close.className='zx-community-close';d.append(close,el('p','ZERO’X / COMUNIDAD','zx-community-kicker'),el('h2',title));document.body.append(d);return d;}
 const reviews=dialog('Referencias & Comprobantes'),notice=el('p','Compras verificadas. Experiencias de nuestra comunidad.'),grid=el('div',null,'zx-review-grid'),message=el('p'),more=btn('Ver más referencias',()=>{page++;load(false);});message.setAttribute('role','status');reviews.append(notice,btn('＋ Escribir reseña',()=>{reviews.close();window.ZXOrderHistory.open();}),message,grid,more);
 function avatar(r){const box=el('span',(r.username||'ZX').slice(0,2).toUpperCase(),'zx-review-avatar');if(/^data:image\/(png|jpeg|webp);base64,/.test(r.avatar||'')){box.textContent='';const img=el('img');img.src=r.avatar;img.alt='';box.append(img);}return box;}
 async function load(reset=true){if(reset){page=0;grid.replaceChildren();}message.textContent='Cargando referencias…';more.hidden=true;try{const data=await call('/reviews?page='+page);for(const r of data.items){const card=el('article',null,'zx-review-card'),head=el('header');head.append(avatar(r),el('strong','@'+r.username));card.append(head,el('p','★'.repeat(r.rating)+'☆'.repeat(10-r.rating)+' '+r.rating+'/10','zx-review-stars'),el('blockquote',r.comment),el('span','✓ Compra verificada','zx-review-verified'));const media=el('div',null,'zx-review-media');for(const f of r.media){const m=el(f.type.startsWith('video/')?'video':'img');m.src=origin+f.url;if(m.tagName==='VIDEO'){m.controls=true;m.preload='none';m.playsInline=true;}else{m.alt='Referencia compartida por '+r.username;m.loading='lazy';}media.append(m);}card.append(media);grid.append(card);}more.hidden=!data.hasMore;message.textContent=grid.children.length?'':'Sé el primero en compartir una compra completada.';}catch{message.textContent='No pudimos cargar las referencias. Inténtalo de nuevo.';}}
 const editor=dialog('Tu experiencia cuenta');editor.innerHTML+=`<form id="zx-review-form"><p data-product></p><label>Calificación de 1 a 10 estrellas<select name="rating" required><option value="">Elige tu calificación</option>${Array.from({length:10},(_,i)=>10-i).map(n=>'<option value="'+n+'">'+n+' / 10 '+ '★'.repeat(n)+'</option>').join('')}</select></label><label>Tu experiencia<textarea name="comment" maxlength="1500" required rows="4"></textarea></label><label>Fotos o videos (hasta 5 archivos)<input name="media" type="file" multiple accept="image/jpeg,image/png,image/webp,video/mp4,video/webm"></label><small>Imágenes hasta 2 MB y videos hasta 8 MB; 12 MB en total. Los nuevos archivos sustituyen a los anteriores.</small><label><input name="removeMedia" type="checkbox">Quitar mis archivos anteriores</label><label><input name="public" type="checkbox">Publicar mi usuario, calificación, comentario y archivos. Revisé que no incluyan teléfonos, datos de pago ni información privada.</label><button type="submit">Guardar reseña</button><p role="status" data-result></p></form>`;
 // innerHTML replacement recreates the close control, so bind it again.
 editor.querySelector('.zx-community-close').onclick=()=>editor.close();const form=editor.querySelector('form');
 async function edit(order){selected=order;form.reset();form.querySelector('[data-product]').textContent=order.product;form.querySelector('[data-result]').textContent='';editor.showModal();try{const d=await call('/review?order='+encodeURIComponent(order.key));if(selected!==order)return;if(d.review){form.elements.rating.value=d.review.rating;form.elements.comment.value=d.review.comment;form.elements.public.checked=!!d.review.public;}}catch{form.querySelector('[data-result]').textContent='Puedes escribir tu reseña. No pudimos recuperar la anterior.';}}
 const read=file=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});
 form.onsubmit=async e=>{e.preventDefault();const submit=form.querySelector('[type=submit]'),msg=form.querySelector('[data-result]'),g=generation,order=selected;submit.disabled=true;try{const files=[...form.elements.media.files];if(files.length>5||files.some(f=>f.size>(f.type.startsWith('video/')?8000000:2000000))||files.reduce((n,f)=>n+f.size,0)>12000000)throw Error('INVALID_MEDIA');const media=await Promise.all(files.map(read));if(g!==generation)throw Error('SESSION_CHANGED');await call('/review?order='+encodeURIComponent(order.key),{method:'POST',body:JSON.stringify({rating:Number(form.elements.rating.value),comment:form.elements.comment.value,public:form.elements.public.checked,removeMedia:form.elements.removeMedia.checked,media})});msg.textContent=form.elements.public.checked?'Reseña publicada. ¡Gracias por compartir tu experiencia!':'Reseña guardada de forma privada.';}catch(e){msg.textContent=e.message==='INVALID_MEDIA'?'Revisa el formato, número y tamaño de los archivos.':'No se pudo guardar la reseña. Conservamos lo que escribiste.';}finally{submit.disabled=false;}};
 const top=dialog('Top Recargueros'),topStatus=el('p'),periods=el('nav',null,'zx-top-periods'),ranking=el('div',null,'zx-review-grid');top.append(topStatus,periods,ranking);
 for(const [key,label] of [['day','Diario'],['week','Semana'],['month','Mes'],['year','Año']]){const b=btn(label,()=>loadTop(key));b.dataset.period=key;periods.append(b);}
 async function loadTop(period='month'){topStatus.textContent='Consultando compras confirmadas…';ranking.replaceChildren();periods.hidden=true;try{const d=await call('/top?period='+period);if(!d.unlocked){topStatus.textContent='🔒 Se habilitará al llegar a 100 ventas completadas. Progreso: '+d.completedSales+' / 100.';return;}periods.hidden=false;for(const b of periods.children)b.setAttribute('aria-pressed',String(b.dataset.period===period));topStatus.textContent='Clasificación por diamantes de recargas ilimitadas, con compras completadas. No incluye pruebas con saldo del fundador.';d.items.forEach((r,i)=>{const card=el('article',null,'zx-rank-card');card.dataset.rank=i+1;card.append(el('strong','#'+(i+1)),avatar(r),el('strong','@'+r.username),el('p',r.diamonds.toLocaleString('es-MX')+' 💎 · '+r.purchases+' compras'));ranking.append(card);});if(!d.items.length)topStatus.textContent='Sin compras completadas en este período.';}catch{topStatus.textContent='No pudimos consultar el ranking. Inténtalo de nuevo.';}}
 window.ZXCommunity={open(){reviews.showModal();load();},edit,top(){top.showModal();loadTop();}};
 window.addEventListener('zx-session-change',()=>{generation++;selected=null;editor.close();form.reset();});window.addEventListener('storage',e=>{if(e.key==='zerox-session'){generation++;selected=null;editor.close();form.reset();}});
})();
