(()=>{
 const section=document.getElementById('code-creator');if(!section)return;
 const form=section.querySelector('form'),status=section.querySelector('[role=status]'),list=section.querySelector('[data-codes]');let attempt=null,busy=false;
 const token=()=>{try{return JSON.parse(localStorage.getItem('zerox-session')||'null')?.token;}catch{return null;}};
 async function api(options={}){const t=token();if(!t)throw Error('Inicia sesión con la cuenta de fundador.');const r=await fetch('https://zerox-sixofire-api.westdark161208.workers.dev/api/admin/coupons',{...options,cache:'no-store',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json',...options.headers}}),b=await r.json();if(t!==token())throw Error('La sesión cambió.');if(!r.ok)throw Error(b.error==='FORBIDDEN'?'Solo el fundador puede crear códigos.':b.error==='COUPON_CONFIGURATION_INVALID'?'Usa un porcentaje de 1 a 99 y una caducidad futura (máximo 5 años).':'No se pudo completar la operación.');return b;}
 async function load(){const {codes}=await api();list.replaceChildren();for(const c of codes){const card=document.createElement('article');card.className='market-card';const title=document.createElement('h3'),text=document.createElement('p');title.textContent=c.code;text.textContent=c.percent+'% · Caduca '+new Date(c.expiresAt).toLocaleString('es-MX')+' · '+(!c.active?'Desactivado':Date.parse(c.expiresAt)<=Date.now()?'Caducado':'Activo');card.append(title,text);if(c.active&&Date.parse(c.expiresAt)>Date.now()){const disable=document.createElement('button');disable.type='button';disable.textContent='Desactivar código';disable.onclick=async()=>{disable.disabled=true;try{await api({method:'POST',body:JSON.stringify({action:'disable',code:c.code})});await load();status.textContent='Código desactivado. Los pedidos ya creados conservan su descuento.';}catch(e){status.textContent=e.message;disable.disabled=false;}};card.append(disable);}list.append(card);}if(!codes.length)list.textContent='Todavía no has creado códigos.';}
 section.querySelector('[data-load]').onclick=()=>load().catch(e=>status.textContent=e.message);
 form.oninput=()=>attempt=null;
 form.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const button=form.querySelector('[type=submit]');button.disabled=true;attempt ||= crypto.randomUUID();try{const expiresAt=new Date(form.elements.expiry.value).toISOString(),b=await api({method:'POST',headers:{'Idempotency-Key':attempt},body:JSON.stringify({percent:Number(form.elements.percent.value),expiresAt})});status.textContent='Código creado: '+b.coupon.code+' · '+b.coupon.percent+'% de descuento.';attempt=null;await load();}catch(e){status.textContent=e.message;}finally{busy=false;button.disabled=false;}};
 window.addEventListener('zx-control-clear',()=>{list.replaceChildren();status.textContent='';form.reset();attempt=null;});
})();
