(()=>{
 const API='https://zerox-sixofire-api.westdark161208.workers.dev';
 const q=id=>document.getElementById(id);let generation=0;
 const token=()=>{try{return JSON.parse(localStorage.getItem('zerox-session')||'null')?.token}catch{return null}};
 const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n/100);
 function clear(){generation++;window.dispatchEvent(new Event('zx-control-clear'));q('workspace').hidden=true;for(const id of ['summary','orders','stock','balances','configuration','publications'])q(id).replaceChildren();}
 function metric(container,label,data,key,currency=false){const d=document.createElement('div');d.className='metric';const s=document.createElement('span'),v=document.createElement('strong');s.textContent=label;v.textContent=data.available?(currency?money(data[key]||0):String(data[key]||0)):'Sin datos';d.append(s,v);q(container).append(d);}
 const item=(id,text)=>{const li=document.createElement('li');li.textContent=text;q(id).append(li);};
 async function refresh(){clear();const current=token(),request=generation;if(!current){q('status').textContent='Inicia sesión con tu cuenta fundadora desde la tienda.';return;}q('refresh').disabled=true;q('status').textContent='Consultando datos…';try{const response=await fetch(API+'/api/admin/control/overview',{headers:{Authorization:'Bearer '+current},cache:'no-store'});if(!response.ok)throw Error(response.status===403?'Esta cuenta no tiene acceso a Control.':'No se pudo consultar el panel.');const d=await response.json();if(request!==generation||token()!==current)return;const m=d.metrics;
 metric('summary','Usuarios registrados',m.users,'total');metric('summary','Pedidos de diamantes',m.diamonds,'total');metric('summary','Pedidos de revendedores',m.resellers,'total');metric('summary','Pedidos pendientes · revendedores',m.resellers,'pending');
 metric('stock','Productos en catálogo administrado',m.catalog,'total');metric('stock','Unidades de Streaming',m.streaming,'units');metric('stock','Productos agotados · Streaming',m.streaming,'soldOut');metric('stock','Productos con stock bajo · Streaming',m.streaming,'lowStock');
 metric('balances','Saldo de clientes · MXN',m.customerWallet,'cents',true);metric('balances','Saldo de revendedores · MXN',m.resellerBalance,'cents',true);metric('balances','Depósitos por revisar · revendedores',m.deposits,'pending');metric('balances','Intentos de pago de prueba',m.testPayments,'total');
 for(const o of d.orders){const tr=document.createElement('tr');for(const v of [o.product,o.status,money(o.cents),o.created]){const td=document.createElement('td');td.textContent=v;tr.append(td)}q('orders').append(tr)}if(!d.orders.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=4;td.textContent=m.resellers.available?'No hay pedidos registrados.':'Este registro aún no está disponible.';tr.append(td);q('orders').append(tr)}
 for(const text of ['Mercado Pago: consulta y piloto de producción en Zero’X Pay; pruebas anteriores separadas','Entrega automática: pendiente de activación','Saldos de proveedores: estado y consulta manual en Proveedores','Passkeys y permisos delegados: pendientes'])item('configuration',text);
 for(const p of d.publications)item('publications','Revisión '+p.revision+' · '+p.created);if(!d.publications.length)item('publications','Sin publicaciones registradas.');window.dispatchEvent(new CustomEvent('zx-control-data',{detail:d}));q('workspace').hidden=false;window.dispatchEvent(new Event('zx-control-ready'));q('status').textContent='Actualizado: '+new Date(d.generatedAt).toLocaleString('es-MX');
 }catch(e){if(request===generation)q('status').textContent=e.message;}finally{q('refresh').disabled=false;}}
 q('refresh').onclick=refresh;window.addEventListener('storage',e=>{if(e.key==='zerox-session'||e.key===null){clear();q('status').textContent='La sesión cambió. Vuelve a consultar el panel.'}});document.addEventListener('visibilitychange',()=>{if(document.hidden)clear();else refresh()});window.addEventListener('pagehide',clear);refresh();
})();
