// Public presentation only: no provider costs, SKU or recipes.
(()=>{globalThis.ZXDiamondCatalog=Object.freeze([
  {
    "id": "zx-diamonds-110",
    "diamonds": 110,
    "salePriceMXN": 18,
    "character": "Subaru Natsuki",
    "anime": "Re:Zero",
    "universe": "rz",
    "tier": 1,
    "image": "assets/diamonds/collection-v2/110.webp",
    "imageReady": true,
    "accent": "171,132,255"
  },
  {
    "id": "zx-diamonds-220",
    "diamonds": 220,
    "salePriceMXN": 35,
    "character": "Bachira Meguru",
    "anime": "Blue Lock",
    "universe": "bl",
    "tier": 1,
    "image": "assets/diamonds/collection-v2/220.webp",
    "imageReady": true,
    "accent": "246,220,80"
  },
  {
    "id": "zx-diamonds-341",
    "diamonds": 341,
    "salePriceMXN": 57,
    "character": "Power",
    "anime": "Chainsaw Man",
    "universe": "cm",
    "tier": 1,
    "image": "assets/diamonds/collection-v2/341.webp",
    "imageReady": true,
    "accent": "255,103,121"
  },
  {
    "id": "zx-diamonds-572",
    "diamonds": 572,
    "salePriceMXN": 85,
    "character": "Rem",
    "anime": "Re:Zero",
    "universe": "rz",
    "tier": 1,
    "image": "assets/diamonds/collection-v2/572.webp",
    "imageReady": true,
    "accent": "100,189,255"
  },
  {
    "id": "zx-diamonds-682",
    "diamonds": 682,
    "salePriceMXN": 114,
    "character": "Chigiri Hyoma",
    "anime": "Blue Lock",
    "universe": "bl",
    "tier": 1,
    "image": "assets/diamonds/collection-v2/682.webp",
    "imageReady": true,
    "accent": "255,115,172"
  },
  {
    "id": "zx-diamonds-913",
    "diamonds": 913,
    "salePriceMXN": 145,
    "character": "Momo Ayase",
    "anime": "Dandadan",
    "universe": "dd",
    "tier": 1,
    "image": "assets/diamonds/collection-v2/913.webp",
    "imageReady": true,
    "accent": "255,126,190"
  },
  {
    "id": "zx-diamonds-1166",
    "diamonds": 1166,
    "salePriceMXN": 150,
    "character": "Reo Mikage",
    "anime": "Blue Lock",
    "universe": "bl",
    "tier": 1,
    "image": "assets/diamonds/collection-v2/1166.webp",
    "imageReady": true,
    "accent": "190,137,255"
  },
  {
    "id": "zx-diamonds-1507",
    "diamonds": 1507,
    "salePriceMXN": 210,
    "character": "Megumi Fushiguro",
    "anime": "Jujutsu Kaisen",
    "universe": "jjk",
    "tier": 1,
    "image": "assets/diamonds/collection-v2/1507.webp",
    "imageReady": true,
    "accent": "113,162,255"
  },
  {
    "id": "zx-diamonds-1738",
    "diamonds": 1738,
    "salePriceMXN": 210,
    "character": "Emilia",
    "anime": "Re:Zero",
    "universe": "rz",
    "tier": 1,
    "image": "assets/diamonds/collection-v2/1738.webp",
    "imageReady": true,
    "accent": "204,159,255"
  },
  {
    "id": "zx-diamonds-2398",
    "diamonds": 2398,
    "salePriceMXN": 275,
    "character": "Aki Hayakawa",
    "anime": "Chainsaw Man",
    "universe": "cm",
    "tier": 1,
    "image": "assets/diamonds/collection-v2/2398.webp",
    "imageReady": true,
    "accent": "107,180,255"
  },
  {
    "id": "zx-diamonds-2970",
    "diamonds": 2970,
    "salePriceMXN": 345,
    "character": "Mikasa Ackerman",
    "anime": "Attack on Titan",
    "universe": "aot",
    "tier": 1,
    "image": "assets/diamonds/collection-v2/2970.webp",
    "imageReady": true,
    "accent": "255,107,119"
  },
  {
    "id": "zx-diamonds-3564",
    "diamonds": 3564,
    "salePriceMXN": 410,
    "character": "Nagi Seishiro",
    "anime": "Blue Lock",
    "universe": "bl",
    "tier": 1,
    "image": "assets/diamonds/collection-v2/3564.webp",
    "imageReady": true,
    "accent": "154,212,255"
  },
  {
    "id": "zx-diamonds-4796",
    "diamonds": 4796,
    "salePriceMXN": 540,
    "character": "Nobara Kugisaki",
    "anime": "Jujutsu Kaisen",
    "universe": "jjk",
    "tier": 1,
    "image": "assets/diamonds/collection-v2/4796.webp",
    "imageReady": true,
    "accent": "255,157,102"
  },
  {
    "id": "zx-diamonds-6160",
    "diamonds": 6160,
    "salePriceMXN": 670,
    "character": "Monkey D. Luffy",
    "anime": "One Piece",
    "universe": "op",
    "tier": 2,
    "image": "assets/diamonds/collection-v2/6160.webp",
    "imageReady": true,
    "accent": "255,105,90"
  },
  {
    "id": "zx-diamonds-6732",
    "diamonds": 6732,
    "salePriceMXN": 745,
    "character": "Roronoa Zoro",
    "anime": "One Piece",
    "universe": "op",
    "tier": 2,
    "image": "assets/diamonds/collection-v2/6732.webp",
    "imageReady": true,
    "accent": "117,235,127"
  },
  {
    "id": "zx-diamonds-7326",
    "diamonds": 7326,
    "salePriceMXN": 810,
    "character": "Nico Robin",
    "anime": "One Piece",
    "universe": "op",
    "tier": 2,
    "image": "assets/diamonds/collection-v2/7326.webp",
    "imageReady": true,
    "accent": "185,137,255"
  },
  {
    "id": "zx-diamonds-8558",
    "diamonds": 8558,
    "salePriceMXN": 940,
    "character": "Isagi Yoichi",
    "anime": "Blue Lock",
    "universe": "bl",
    "tier": 2,
    "image": "assets/diamonds/collection-v2/8558.webp",
    "imageReady": true,
    "accent": "109,175,255"
  },
  {
    "id": "zx-diamonds-9724",
    "diamonds": 9724,
    "salePriceMXN": 1075,
    "character": "Trafalgar Law",
    "anime": "One Piece",
    "universe": "op",
    "tier": 2,
    "image": "assets/diamonds/collection-v2/9724.webp",
    "imageReady": true,
    "accent": "255,221,115"
  },
  {
    "id": "zx-diamonds-10956",
    "diamonds": 10956,
    "salePriceMXN": 1210,
    "character": "Levi Ackerman",
    "anime": "Attack on Titan",
    "universe": "aot",
    "tier": 2,
    "image": "assets/diamonds/collection-v2/10956.webp",
    "imageReady": true,
    "accent": "138,211,193"
  },
  {
    "id": "zx-diamonds-12320",
    "diamonds": 12320,
    "salePriceMXN": 1340,
    "character": "Boa Hancock",
    "anime": "One Piece",
    "universe": "op",
    "tier": 2,
    "image": "assets/diamonds/collection-v2/12320.webp",
    "imageReady": true,
    "accent": "255,137,183"
  },
  {
    "id": "zx-diamonds-12892",
    "diamonds": 12892,
    "salePriceMXN": 1410,
    "character": "Barou Shoei",
    "anime": "Blue Lock",
    "universe": "bl",
    "tier": 2,
    "image": "assets/diamonds/collection-v2/12892.webp",
    "imageReady": true,
    "accent": "255,130,97"
  },
  {
    "id": "zx-diamonds-14058",
    "diamonds": 14058,
    "salePriceMXN": 1545,
    "character": "Denji",
    "anime": "Chainsaw Man",
    "universe": "cm",
    "tier": 2,
    "image": "assets/diamonds/collection-v2/14058.webp",
    "imageReady": true,
    "accent": "255,160,80"
  },
  {
    "id": "zx-diamonds-14718",
    "diamonds": 14718,
    "salePriceMXN": 1605,
    "character": "Maki Zenin",
    "anime": "Jujutsu Kaisen",
    "universe": "jjk",
    "tier": 2,
    "image": "assets/diamonds/collection-v2/14718.webp",
    "imageReady": true,
    "accent": "133,235,166"
  },
  {
    "id": "zx-diamonds-15884",
    "diamonds": 15884,
    "salePriceMXN": 1740,
    "character": "Portgas D. Ace",
    "anime": "One Piece",
    "universe": "op",
    "tier": 3,
    "image": "assets/diamonds/collection-v2/15884.webp",
    "imageReady": true,
    "accent": "255,152,88"
  },
  {
    "id": "zx-diamonds-17116",
    "diamonds": 17116,
    "salePriceMXN": 1875,
    "character": "Rin Itoshi",
    "anime": "Blue Lock",
    "universe": "bl",
    "tier": 3,
    "image": "assets/diamonds/collection-v2/17116.webp",
    "imageReady": true,
    "accent": "112,187,255"
  },
  {
    "id": "zx-diamonds-18480",
    "diamonds": 18480,
    "salePriceMXN": 2005,
    "character": "Colección rosa",
    "anime": "Zero’X Store",
    "universe": "zx",
    "tier": 3,
    "image": "assets/diamonds/collection-v2/18480.webp",
    "imageReady": true,
    "accent": "255,107,142"
  },
  {
    "id": "zx-diamonds-19052",
    "diamonds": 19052,
    "salePriceMXN": 2080,
    "character": "Toji Fushiguro",
    "anime": "Jujutsu Kaisen",
    "universe": "jjk",
    "tier": 3,
    "image": "assets/diamonds/collection-v2/19052.webp",
    "imageReady": true,
    "accent": "159,135,255"
  },
  {
    "id": "zx-diamonds-20878",
    "diamonds": 20878,
    "salePriceMXN": 2275,
    "character": "Charlotte Katakuri",
    "anime": "One Piece",
    "universe": "op",
    "tier": 3,
    "image": "assets/diamonds/collection-v2/20878.webp",
    "imageReady": true,
    "accent": "244,130,178"
  },
  {
    "id": "zx-diamonds-22044",
    "diamonds": 22044,
    "salePriceMXN": 2410,
    "character": "Makima",
    "anime": "Chainsaw Man",
    "universe": "cm",
    "tier": 3,
    "image": "assets/diamonds/collection-v2/22044.webp",
    "imageReady": true,
    "accent": "255,107,112"
  },
  {
    "id": "zx-diamonds-23276",
    "diamonds": 23276,
    "salePriceMXN": 2545,
    "character": "Igris",
    "anime": "Solo Leveling",
    "universe": "sl",
    "tier": 3,
    "image": "assets/diamonds/collection-v2/23276.webp",
    "imageReady": true,
    "accent": "130,181,255"
  },
  {
    "id": "zx-diamonds-24640",
    "diamonds": 24640,
    "salePriceMXN": 2675,
    "character": "Jiji / Evil Eye",
    "anime": "Dandadan",
    "universe": "dd",
    "tier": 3,
    "image": "assets/diamonds/collection-v2/24640.webp",
    "imageReady": true,
    "accent": "255,207,121"
  },
  {
    "id": "zx-diamonds-25806",
    "diamonds": 25806,
    "salePriceMXN": 2810,
    "character": "Yuta Okkotsu",
    "anime": "Jujutsu Kaisen",
    "universe": "jjk",
    "tier": 3,
    "image": "assets/diamonds/collection-v2/25806.webp",
    "imageReady": true,
    "accent": "105,204,255"
  },
  {
    "id": "zx-diamonds-27038",
    "diamonds": 27038,
    "salePriceMXN": 2945,
    "character": "Marco el Fénix",
    "anime": "One Piece",
    "universe": "op",
    "tier": 3,
    "image": "assets/diamonds/collection-v2/27038.webp",
    "imageReady": true,
    "accent": "139,222,169"
  },
  {
    "id": "zx-diamonds-28204",
    "diamonds": 28204,
    "salePriceMXN": 3080,
    "character": "Eren / Titán de Ataque",
    "anime": "Attack on Titan",
    "universe": "aot",
    "tier": 3,
    "image": "assets/diamonds/collection-v2/28204.webp",
    "imageReady": true,
    "accent": "135,205,255"
  },
  {
    "id": "zx-diamonds-30008",
    "diamonds": 30008,
    "salePriceMXN": 3285,
    "character": "Dracule Mihawk",
    "anime": "One Piece",
    "universe": "op",
    "tier": 4,
    "image": "assets/diamonds/collection-v2/30008.webp",
    "imageReady": true,
    "accent": "255,105,155"
  },
  {
    "id": "zx-diamonds-30800",
    "diamonds": 30800,
    "salePriceMXN": 3340,
    "character": "Sanji",
    "anime": "One Piece",
    "universe": "op",
    "tier": 4,
    "image": "assets/diamonds/collection-v2/30800.webp",
    "imageReady": true,
    "accent": "124,164,255"
  },
  {
    "id": "zx-diamonds-31966",
    "diamonds": 31966,
    "salePriceMXN": 3475,
    "character": "Okarun / Turbo Granny",
    "anime": "Dandadan",
    "universe": "dd",
    "tier": 4,
    "image": "assets/diamonds/collection-v2/31966.webp",
    "imageReady": true,
    "accent": "255,216,134"
  },
  {
    "id": "zx-diamonds-33198",
    "diamonds": 33198,
    "salePriceMXN": 3610,
    "character": "Yuta + Rika",
    "anime": "Jujutsu Kaisen",
    "universe": "jjk",
    "tier": 4,
    "image": "assets/diamonds/collection-v2/33198.webp",
    "imageReady": true,
    "accent": "255,134,92"
  },
  {
    "id": "zx-diamonds-34936",
    "diamonds": 34936,
    "salePriceMXN": 3820,
    "character": "Silvers Rayleigh",
    "anime": "One Piece",
    "universe": "op",
    "tier": 4,
    "image": "assets/diamonds/collection-v2/34936.webp",
    "imageReady": true,
    "accent": "135,186,255"
  },
  {
    "id": "zx-diamonds-36960",
    "diamonds": 36960,
    "salePriceMXN": 4010,
    "character": "Roronoa Zoro / Asura",
    "anime": "One Piece",
    "universe": "op",
    "tier": 4,
    "image": "assets/diamonds/collection-v2/36960.webp",
    "imageReady": true,
    "accent": "255,113,144"
  },
  {
    "id": "zx-diamonds-38126",
    "diamonds": 38126,
    "salePriceMXN": 4145,
    "character": "Gojo Satoru",
    "anime": "Jujutsu Kaisen",
    "universe": "jjk",
    "tier": 4,
    "image": "assets/diamonds/collection-v2/38126.webp",
    "imageReady": true,
    "accent": "195,168,255"
  },
  {
    "id": "zx-diamonds-39358",
    "diamonds": 39358,
    "salePriceMXN": 4280,
    "character": "Ryomen Sukuna",
    "anime": "Jujutsu Kaisen",
    "universe": "jjk",
    "tier": 4,
    "image": "assets/diamonds/collection-v2/39358.webp",
    "imageReady": true,
    "accent": "162,124,255"
  },
  {
    "id": "zx-diamonds-40524",
    "diamonds": 40524,
    "salePriceMXN": 4415,
    "character": "Kaido",
    "anime": "One Piece",
    "universe": "op",
    "tier": 5,
    "image": "assets/diamonds/collection-v2/40524.webp",
    "imageReady": true,
    "accent": "131,224,227"
  },
  {
    "id": "zx-diamonds-43120",
    "diamonds": 43120,
    "salePriceMXN": 4680,
    "character": "Sung Jinwoo",
    "anime": "Solo Leveling",
    "universe": "sl",
    "tier": 5,
    "image": "assets/diamonds/collection-v2/43120.webp",
    "imageReady": true,
    "accent": "255,100,139"
  },
  {
    "id": "zx-diamonds-44286",
    "diamonds": 44286,
    "salePriceMXN": 4815,
    "character": "Yamato",
    "anime": "One Piece",
    "universe": "op",
    "tier": 5,
    "image": "assets/diamonds/collection-v2/44286.webp",
    "imageReady": true,
    "accent": "255,216,143"
  },
  {
    "id": "zx-diamonds-45518",
    "diamonds": 45518,
    "salePriceMXN": 4950,
    "character": "Buggy",
    "anime": "One Piece",
    "universe": "op",
    "tier": 5,
    "image": "assets/diamonds/collection-v2/45518.webp",
    "imageReady": true,
    "accent": "164,124,255"
  },
  {
    "id": "zx-diamonds-46684",
    "diamonds": 46684,
    "salePriceMXN": 5085,
    "character": "Edward Newgate / Whitebeard",
    "anime": "One Piece",
    "universe": "op",
    "tier": 5,
    "image": "assets/diamonds/collection-v2/46684.webp",
    "imageReady": true,
    "accent": "255,108,114"
  },
  {
    "id": "zx-diamonds-49280",
    "diamonds": 49280,
    "salePriceMXN": 5350,
    "character": "Sung Jinwoo / Shadow Monarch",
    "anime": "Solo Leveling",
    "universe": "sl",
    "tier": 5,
    "image": "assets/diamonds/collection-v2/49280.webp",
    "imageReady": true,
    "accent": "255,215,112"
  },
  {
    "id": "zx-diamonds-50446",
    "diamonds": 50446,
    "salePriceMXN": 5485,
    "character": "Monkey D. Luffy / Gear 5",
    "anime": "One Piece",
    "universe": "op",
    "tier": 5,
    "image": "assets/diamonds/collection-v2/50446.webp",
    "imageReady": true,
    "accent": "255,156,110"
  },
  {
    "id": "zx-diamonds-100892",
    "diamonds": 100892,
    "salePriceMXN": 10960,
    "character": "Gol D. Roger / Rey de los Piratas",
    "anime": "One Piece",
    "universe": "op",
    "tier": 6,
    "image": "assets/diamonds/collection-v2/100892.webp",
    "imageReady": true,
    "accent": "255,215,112"
  }
].map(Object.freeze));})();
