/* New games use their provider validation; never query a Free Fire profile for another game. */
(()=>{
 const hub=document.querySelector('.zx-hub-grid');
 const node=(tag,text)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;};
 function card(id,name,image,description){let b=hub.querySelector('[data-game-section="'+id+'"]');if(!b){b=node('button');b.type='button';b.className='zx-hub-card';b.dataset.gameSection=id;hub.append(b);b.onclick=()=>{zxOpenCatalog(b.dataset.category);const heading=document.getElementById('catalog-title');if(heading)heading.textContent=b.querySelector('strong').textContent;};}b.dataset.category=name;b.replaceChildren();if(image){const img=node('img');img.src=image;img.alt=name;img.loading='lazy';b.append(img);}const box=node('div');box.append(node('small','JUEGOS'),node('strong',name),node('span',description));b.append(box);return b;}
 for(const s of ZXGameSections)card(s.id,s.name,s.image,s.description);
 function ensure(map,editing=false){const added=[];for(const [id,p] of Object.entries(map)){
  if(id.startsWith('custom:block:')){const b=card(id,p.name,p.image,p.description);b.dataset.category=id;b.hidden=p.active===false&&!editing;b.querySelector('small').textContent=p.character||'ZERO’X';}
  if(id.startsWith('custom:product:')&&!PRODUCTS.some(b=>b.id===id)){const b={id,category:p.category,name:p.name,price:0,pricePending:true,active:true,description:p.description,editorImage:p.image};PRODUCTS.push(b);added.push(b);}
 }return added;}
 const errors={...window.ZXCoupons.errors,LOGIN_REQUIRED:'Inicia sesión para comprar.',PRODUCT_PRICE_REQUIRED:'Precio pendiente de publicar.',PLAYER_REJECTED:'El proveedor no pudo confirmar este ID. Revisa el juego y tu ID; no se realizó ningún cobro.',PRODUCT_DELIVERY_MAPPING_REQUIRED:'Este artículo requiere revisar su disponibilidad o plataforma antes de cobrar.',DELIVERY_FUNDS_UNAVAILABLE:'La entrega no está disponible en este momento. No se realizó el cobro.',PRODUCT_PRICE_CHANGED:'El precio cambió. Cierra y vuelve a abrir el artículo.',WALLET_MOVEMENT_REJECTED:'Saldo insuficiente o movimiento rechazado.',PRODUCT_NOT_AVAILABLE:'Entrega temporalmente no disponible.'};
 function checkout(product){
  const d=node('dialog');d.className='zx-reference-modal';const close=node('button','×');close.type='button';close.setAttribute('aria-label','Cerrar');close.onclick=()=>d.close();d.append(close,node('h2',product.name));
  const msg=node('p');msg.setAttribute('role','status');d.append(msg);document.body.append(d);d.addEventListener('close',()=>d.remove());d.showModal();
  if(!getZeroXSession()?.token){msg.textContent=errors.LOGIN_REQUIRED;return;}if(product.price<=0){msg.textContent=errors.PRODUCT_PRICE_REQUIRED;return;}
  if(product.platformPending){msg.textContent='Estamos confirmando la plataforma de Arena Breakout. Infinite no está confirmado; este artículo todavía no acepta pagos.';return;}
  d.append(node('p','Precio final con costos de operación incluidos, igual para saldo y pagos en línea.'));
  const f=node('form'),uid=node('input');uid.name='uid';uid.inputMode='numeric';uid.pattern='[0-9]{5,15}';uid.required=true;uid.maxLength=15;
  const label=node('label','ID de '+product.category);label.append(uid);const verify=node('button','Verificar ID');verify.type='submit';f.append(label,verify);d.append(f);
  const payments=node('section');payments.hidden=true;const total=node('strong','Total '+money(product.price)),identity=node('p'),confirm=node('label','Confirmo que este ID es el destinatario de mi compra '),check=node('input');check.type='checkbox';confirm.append(check);const phoneLabel=node('label','Teléfono de contacto / WhatsApp'),phone=node('input');phone.type='tel';phone.value=zeroxUser?.phone||'';phoneLabel.append(phone);const coupon=node('div'),methods=node('div');const select=zxRenderPaymentMethods(methods),pay=node('button','Pagar con Mercado Pago →');pay.type='button';payments.append(identity,confirm,total,phoneLabel,coupon,methods,pay);d.append(payments);const discount=ZXCoupons.mount(coupon,Math.round(product.price*100),s=>total.textContent='Total '+money(s.amountCents/100));let verified='',busy=false,key=crypto.randomUUID(),created=false;
  select.onchange=()=>pay.textContent=select.value==='wallet'?'Pagar con saldo →':'Pagar con Mercado Pago →';
  uid.oninput=()=>{verified='';check.checked=false;payments.hidden=true;};
  f.onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;verify.disabled=true;msg.textContent='Verificando destino y disponibilidad…';const value=uid.value.trim();try{const q=await zeroxAuthRequest('/api/services/purchase/game/quote',{method:'POST',body:JSON.stringify({productId:product.id,playerId:value})});if(!d.open||value!==uid.value.trim())return;if(q.amountCents!==Math.round(product.price*100))throw Error('PRODUCT_PRICE_CHANGED');verified=value;identity.textContent=(q.accountName||'Cuenta validada')+' · ID '+value;payments.hidden=false;msg.textContent='Destino verificado. Confirma el ID antes de pagar.';}catch(e){msg.textContent=errors[e.data?.error||e.message]||'No pudimos verificar la recarga. Intenta de nuevo más tarde.';}finally{busy=false;verify.disabled=false;}};
  pay.onclick=async()=>{if(busy||created)return;if(!verified||verified!==uid.value.trim()||!check.checked){msg.textContent='Verifica y confirma el ID de destino.';return;}if(!/^\+?[0-9 ()-]{8,24}$/.test(phone.value)){msg.textContent='Agrega un teléfono de contacto válido.';return;}busy=true;pay.disabled=true;verify.disabled=true;select.disabled=true;methods.querySelectorAll('button').forEach(b=>b.disabled=true);uid.disabled=true;check.disabled=true;phone.disabled=true;discount.lock();try{
   const price=discount.state(),session=getZeroXSession()?.token,method=select.value;const pendingKey='zx-game-pending:'+String(zeroxUser?.id||'')+':'+product.id+':'+verified;let old=null;try{old=JSON.parse(sessionStorage.getItem(pendingKey)||'null');}catch{}if(old){if(old.method!==method||old.amountCents!==price.amountCents||old.couponCode!==price.couponCode)throw Error('IDEMPOTENCY_CONFLICT');key=old.key;}if(method==='wallet'&&!await ZXPurchaseFlow.confirmBalance({product:product.name,playerId:verified,amount:money(price.amountCents/100)+' MXN · Saldo Zero’X'}))return;
   if(!d.open||document.hidden||session!==getZeroXSession()?.token)return;try{sessionStorage.setItem(pendingKey,JSON.stringify({key,method,amountCents:price.amountCents,couponCode:price.couponCode}));}catch{}msg.textContent='Preparando el pago…';const r=await zeroxAuthRequest('/api/services/purchase/checkout',{method:'POST',headers:{'Idempotency-Key':key},body:JSON.stringify({productId:product.id,quantity:1,playerId:verified,playerConfirmed:true,contactPhone:phone.value.trim(),method,maxAmountCents:price.amountCents,couponCode:price.couponCode})});created=true;if(session!==getZeroXSession()?.token||!d.open)return;try{sessionStorage.removeItem(pendingKey);}catch{}
   if(r.checkoutUrl){const u=new URL(r.checkoutUrl);if(u.protocol!=='https:'||!['www.mercadopago.com.mx','www.mercadopago.com'].includes(u.hostname)||u.username||u.password)throw Error('INVALID_CHECKOUT');location.assign(u.href);return;}
   msg.textContent='Pedido registrado. Consulta la entrega; no vuelvas a pagar.';const a=node('a','Consultar pedido →');a.href='product-payment.html?kind=service&order='+encodeURIComponent(r.orderId);payments.append(a);ZXPurchaseFlow.watchOrder(r.orderId,{request:path=>zeroxAuthRequest('/api/services/purchase'+path),onComplete:id=>ZXPurchaseFlow.openReceipt(id,'service')});
  }catch(e){msg.textContent=errors[e.data?.error||e.message]||'No pudimos confirmar el intento. Consulta Mis pedidos antes de repetir el pago.';}finally{busy=false;pay.disabled=created;verify.disabled=created;select.disabled=created;methods.querySelectorAll('button').forEach(b=>b.disabled=created);uid.disabled=created;check.disabled=created;phone.disabled=created;discount.lock(created);}};
 }
 window.ZXGameStore={ensure,checkout};
 fetch(ZEROX_API+'/api/store-editor/games').then(r=>{if(!r.ok)throw Error('catalog');return r.json()}).then(d=>{const bases=[];for(const p of d.products||[]){const section=ZXGameSections.find(s=>s.id===p.section);if(!section||PRODUCTS.some(b=>b.id===p.id))continue;const b={id:p.id,name:p.name,category:section.name,price:0,pricePending:true,active:true,zxGame:true,platformPending:p.platformPending,description:'Recarga por ID · '+section.name,editorImage:section.image};PRODUCTS.push(b);bases.push(b);}document.dispatchEvent(new CustomEvent('zx-game-catalog',{detail:bases}));render();}).catch(()=>{for(const s of ZXGameSections){const b=hub.querySelector('[data-game-section="'+s.id+'"]');b.querySelector('span').textContent='Catálogo temporalmente no disponible';}});
})();
