/* Personal MXN balance and private island; server decides funding availability. */
(()=>{
 const q=id=>document.getElementById(id),value=q('zx-header-wallet-value'),island=q('zx-wallet-island');let generation=0,controller;
 const icons=["<svg viewBox=\"0 0 48 36\" fill=\"none\"><rect x=\"2\" y=\"3\" width=\"44\" height=\"30\" rx=\"6\" fill=\"#123f57\" stroke=\"#75dcff\" stroke-width=\"2\"/><path d=\"M3 12h42\" stroke=\"#75dcff\" stroke-width=\"5\"/><rect x=\"9\" y=\"22\" width=\"9\" height=\"5\" rx=\"1\" fill=\"#8cf6dc\"/><path d=\"M25 25h12\" stroke=\"#c1f7ff\" stroke-width=\"2\" stroke-linecap=\"round\"/></svg>", "<svg viewBox=\"0 0 64 40\"><rect x=\"1\" y=\"3\" width=\"62\" height=\"34\" rx=\"6\" fill=\"#ffcd42\"/><rect x=\"3\" y=\"6\" width=\"58\" height=\"28\" rx=\"4\" fill=\"#df202b\"/><text x=\"32\" y=\"27\" fill=\"white\" font-family=\"Arial,sans-serif\" font-weight=\"900\" font-style=\"italic\" font-size=\"21\" text-anchor=\"middle\">OXXO</text></svg>", "<svg viewBox=\"0 0 48 40\" fill=\"none\"><path d=\"M4 12L24 3l20 9H4Z\" fill=\"#13584b\" stroke=\"#63ffbc\" stroke-width=\"2\"/><path d=\"M10 16v13m9-13v13m10-13v13m9-13v13M5 33h38\" stroke=\"#9affe0\" stroke-width=\"3\" stroke-linecap=\"round\"/><path d=\"M7 38h34\" stroke=\"#63ffbc\" stroke-width=\"2\" stroke-linecap=\"round\"/></svg>", "<svg viewBox=\"0 0 64 40\" fill=\"none\"><ellipse cx=\"32\" cy=\"20\" rx=\"30\" ry=\"17\" fill=\"#00bcff\"/><path d=\"M5 19l12-9 11 1 10 4 10-3 11 8-11 10-10-1-7 5-12-6-8-1Z\" fill=\"#f6ffff\" stroke=\"#165174\" stroke-width=\"1.5\"/><path d=\"M17 11l9 7 7-4 12 10-5 4-9-7-5 3-6-4m11 1 8 9m-14-7 9 9m-15-9 9 9\" stroke=\"#165174\" stroke-width=\"1.5\" stroke-linecap=\"round\" stroke-linejoin=\"round\"/></svg>"];
 const token=()=>getZeroXSession()?.token;
 const money=cents=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(cents/100)+' MXN';
 function methods(available=false){const host=q('zx-wallet-island-methods');if(!host)return;host.replaceChildren();let index=0;for(const [code,name,icon] of [['card','Tarjeta','▰'],['oxxo','OXXO','OXXO'],['spei','Transferencia','⇄'],['all','Mercado Pago','MP']]){const tile=document.createElement(available?'a':'span');tile.className='zx-island-method zx-island-method-'+code;if(available)tile.href='wallet-payment.html?method='+code;const mark=document.createElement('b'),label=document.createElement('span');mark.innerHTML=icons[index++]||'';mark.setAttribute('aria-hidden','true');label.textContent=name;tile.append(mark,label);host.append(tile);}q('zx-wallet-island-topup').hidden=!available;}
 function clear(){generation++;controller?.abort();value.textContent=token()?'Consultar saldo':'Inicia sesión';if(!island)return;q('zx-wallet-island-value').textContent='—';q('zx-wallet-island-status').textContent='Consulta tu saldo para ver la disponibilidad de recarga.';methods(false);}
 function hide(){if(island?.open)island.close();clear();}
 async function refresh(){clear();const current=token(),version=generation;if(!current||document.hidden)return;controller=new AbortController();value.textContent='Consultando…';
  try{const data=await zeroxAuthRequest('/api/wallet/me',{cache:'no-store',signal:controller.signal});if(version!==generation||current!==token()||document.hidden)return;
   if(data.currency!=='MXN'||!Number.isSafeInteger(data.availableCents)||data.availableCents<0)throw Error('INVALID_BALANCE');
   value.textContent=money(data.availableCents);if(island){q('zx-wallet-island-value').textContent=money(data.availableCents);methods(data.fundingPilotAvailable===true);q('zx-wallet-island-status').textContent=data.fundingPilotAvailable===true?'Recarga real disponible en el piloto de tu cuenta.':'Consulta de saldo disponible. La recarga está en preparación para esta cuenta.';}
  }catch(e){if(version===generation&&current===token()&&!document.hidden){value.textContent=e.status===401?'Inicia sesión':'Saldo no disponible';if(island)q('zx-wallet-island-status').textContent=e.status===401?'Tu sesión terminó. Vuelve a iniciar sesión.':'No pudimos consultar tu saldo. Puedes volver a intentarlo.';}}
 }
 q('zx-header-wallet').addEventListener('click',()=>{if(!token()){q('open-account').click();return;}if(island&&!island.open)island.showModal();refresh();});
 q('zx-wallet-island-close')?.addEventListener('click',()=>{island.close();q('zx-header-wallet').focus();});q('zx-wallet-island-refresh')?.addEventListener('click',refresh);
 island?.addEventListener('click',e=>{if(e.target!==island)return;const r=island.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)island.close();});
 window.addEventListener('zx-session-change',hide);window.addEventListener('zx-account-ready',refresh);
 window.addEventListener('storage',e=>{if(e.key==='zerox-session'||e.key===null){hide();refresh();}});window.addEventListener('pagehide',hide);
 document.addEventListener('visibilitychange',()=>{if(document.hidden)hide();else refresh();});refresh();
})();
