/* Personal MXN balance and private island; server decides funding availability. */
(()=>{
 const q=id=>document.getElementById(id),value=q('zx-header-wallet-value'),island=q('zx-wallet-island');let generation=0,controller,fundingAvailable=false,attempt=null,method="all",fundingBusy=false;

 const token=()=>getZeroXSession()?.token;
 const money=cents=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(cents/100)+' MXN';
 function methods(available=false){const host=q('zx-wallet-island-methods');if(!host)return;host.replaceChildren();for(const [code,name] of [['card','Tarjeta'],['spei','Transferencia'],['all','Mercado Pago']]){const tile=document.createElement('button');tile.type='button';tile.className='zx-island-method zx-island-method-'+code;tile.disabled=!available||!!attempt;tile.setAttribute('aria-pressed',String(method===code));const mark=document.createElement('b'),label=document.createElement('span');mark.innerHTML=window.ZX_PAYMENT_ICONS?.[code]||'';mark.setAttribute('aria-hidden','true');label.textContent=name;tile.append(mark,label);tile.onclick=()=>{if(attempt||fundingBusy)return;method=code;methods(available);};host.append(tile);}if(q('zx-island-amount'))q('zx-island-amount').disabled=!!attempt;q('zx-wallet-island-topup').hidden=!available;q('zx-wallet-island-topup').disabled=!available||!!attempt;if(q('zx-island-funding-form'))q('zx-island-funding-form').hidden=!available;}
 function clear(){generation++;fundingAvailable=false;fundingBusy=false;controller?.abort();value.textContent=token()?'Consultar saldo':'Inicia sesión';if(!island)return;q('zx-wallet-island-value').textContent='—';q('zx-wallet-island-status').textContent='Consulta tu saldo para ver la disponibilidad de recarga.';methods(false);if(q('zx-island-checkout')){q('zx-island-checkout').hidden=true;q('zx-island-checkout').removeAttribute('href');}if(q('zx-island-funding-refresh'))q('zx-island-funding-refresh').hidden=true;if(q('zx-island-funding-status'))q('zx-island-funding-status').textContent='';if(q('zx-island-new-funding'))q('zx-island-new-funding').hidden=true;}
 function hide(){if(island?.open)island.close();clear();}
 async function refresh(){clear();const current=token(),version=generation;if(!current||document.hidden)return;controller=new AbortController();value.textContent='Consultando…';
  try{const data=await zeroxAuthRequest('/api/wallet/me',{cache:'no-store',signal:controller.signal});if(version!==generation||current!==token()||document.hidden)return;
   if(data.currency!=='MXN'||!Number.isSafeInteger(data.availableCents)||data.availableCents<0)throw Error('INVALID_BALANCE');
   value.textContent=money(data.availableCents);if(island){q('zx-wallet-island-value').textContent=money(data.availableCents);fundingAvailable=data.fundingPilotAvailable===true;methods(fundingAvailable);if(attempt&&q('zx-island-funding-refresh'))q('zx-island-funding-refresh').hidden=false;q('zx-wallet-island-status').textContent=data.fundingPilotAvailable===true?'Recarga tu saldo con tarjeta o transferencia mediante Mercado Pago.':'Consulta de saldo disponible. La recarga está en preparación para esta cuenta.';}
  }catch(e){if(version===generation&&current===token()&&!document.hidden){value.textContent=e.status===401?'Inicia sesión':'Saldo no disponible';if(island)q('zx-wallet-island-status').textContent=e.status===401?'Tu sesión terminó. Vuelve a iniciar sesión.':'No pudimos consultar tu saldo. Puedes volver a intentarlo.';}}
 }
 const FUNDING='/api/payments/mercadopago/funding';
 function restoreAttempt(){try{const returned=typeof location!=='undefined'?new URL(location.href).searchParams.get('funding'):null;if(/^[a-f0-9-]{36}$/.test(returned||''))attempt=returned;const owner=(typeof zeroxUser!=='undefined'?zeroxUser?.id:null)||getZeroXSession()?.userId;if(!owner)return null;const key='zx-island-funding:'+owner;const p=JSON.parse(sessionStorage.getItem(key)||'null');if(p&&(!returned||returned===p.id)&&/^[a-f0-9-]{36}$/.test(p.id)&&['all','card','oxxo','spei'].includes(p.method)){attempt=p.id;method=p.method;if(q('zx-island-amount'))q('zx-island-amount').value=p.amount;}return key;}catch{return null;}}
 function safeCheckout(url,redirect=false){const u=new URL(url);if(u.protocol!=='https:'||!['www.mercadopago.com.mx','www.mercadopago.com'].includes(u.hostname)||u.username||u.password)throw Error('INVALID_CHECKOUT');const link=q('zx-island-checkout');link.href=u.href;link.hidden=!redirect?false:true;if(redirect)location.assign(u.href);}
 async function fundingStatus(){if(!attempt||!token()||fundingBusy)return;const version=generation,current=token();fundingBusy=true;try{const data=await zeroxAuthRequest(FUNDING+'/intents/'+attempt,{cache:'no-store'});if(version!==generation||current!==token()||document.hidden)return;const names={pending:'Pendiente de pago o confirmación',verified:'Pago verificado',confirmed:'Saldo abonado',failed:'Pago rechazado',cancelled:'Pago cancelado',review_required:'Requiere revisión'};q('zx-island-funding-status').textContent=(names[data.state]||'Consulta pendiente')+' · '+money(data.amountCents);if(data.state==='pending'&&data.checkoutUrl)safeCheckout(data.checkoutUrl);else q('zx-island-checkout').hidden=true;if(data.state==='confirmed'){await refresh();if(current!==token()||document.hidden)return;q('zx-island-funding-status').textContent='Saldo abonado. Tu saldo se actualizó.';if(q('zx-island-new-funding'))q('zx-island-new-funding').hidden=false;}}catch{if(version===generation)q('zx-island-funding-status').textContent='No pudimos comprobar esta recarga. Conserva el intento; no prepares otro pago.';}finally{if(version===generation)fundingBusy=false;}}
 q('zx-island-funding-form')?.addEventListener('submit',async event=>{event.preventDefault();if(!fundingAvailable||attempt||fundingBusy||!token())return;const raw=q('zx-island-amount').value;if(!/^\d{1,4}(\.\d{1,2})?$/.test(raw))return;const cents=Math.round(Number(raw)*100);if(cents<1000||cents>500000)return;const version=generation,current=token();const storageKey=restoreAttempt();if(attempt){fundingStatus();return;}attempt=crypto.randomUUID();fundingBusy=true;try{if(storageKey)sessionStorage.setItem(storageKey,JSON.stringify({id:attempt,method,amount:raw}));}catch{}q('zx-island-amount').disabled=true;methods(true);q('zx-island-funding-refresh').hidden=false;q('zx-island-funding-status').textContent='Preparando recarga…';try{const data=await zeroxAuthRequest(FUNDING+'/checkout',{method:'POST',headers:{'Idempotency-Key':attempt},body:JSON.stringify({amountCents:cents,method,returnTo:'store'})});if(version!==generation||current!==token()||document.hidden)return;safeCheckout(data.checkoutUrl,true);q('zx-island-funding-status').textContent='Pago preparado. Revisa el importe en Mercado Pago. El saldo se abona después de la confirmación del servidor.';}catch{if(version===generation&&current===token())q('zx-island-funding-status').textContent='El intento necesita consulta o revisión. No vuelvas a preparar ni repetir el pago.';}finally{if(version===generation)fundingBusy=false;}});
 q('zx-island-funding-refresh')?.addEventListener('click',fundingStatus);
 q('zx-island-new-funding')?.addEventListener('click',()=>{const key=restoreAttempt();try{if(key)sessionStorage.removeItem(key);}catch{}attempt=null;method='all';if(typeof location!=='undefined'){const url=new URL(location.href);url.searchParams.delete('funding');history.replaceState(null,'',url);}q('zx-island-amount').disabled=false;q('zx-island-new-funding').hidden=true;q('zx-island-funding-status').textContent='Elige el importe de tu siguiente recarga.';methods(fundingAvailable);});
 q('zx-header-wallet').addEventListener('click',()=>{if(!token()){q('open-account').click();return;}if(island&&!island.open)island.showModal();restoreAttempt();refresh();});
 q('zx-wallet-island-close')?.addEventListener('click',()=>{island.close();q('zx-header-wallet').focus();});q('zx-wallet-island-refresh')?.addEventListener('click',refresh);
 island?.addEventListener('click',e=>{if(e.target!==island)return;const r=island.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)island.close();});
 window.addEventListener('zx-session-change',()=>{hide();attempt=null;method='all';});window.addEventListener('zx-account-ready',refresh);
 window.addEventListener('storage',e=>{if(e.key==='zerox-session'||e.key===null){hide();attempt=null;method='all';refresh();}});window.addEventListener('pagehide',hide);
 document.addEventListener('visibilitychange',()=>{if(document.hidden)hide();else refresh();});refresh();
})();
