(()=>{
 const $=id=>document.getElementById(id),dialog=$('status'),list=$('status-result');let page=0,version=0,query='',items=[],imageURL=null;
 const token=()=>{try{return JSON.parse(localStorage.getItem('zerox-session')||'null')?.token;}catch{return null;}};
 const api='https://zerox-sixofire-api.westdark161208.workers.dev/api/orders';
 async function request(path,options={}){const v=version,t=token();if(!t)throw Error('LOGIN_REQUIRED');const r=await fetch(api+path,{...options,cache:'no-store',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json'},signal:AbortSignal.timeout(20000)});if(v!==version||t!==token())throw Error('STALE');if(!r.ok){if(r.status===401){clear();throw Error('STALE');}throw Error((await r.json()).error||'REQUEST_FAILED');}return r;}
 function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
 function button(text,fn){const e=el('button',text);e.type='button';e.onclick=fn;return e;}
 const date=v=>new Date(v?.includes('T')?v:v+'Z').toLocaleString('es-MX');
 const states={COMPLETED:'Completado',PENDING_PAYMENT:'Pago pendiente',PAID:'Pago confirmado · Entrega pendiente',PROCESSING:'En proceso',REQUIRES_REVIEW:'En revisión',PARTIALLY_COMPLETED:'Entrega parcial',FAILED:'No completado'};
 function render(){list.replaceChildren();for(const o of items){const card=el('article',undefined,'zx-order-card');card.append(el('span',states[o.state]||'En revisión','zx-order-state'),el('h3',o.product),el('p',o.folio,'zx-order-folio'),el('p',date(o.createdAt)+' · ID de jugador: '+o.playerId));const amount=Number.isSafeInteger(o.amountMicros)?(o.amountMicros/1e6).toFixed(6):Number.isSafeInteger(o.amountCents)?(o.amountCents/100).toFixed(2):'—';card.append(el('strong',amount+' '+o.currency),el('p',o.method));const actions=el('div',undefined,'zx-order-actions');if(['diamond','service','bundle'].includes(o.kind))actions.append(button(o.completed?'Ver comprobante':'Ver seguimiento',()=>{if(o.completed)window.ZXPurchaseFlow.openReceipt(o.id,o.kind);else location.href=o.kind==='bundle'?'./promotions.html?order='+encodeURIComponent(o.id):'./product-payment.html?kind='+o.kind+'&order='+encodeURIComponent(o.id);}));if(o.completed)actions.append(button(o.reference?'Editar referencia ★':'Subir referencia ★',()=>edit(o)));card.append(actions);if(o.reference){card.append(el('p','★'.repeat(o.reference.rating)+' · '+o.reference.comment));if(o.reference.hasImage)card.append(button('Ver mi captura',()=>showImage(o)));}list.append(card);}}
 async function load(reset=true){const v=++version;if(reset){page=0;items=[];render();}$('orders-message').textContent=token()?'Consultando tus pedidos…':'Inicia sesión para ver tus compras.';$('orders-more').hidden=true;if(!token())return;
 try{const data=await (await request('/me?page='+page+'&q='+encodeURIComponent(query))).json();if(v!==version)return;items.push(...data.items);render();$('orders-more').hidden=!data.hasMore;$('orders-message').textContent=items.length?'':query?'No encontramos ese folio en tu cuenta.':'Aún no hay compras registradas en tu cuenta.';}catch(e){if(v===version&&e.message!=='STALE')$('orders-message').textContent='No pudimos cargar el historial. Pulsa Actualizar para intentarlo de nuevo.';}}
 function open(){if(!dialog.open)dialog.showModal();query='';$('status-form').elements.orderId.value='';load();}
 window.ZXOrderHistory={open,openReferences:()=>{community.hidden=false;community.open=true;if(!refs.children.length)refs.textContent='Todavía no hay referencias públicas. Puedes compartir la tuya desde un pedido completado.';community.scrollIntoView({block:'start'});}};$('status-form').onsubmit=e=>{e.preventDefault();query=e.currentTarget.elements.orderId.value.trim();load();};$('orders-refresh').onclick=()=>load();$('orders-more').onclick=()=>{page++;load(false);};
 const review=el('dialog',undefined,'zx-reference-modal');review.setAttribute('aria-label','Referencia de compra');review.innerHTML=`<button type="button" class="zx-ref-close" aria-label="Cerrar referencia">×</button><h2>Tu experiencia cuenta</h2><p data-product></p><form><label>Calificación<select name="rating" required><option value="">Elige de 1 a 5 estrellas</option><option value="5">★★★★★ · Excelente</option><option value="4">★★★★ · Buena</option><option value="3">★★★ · Regular</option><option value="2">★★ · Mala</option><option value="1">★ · Muy mala</option></select></label><label>Tu comentario<textarea name="comment" maxlength="1000" rows="3" required placeholder="Cuéntanos cómo fue tu compra"></textarea></label><label>Captura de la recarga (opcional)<input name="image" type="file" accept="image/jpeg,image/png,image/webp"></label><small>La captura queda privada en tu pedido. Puedes sustituirla subiendo otra.</small><label class="zx-ref-consent"><input name="public" type="checkbox"> Permito mostrar mi comentario y estrellas como referencia pública, sin mi nombre ni datos del pedido.</label><button type="submit">Guardar referencia</button><p role="status" data-message></p></form>`;document.body.append(review);review.querySelector('.zx-ref-close').onclick=()=>review.close();let selected=null;
 function edit(o){selected=o;const f=review.querySelector('form');f.reset();f.elements.rating.value=o.reference?.rating||'';f.elements.comment.value=o.reference?.comment||'';f.elements.public.checked=!!o.reference?.public;review.querySelector('[data-product]').textContent=o.product;review.querySelector('[data-message]').textContent='';review.showModal();}
 async function compress(file){if(file.size>10000000||!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('INVALID_IMAGE');const bitmap=await createImageBitmap(file);try{const scale=Math.min(1,1280/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.82);}finally{bitmap.close();}}
 review.querySelector('form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,o=selected,v=version,submit=f.querySelector('[type=submit]'),message=review.querySelector('[data-message]');submit.disabled=true;message.textContent='Guardando…';try{const image=f.elements.image.files[0]?await compress(f.elements.image.files[0]):null;if(v!==version)throw Error('STALE');await request('/reference?order='+encodeURIComponent(o.key),{method:'POST',body:JSON.stringify({rating:Number(f.elements.rating.value),comment:f.elements.comment.value,public:f.elements.public.checked,image})});if(v!==version)return;review.close();await load();$('orders-message').textContent='Referencia guardada. ¡Gracias por compartir tu experiencia!';}catch(e){if(v===version)message.textContent=e.message==='INVALID_IMAGE'?'Elige una imagen JPG, PNG o WebP de hasta 10 MB.':'No se pudo guardar. Conservamos el formulario para que vuelvas a intentarlo.';}finally{submit.disabled=false;}};
 const viewer=el('dialog',undefined,'zx-reference-modal');const photo=el('img');photo.alt='Tu captura de la recarga';viewer.append(button('Cerrar captura ×',()=>viewer.close()),photo);document.body.append(viewer);viewer.addEventListener('close',()=>{photo.removeAttribute('src');if(imageURL)URL.revokeObjectURL(imageURL);imageURL=null;});async function showImage(o){const v=version;try{const blob=await (await request('/reference/image?order='+encodeURIComponent(o.key))).blob();if(v!==version)return;if(imageURL)URL.revokeObjectURL(imageURL);imageURL=URL.createObjectURL(blob);photo.src=imageURL;viewer.showModal();}catch{if(v===version)$('orders-message').textContent='No pudimos cargar tu captura. Inténtalo otra vez.';}}
 function clear(){version++;items=[];render();selected=null;review.close();review.querySelector('form').reset();viewer.close();$('orders-message').textContent='Inicia sesión para ver tus compras.';$('orders-more').hidden=true;}
 window.addEventListener('zx-session-change',clear);window.addEventListener('storage',e=>{if(e.key==='zerox-session'||e.key===null)clear();});window.addEventListener('pagehide',clear);
 const reviewId=new URL(location.href).searchParams.get('review');if(reviewId){query=reviewId;$('status-form').elements.orderId.value=reviewId;dialog.showModal();load().then(()=>{const o=items.find(o=>o.id===reviewId&&o.completed);if(o)edit(o);});history.replaceState(null,'',location.pathname+location.hash);}
 // Real recent purchases only: never repeat an event during this browser session.
 const toast=el('aside',undefined,'zx-purchase-toast');toast.hidden=true;const avatar=el('span',undefined,'zx-activity-avatar');const note=el('div'),mute=button('×',()=>{sessionStorage.setItem('zx-activity-muted','1');toast.hidden=true;});mute.setAttribute('aria-label','Ocultar avisos de compras');toast.append(avatar,note,mute);document.body.append(toast);
 const community=el('details',undefined,'zx-community');community.id='referencias';community.append(el('summary','Referencias de compras verificadas'));const refs=el('div');community.append(refs);(document.querySelector('main')||document.body).append(community);community.hidden=true;
 let queue=[],cursor=0;let lastFetch=0;
 async function activity(){if(document.hidden||document.querySelector('dialog[open]')||sessionStorage.getItem('zx-activity-muted')==='1')return;if(Date.now()-lastFetch>120000){lastFetch=Date.now();try{const r=await fetch(api+'/activity',{cache:'no-store',signal:AbortSignal.timeout(10000)});if(r.ok){const data=await r.json();queue=data.items;refs.replaceChildren();for(const ref of data.references||[]){const block=el('blockquote');block.append(el('strong','★'.repeat(ref.rating)+' · Compra verificada'),el('p',ref.comment));refs.append(block);}community.hidden=!refs.children.length;}}catch{}}
 if(!queue.length||document.hidden||document.querySelector('dialog[open]')||sessionStorage.getItem('zx-activity-muted')==='1')return;const o=queue[cursor++%queue.length];avatar.replaceChildren();if(o.avatar&&/^data:image\/(jpeg|png|webp);base64,/.test(o.avatar)){const img=el('img');img.src=o.avatar;img.alt='';avatar.append(img);}else avatar.textContent=(o.customer||'ZX').replace('@','').slice(0,2).toUpperCase();note.replaceChildren(el('strong',o.customer+' compró '+o.product),el('small','Compra confirmada · '+date(o.completedAt)));toast.hidden=false;}
 new MutationObserver(()=>{if(document.querySelector('dialog[open]'))toast.hidden=true;}).observe(document.body,{attributes:true,attributeFilter:['open'],subtree:true});document.addEventListener('visibilitychange',()=>{if(document.hidden)toast.hidden=true;});setTimeout(activity,4000);setInterval(activity,4000);
})();
