(()=>{
 const q=id=>document.getElementById(id),api='https://zerox-sixofire-api.westdark161208.workers.dev/api/diamonds/purchase',order=new URL(location.href).searchParams.get('order');let version=0;
 const token=()=>{try{return JSON.parse(localStorage.getItem('zerox-session')||'null')?.token;}catch{return null;}};
 function clear(){version++;q('product-status').textContent='Inicia sesión en la tienda para consultar tu pedido.';q('product-delivery').textContent='';q('product-checkout').hidden=true;q('product-checkout').removeAttribute('href');q('product-resume').hidden=true;}
 async function request(path,options={}){const current=token(),v=version;if(!current)throw Error('LOGIN_REQUIRED');const response=await fetch(api+path,{...options,headers:{Authorization:'Bearer '+current,'Content-Type':'application/json'},cache:'no-store',signal:AbortSignal.timeout(20000)}),data=await response.json();if(v!==version||current!==token()||document.hidden)throw Error('STALE');if(!response.ok||!data.ok)throw Error(data.error);return data;}
 async function refresh(){const v=version;q('product-refresh').disabled=true;try{if(!/^[a-f0-9-]{36}$/.test(order||''))throw Error('INVALID_ORDER');const {order:o}=await request('/orders/'+order);q('product-status').textContent=({PENDING_PAYMENT:'Pago pendiente',PAID:'Pago confirmado',PROCESSING:'Entrega en proceso',REQUIRES_REVIEW:'Entrega en revisión',PARTIALLY_COMPLETED:'Entrega parcial',COMPLETED:'Diamantes entregados',FAILED:'Entrega fallida'})[o.state]||'Estado pendiente de revisión';q('product-delivery').textContent=o.delivered+' / '+o.diamonds+' diamantes confirmados';q('product-resume').hidden=(o.paymentState!=='paid'&&!o.recoveryAvailable)||['COMPLETED','FAILED'].includes(o.state);q('product-checkout').hidden=true;if(o.state==='PENDING_PAYMENT'&&o.checkout_url){const u=new URL(o.checkout_url);if(u.protocol==='https:'&&['www.mercadopago.com.mx','www.mercadopago.com'].includes(u.hostname)&&!u.username&&!u.password){q('product-checkout').href=u.href;q('product-checkout').hidden=false;}}}catch(e){if(v===version&&e.message!=='STALE')q('product-status').textContent=e.message==='LOGIN_REQUIRED'?'Inicia sesión en la tienda.':e.message==='PRODUCT_DELIVERY_NOT_READY'?'La entrega está pendiente de habilitación.':'No pudimos consultar tu pedido. No vuelvas a pagar hasta revisar el estado.';}finally{if(v===version)q('product-refresh').disabled=false;}}
 q('product-refresh').onclick=refresh;q('product-resume').onclick=async()=>{const v=version;q('product-resume').disabled=true;try{await request('/resume',{method:'POST',body:JSON.stringify({orderId:order})});await refresh();}catch{if(v===version)q('product-status').textContent='La entrega necesita revisión; no se repetirá un envío incierto.';}finally{if(v===version)q('product-resume').disabled=false;}};
 window.addEventListener('pagehide',clear);window.addEventListener('storage',e=>{if(e.key==='zerox-session'||e.key===null)clear();});document.addEventListener('visibilitychange',()=>{if(document.hidden)clear();else refresh();});refresh();
})();
