(()=>{
 const q=id=>document.getElementById(id),api='https://zerox-sixofire-api.westdark161208.workers.dev/api/diamonds/purchase',order=new URL(location.href).searchParams.get('order');let version=0,receipt=null;
 const token=()=>{try{return JSON.parse(localStorage.getItem('zerox-session')||'null')?.token;}catch{return null;}};
 function clearReceipt(){receipt=null;q('product-receipt').hidden=true;q('receipt-fields').replaceChildren();q('receipt-references').replaceChildren();q('receipt-total-value').textContent='';q('receipt-total-label').textContent='';q('receipt-payment-badge').textContent='';}
 function clear(){version++;clearReceipt();q('product-status').textContent='Inicia sesión en la tienda para consultar tu pedido.';q('product-delivery').textContent='';q('product-checkout').hidden=true;q('product-checkout').removeAttribute('href');q('product-resume').hidden=true;}
 async function request(path,options={}){const current=token(),v=version;if(!current)throw Error('LOGIN_REQUIRED');const response=await fetch(api+path,{...options,headers:{Authorization:'Bearer '+current,'Content-Type':'application/json'},cache:'no-store',signal:AbortSignal.timeout(20000)}),data=await response.json();if(v!==version||current!==token()||document.hidden)throw Error('STALE');if(!response.ok||!data.ok)throw Error(data.error);return data;}
 const methodNames={'ra-funds':'Saldo RA · cuenta fundadora',wallet:'Saldo Zero’X',card:'Tarjeta · Mercado Pago',oxxo:'OXXO · Mercado Pago',spei:'SPEI · Mercado Pago',all:'Mercado Pago'};
 function fields(r){const pairs=[['Folio',r.number],['Recarga',r.product],['ID del jugador',r.playerId],['Región',r.region||'—'],['Diamantes confirmados',String(r.diamonds)],['Confirmación',new Date(r.confirmedAt).toLocaleString('es-MX',{timeZone:'America/Mexico_City'})+' · México'],['Método',methodNames[r.method]||r.method]];
  pairs.push(r.method==='ra-funds'?['Coste cotizado al proveedor',(r.supplierQuotedCostMicros/1e6).toFixed(6)+' '+r.supplierCurrency]:['Importe',(r.amountCents/100).toFixed(2)+' '+r.currency]);return pairs;}
 function showReceipt(r){receipt=r;const supplier=r.method==='ra-funds';q('receipt-payment-badge').textContent=supplier?'✓ Fondos RA autorizados':'✓ Pago aprobado';q('receipt-total-label').textContent=supplier?'Coste cotizado al proveedor':'Total pagado';q('receipt-total-value').textContent=supplier?(Number.isSafeInteger(r.supplierQuotedCostMicros)&&r.supplierCurrency?(r.supplierQuotedCostMicros/1e6).toFixed(6)+' '+r.supplierCurrency:'No disponible'):(r.amountCents/100).toFixed(2)+' '+r.currency;const list=q('receipt-fields');list.replaceChildren();for(const [key,value] of fields(r)){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=value;list.append(dt,dd);}q('receipt-references').replaceChildren();for(const ref of r.references){const li=document.createElement('li');li.textContent=ref.provider+' · '+ref.reference+' · '+ref.diamonds+' diamantes';q('receipt-references').append(li);}q('receipt-notice').textContent=r.notice;q('product-receipt').hidden=false;}
 async function refresh(){const v=version;q('product-refresh').disabled=true;try{if(!/^[a-f0-9-]{36}$/.test(order||''))throw Error('INVALID_ORDER');const {order:o}=await request('/orders/'+order);clearReceipt();q('product-status').textContent=({PENDING_PAYMENT:'Pago pendiente',PAID:'Pago confirmado',PROCESSING:'Entrega en proceso',REQUIRES_REVIEW:'Entrega en revisión',PARTIALLY_COMPLETED:'Entrega parcial',COMPLETED:'Recarga completada ✓',FAILED:'Entrega fallida'})[o.state]||'Estado pendiente de revisión';if(o.paymentMethod==='ra-funds'&&o.state==='PAID')q('product-status').textContent='Recarga autorizada con fondos RA';q('product-delivery').textContent=o.delivered+' / '+o.diamonds+' diamantes confirmados'+(o.paymentMethod==='ra-funds'?' · Fondos de Recargas América, cuenta fundadora':'');q('product-resume').hidden=(o.paymentState!=='paid'&&!o.recoveryAvailable)||['COMPLETED','FAILED'].includes(o.state);q('product-checkout').hidden=true;
   if(o.state==='COMPLETED'){try{const data=await request('/orders/'+order+'/receipt');showReceipt(data.receipt);}catch(e){if(e.message==='STALE')return;q('product-delivery').textContent+=' · No pudimos cargar el comprobante. Pulsa Consultar estado.';}}
   if(o.state==='PENDING_PAYMENT'&&o.checkout_url){const u=new URL(o.checkout_url);if(u.protocol==='https:'&&['www.mercadopago.com.mx','www.mercadopago.com'].includes(u.hostname)&&!u.username&&!u.password){q('product-checkout').href=u.href;q('product-checkout').hidden=false;}}
  }catch(e){if(v===version&&e.message!=='STALE'){clearReceipt();q('product-status').textContent=e.message==='LOGIN_REQUIRED'?'Inicia sesión en la tienda.':'No pudimos consultar tu pedido. Conserva el enlace y revisa el estado antes de volver a comprar.';}}finally{if(v===version)q('product-refresh').disabled=false;}}
 q('product-download').onclick=()=>{if(!receipt||!token())return;const r=receipt,text=['ZERO’X STORE · COMPROBANTE DE RECARGA','ENTREGA CONFIRMADA',...fields(r).map(([k,v])=>k+': '+v),'Referencias del proveedor:',...r.references.map(x=>x.provider+' · '+x.reference+' · '+x.diamonds+' diamantes'),r.notice].join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='ZeroX-recarga-'+r.orderId+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 q('product-print').onclick=()=>{if(receipt&&token())window.print();};
 q('product-refresh').onclick=refresh;q('product-resume').onclick=async()=>{const v=version;q('product-resume').disabled=true;try{await request('/resume',{method:'POST',body:JSON.stringify({orderId:order})});await refresh();}catch{if(v===version)q('product-status').textContent='La entrega necesita revisión; no se repetirá un envío incierto.';}finally{if(v===version)q('product-resume').disabled=false;}};
 window.addEventListener('pagehide',clear);window.addEventListener('storage',e=>{if(e.key==='zerox-session'||e.key===null)clear();});document.addEventListener('visibilitychange',()=>{if(document.hidden)clear();else refresh();});refresh();
})();
