(()=>{
 const q=id=>document.getElementById(id),api='https://zerox-sixofire-api.westdark161208.workers.dev/api/diamonds/purchase',order=new URL(location.href).searchParams.get('order');let version=0,receipt=null,timer=null,busy=false,polls=0;const embedded=new URL(location.href).searchParams.get('embedded')==='1';if(embedded)document.body.classList.add('zx-receipt-embedded');
 const token=()=>{try{return JSON.parse(localStorage.getItem('zerox-session')||'null')?.token;}catch{return null;}};
 function clearReceipt(){receipt=null;document.body.classList.remove('zx-receipt-ready');if(q('receipt-modal').open)q('receipt-modal').close();q('product-reopen').hidden=true;q('product-receipt').hidden=true;q('receipt-fields').replaceChildren();q('receipt-total-value').textContent='';q('receipt-total-label').textContent='';q('receipt-payment-badge').textContent='';}
 function clear(){version++;clearTimeout(timer);busy=false;clearReceipt();q('product-status').textContent='Inicia sesión en la tienda para consultar tu pedido.';q('product-delivery').textContent='';q('product-checkout').hidden=true;q('product-checkout').removeAttribute('href');q('product-resume').hidden=true;}
 async function request(path,options={}){const current=token(),v=version;if(!current)throw Error('LOGIN_REQUIRED');const response=await fetch(api+path,{...options,headers:{Authorization:'Bearer '+current,'Content-Type':'application/json'},cache:'no-store',signal:AbortSignal.timeout(20000)}),data=await response.json();if(v!==version||current!==token()||document.hidden)throw Error('STALE');if(!response.ok||!data.ok)throw Error(data.error);return data;}
 const methodNames={balance:'Saldo de cuenta','ra-funds':'Saldo de cuenta',wallet:'Saldo Zero’X',card:'Tarjeta · Mercado Pago',oxxo:'OXXO · Mercado Pago',spei:'SPEI · Mercado Pago',all:'Mercado Pago'};
 function fields(r){const pairs=[['Folio',r.number],['Recarga',r.product],['ID del jugador',r.playerId],['Región',r.region||'—'],['Diamantes confirmados',String(r.diamonds)],['Confirmación',new Date(r.confirmedAt).toLocaleString('es-MX',{timeZone:'America/Mexico_City'})+' · México'],['Método',methodNames[r.method]||r.method]];
  pairs.push([r.amountLabel||'Total pagado',amount(r)]);return pairs;}
 function amount(r){return Number.isSafeInteger(r.amountMicros)?(r.amountMicros/1e6).toFixed(6)+' '+r.currency:(r.amountCents/100).toFixed(2)+' '+r.currency;}
 function reveal(){const modal=q('receipt-modal');if(!modal.open){if(embedded)modal.show();else modal.showModal();}}
 function showReceipt(r){q('product-reference').href='./?review='+encodeURIComponent(r.orderId);receipt=r;document.body.classList.add('zx-receipt-ready');q('receipt-payment-badge').textContent=r.method==='balance'?'✓ Saldo autorizado':'✓ Pago aprobado';q('receipt-total-label').textContent=r.amountLabel||'Total pagado';q('receipt-total-value').textContent=amount(r);const list=q('receipt-fields');list.replaceChildren();for(const [key,value] of fields(r).filter(([key])=>!['Región','Diamantes confirmados',r.amountLabel||'Total pagado'].includes(key))){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=value;list.append(dt,dd);}q('receipt-notice').textContent=r.notice;q('product-receipt').hidden=false;q('product-reopen').hidden=false;reveal();}

 async function refresh(){if(busy||document.hidden)return;clearTimeout(timer);busy=true;const v=version;q('product-refresh').disabled=true;try{if(!/^[a-f0-9-]{36}$/.test(order||''))throw Error('INVALID_ORDER');const {order:o}=await request('/orders/'+order);clearReceipt();q('product-status').textContent=({PENDING_PAYMENT:'Pago pendiente',PAID:'Pago confirmado',PROCESSING:'Entrega en proceso',REQUIRES_REVIEW:'Entrega en revisión',PARTIALLY_COMPLETED:'Entrega parcial',COMPLETED:'Recarga completada ✓',FAILED:'Entrega fallida'})[o.state]||'Estado pendiente de revisión';if(o.paymentMethod==='ra-funds'&&o.state==='PAID')q('product-status').textContent='Recarga autorizada con saldo';q('product-delivery').textContent=o.delivered+' / '+o.diamonds+' diamantes confirmados';q('product-resume').hidden=(o.paymentState!=='paid'&&!o.recoveryAvailable)||['COMPLETED','FAILED'].includes(o.state);q('product-checkout').hidden=true;
   if(o.state==='COMPLETED'){try{const data=await request('/orders/'+order+'/receipt');showReceipt(data.receipt);}catch(e){if(e.message==='STALE')return;q('product-delivery').textContent+=' · No pudimos cargar el comprobante. Pulsa Consultar estado.';}}
   if(o.state==='PENDING_PAYMENT'&&o.checkout_url){const u=new URL(o.checkout_url);if(u.protocol==='https:'&&['www.mercadopago.com.mx','www.mercadopago.com'].includes(u.hostname)&&!u.username&&!u.password){q('product-checkout').href=u.href;q('product-checkout').hidden=false;}}
  }catch(e){if(v===version&&e.message!=='STALE'){clearReceipt();q('product-status').textContent=e.message==='LOGIN_REQUIRED'?'Inicia sesión en la tienda.':'No pudimos consultar tu pedido. Conserva el enlace y revisa el estado antes de volver a comprar.';}}finally{if(v===version){busy=false;q('product-refresh').disabled=false;if(!receipt&&token()&&!document.hidden&&++polls<120)timer=setTimeout(refresh,5000);}}}
 q('product-download').onclick=()=>{if(!receipt||!token())return;const r=receipt,text=['ZERO’X STORE · COMPROBANTE DE RECARGA','ENTREGA CONFIRMADA',...fields(r).map(([k,v])=>k+': '+v),r.notice].join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='ZeroX-recarga-'+r.orderId+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 q('receipt-close').onclick=()=>q('receipt-modal').close();q('product-reopen').onclick=()=>{if(receipt&&token())reveal();};
 q('product-print').onclick=()=>{if(receipt&&token())window.print();};
 q('product-refresh').onclick=refresh;q('product-resume').onclick=async()=>{const v=version;q('product-resume').disabled=true;try{await request('/resume',{method:'POST',body:JSON.stringify({orderId:order})});await refresh();}catch{if(v===version)q('product-status').textContent='La entrega necesita revisión; no se repetirá un envío incierto.';}finally{if(v===version)q('product-resume').disabled=false;}};
 window.addEventListener('pagehide',clear);window.addEventListener('zx-session-change',clear);window.addEventListener('storage',e=>{if(e.key==='zerox-session'||e.key===null)clear();});document.addEventListener('visibilitychange',()=>{if(document.hidden)clear();else refresh();});refresh();
})();
