(()=>{
 const q=id=>document.getElementById(id),root='https://zerox-sixofire-api.westdark161208.workers.dev',params=new URLSearchParams(location.search),token=()=>{try{return JSON.parse(localStorage.getItem('zerox-session')||'null')?.token;}catch{return null;}},el=(tag,text)=>{const n=document.createElement(tag);if(text)n.textContent=text;return n;};let orderId=params.get('order'),activeAd=null,verified='',destinationVerified='',currentLine=null,busy=false,timer=null,lastUid='',requestKey=null,openedDestination=null;
 const errors={PROMOTION_PRICE_REQUIRED:'Publica el precio del combo en Zero’X Editor.',PROMOTION_DESCRIPTION_REQUIRED:'La promoción necesita cantidades y artículos precisos. Por ejemplo: 6160 diamantes + 21 cajas de fragmentos + 3 pases Booyah.',PRODUCT_DELIVERY_MAPPING_REQUIRED:'Uno de los artículos no tiene entrega disponible para esta cuenta. No se ha preparado el cobro.',WALLET_MOVEMENT_REJECTED:'No hay saldo suficiente para este combo.',LOGIN_REQUIRED:'Inicia sesión en la tienda para continuar.',DELIVERY_PRICE_CHANGED:'La entrega requiere revisión de disponibilidad. Tu pago se conserva; no vuelvas a pagar.',DESTINATION_LOCKED:'Este destino ya fue confirmado y no puede cambiarse.'};
 async function request(path,options={}){const t=token();if(!t)throw Error('LOGIN_REQUIRED');const r=await fetch(root+'/api/promotions'+path,{...options,cache:'no-store',headers:{Authorization:'Bearer '+t,'Content-Type':'application/json',...options.headers}}),b=await r.json();if(t!==token())throw Error('LOGIN_REQUIRED');if(!r.ok){const e=Error(b.error);e.orderId=b.orderId;throw e;}return b;}
 function message(e){return window.ZXCoupons.errors[e.message]||errors[e.message]||'No se confirmó la operación. Conserva tu pedido. Código: '+e.message;}
 async function verify(form,dest){const uid=form.elements.uid.value.trim(),out=form.querySelector('[data-player]');out.textContent='Consultando…';form.elements.confirmed.checked=false;if(dest)destinationVerified='';else verified='';try{const r=await fetch(root+'/api/player?uid='+encodeURIComponent(uid)+'&region=br'),b=await r.json(),p=b.player?.basicInfo;if(!r.ok||!b.ok||String(p?.accountId)!==uid||!p.nickname)throw Error('PLAYER_NOT_FOUND');if(form.elements.uid.value.trim()!==uid)return;out.textContent=p.nickname+' · ID '+uid;if(dest)destinationVerified=uid;else verified=uid;}catch{out.textContent='No pudimos verificar ese ID. Revisa e intenta otra vez.';}}
 const buy=q('promo-buy'),form=buy.querySelector('form'),dest=q('promo-destination'),df=dest.querySelector('form');for(const d of [buy,dest])d.querySelector('[data-close]').onclick=()=>d.close();form.querySelector('[data-verify]').onclick=()=>verify(form,false);df.querySelector('[data-verify]').onclick=()=>verify(df,true);form.elements.uid.oninput=()=>{verified='';form.elements.confirmed.checked=false;};df.elements.uid.oninput=()=>{destinationVerified='';df.elements.confirmed.checked=false;};df.querySelector('[data-reuse]').onclick=()=>{df.elements.uid.value=lastUid;verify(df,true);};
 const couponHost=document.createElement('div');form.querySelector('[data-total]').before(couponHost);let couponControl=null;
 form.elements.method.addEventListener('change',()=>couponControl?.setRetail(!['ra','sf'].includes(form.elements.method.value)));
 function openAd(ad){if(!token()){q('promo-status').textContent=errors.LOGIN_REQUIRED;return;}activeAd=ad;verified='';form.reset();couponControl=window.ZXCoupons.mount(couponHost,ad.priceCents||0,s=>form.querySelector('[data-total]').textContent='Total: $'+(s.amountCents/100).toFixed(2)+' MXN');requestKey=crypto.randomUUID();buy.querySelector('[data-title]').textContent=ad.title;form.querySelector('[data-player]').textContent='';form.querySelector('[data-result]').textContent='';form.querySelector('[data-total]').textContent=ad.priceCents?'Total: $'+(ad.priceCents/100).toFixed(2)+' MXN':'Precio pendiente de publicar';buy.showModal();}
 form.onsubmit=async e=>{e.preventDefault();if(busy)return;const out=form.querySelector('[data-result]');if(verified!==form.elements.uid.value.trim()||!form.elements.confirmed.checked){out.textContent='Comprueba y confirma la cuenta.';return;}busy=true;couponControl.lock();form.querySelector('[type=submit]').disabled=true;try{const body={adId:activeAd.id,playerId:verified,playerConfirmed:true,method:form.elements.method.value,couponCode:couponControl.state().couponCode},quote=await request('/quote',{method:'POST',body:JSON.stringify(body)});out.textContent=quote.lines.map(l=>l.label).join(' · ');form.querySelector('[data-total]').textContent='Total: $'+(quote.amountCents/100).toFixed(2)+' MXN';const accepted=['all','card','spei'].includes(form.elements.method.value)||await window.ZXPurchaseFlow.confirmBalance({product:quote.name,playerId:verified,paymentLabel:['all','card','spei'].includes(form.elements.method.value)?'Continuar a Mercado Pago':undefined,amount:quote.totalMicros?(quote.totalMicros/1e6).toFixed(6)+' USD · saldo API':'$'+(quote.amountCents/100).toFixed(2)+' MXN · '+(form.elements.method.value==='wallet'?'Saldo Zero’X':'Pago por Mercado Pago')});if(!accepted)return;const r=await request('/checkout',{method:'POST',headers:{'Idempotency-Key':requestKey},body:JSON.stringify({...body,contactPhone:form.elements.phone.value,method:form.elements.method.value,maxAmountCents:quote.amountCents,...(quote.totalMicros?{supplierConfirmed:true,maxTotalMicros:quote.totalMicros}:{})})});lastUid=verified;orderId=r.order.id;history.replaceState(null,'','?order='+orderId);buy.close();if(r.order.checkoutUrl){const u=new URL(r.order.checkoutUrl);if(u.protocol!=='https:'||!['www.mercadopago.com.mx','www.mercadopago.com'].includes(u.hostname)||u.username||u.password)throw Error('INVALID_CHECKOUT');location.assign(u.href);return;}renderOrder(r.order);poll();}catch(err){out.textContent=message(err);if(err.orderId){orderId=err.orderId;history.replaceState(null,'','?order='+orderId);buy.close();poll();}}finally{busy=false;couponControl.lock(false);form.querySelector('[type=submit]').disabled=false;}};
 function renderOrder(o){q('promo-list').hidden=true;const section=q('promo-order');section.hidden=false;section.replaceChildren(el('h2',o.product),el('p','Folio: ZX-'+o.id),el('strong',o.fundsMicros?(o.fundsMicros/1e6).toFixed(6)+' USD · saldo autorizado':'$'+(o.amountCents/100).toFixed(2)+' MXN'),el('p',({PENDING_PAYMENT:'Esperando confirmación del pago',PAID:'Pago confirmado · selecciona los destinos',PROCESSING:'Entrega en proceso',COMPLETED:'Compra completada ✓',REQUIRES_REVIEW:'Pedido en revisión. No vuelvas a pagar.'})[o.state]||o.state));
  if(o.paymentState!=='paid'&&o.checkoutUrl){const u=new URL(o.checkoutUrl);if(u.protocol==='https:'&&['www.mercadopago.com.mx','www.mercadopago.com'].includes(u.hostname)){const a=el('a','Ir a Mercado Pago →');a.href=u.href;a.className='zx-order-payment-link';section.append(a);}}
  for(const l of o.lines){const row=el('article');row.className='holo-chart';row.append(el('h3',l.label),el('p',l.playerId?'ID: '+l.playerId:'Cuenta por confirmar'),el('p',({WAITING_ID:'Pendiente de destino',PROCESSING:'Procesando',COMPLETED:'Entregado ✓',REQUIRES_REVIEW:'En revisión'})[l.state]||l.state));section.append(row);}
  const next=o.lines.find(l=>l.state!=='COMPLETED');if(o.paymentState==='paid'&&next){currentLine=next;const b=el('button',next.state==='WAITING_ID'?'Confirmar cuenta para '+next.label:'Continuar / consultar entrega');b.type='button';b.onclick=()=>next.state==='WAITING_ID'?openDestination(next):run();section.append(b);if(next.state==='WAITING_ID'&&!dest.open&&!busy&&openedDestination!==orderId+':'+next.sequence)openDestination(next);}if(o.state==='COMPLETED'){const b=el('button','Ver comprobante');b.onclick=()=>window.ZXPurchaseFlow.openReceipt(o.id,'bundle');section.append(b);if(!sessionStorage.getItem('zx-bundle-receipt:'+o.id)){sessionStorage.setItem('zx-bundle-receipt:'+o.id,'1');b.click();}}}
 function openDestination(l){openedDestination=orderId+':'+l.sequence;destinationVerified='';df.reset();dest.querySelector('[data-title]').textContent=l.label;df.querySelector('[data-reuse]').hidden=!lastUid||/pase|cuenta/i.test(l.label);df.querySelector('[data-player]').textContent='';df.querySelector('[data-result]').textContent='';dest.showModal();}
 df.onsubmit=async e=>{e.preventDefault();if(busy)return;const out=df.querySelector('[data-result]');if(destinationVerified!==df.elements.uid.value.trim()||!df.elements.confirmed.checked){out.textContent='Verifica y confirma esta cuenta.';return;}busy=true;try{await request('/orders/'+orderId+'/destination',{method:'POST',body:JSON.stringify({sequence:currentLine.sequence,playerId:destinationVerified,confirmed:true})});lastUid=destinationVerified;dest.close();busy=false;await run();}catch(err){out.textContent=message(err);}finally{busy=false;}};
 async function run(){if(busy)return;busy=true;try{const r=await request('/orders/'+orderId+'/run',{method:'POST',body:'{}'});renderOrder(r.order);}catch(err){q('promo-status').textContent=message(err);}finally{busy=false;poll();}}
 async function poll(){clearTimeout(timer);if(!orderId||document.hidden||!token())return;try{const r=await request('/orders/'+orderId);renderOrder(r.order);if(r.order.state!=='COMPLETED')timer=setTimeout(poll,5000);}catch(err){q('promo-status').textContent=message(err);}}
 async function load(){if(token()){try{const r=await fetch(root+'/api/auth/me',{headers:{Authorization:'Bearer '+token()},cache:'no-store'}),b=await r.json();if(b.user?.isFounder)for(const [value,label] of [['ra','Saldo RA · fundador'],['sf','Saldo SF · fundador']]){const opt=el('option',label);opt.value=value;form.elements.method.append(opt);}}catch{}}if(orderId){poll();return;}try{const [a,p]=await Promise.all([fetch(root+'/api/content/ads').then(r=>r.json()),fetch(root+'/api/store-editor/catalog').then(r=>r.json())]);for(const ad of a.ads||[]){const edit=p.products?.['entity:ads:'+ad.id];if(edit?.active===false)continue;const data={...ad,title:edit?.name||ad.title,description:edit?.description||ad.description,image:edit?.image||ad.image,priceCents:edit?.priceCents?ZXRetailPricing.priceCents(edit.priceCents):0};const card=el('article');card.className='holo-chart';const img=el('img');img.src=data.image;img.alt=data.title;img.style.width='100%';img.style.borderRadius='16px';const b=el('button','Comprar ahora →');b.onclick=()=>openAd(data);card.append(img,el('h2',data.title),el('p',data.description),el('strong',data.priceCents?'$'+(data.priceCents/100).toFixed(2)+' MXN':'Precio pendiente'),b);q('promo-list').append(card);if(ad.id===params.get('ad'))card.scrollIntoView({block:'start'});}if(!q('promo-list').children.length)q('promo-status').textContent='No hay promociones activas.';}catch{q('promo-status').textContent='No pudimos cargar las promociones.';}}
 window.addEventListener('pagehide',()=>clearTimeout(timer));window.addEventListener('storage',e=>{if(e.key==='zerox-session'||e.key===null){clearTimeout(timer);buy.close();dest.close();q('promo-order').replaceChildren();q('promo-status').textContent=errors.LOGIN_REQUIRED;}});document.addEventListener('visibilitychange',()=>{if(!document.hidden)poll();});load();
})();
