(()=>{
 const API='https://zerox-sixofire-api.westdark161208.workers.dev/api/admin/providers/',q=id=>document.getElementById(id);let generation=0;
 const token=()=>{try{return JSON.parse(localStorage.getItem('zerox-session')||'null')?.token}catch{return null}};
 const errors={RA_READ_DISABLED:'Las consultas de Recargas América están desactivadas.',RA_KEY_MISSING:'Falta RECARGAS_AMERICA_API_KEY en el servidor.',RA_HTTP_401:'Recargas América rechazó la clave.',RA_HTTP_403:'Recargas América no permite esta consulta.',RA_UNAVAILABLE:'Recargas América no respondió. No se realizaron compras.',RA_INVALID_RESPONSE:'Recargas América respondió con un formato distinto del contrato.',PROVIDER_KEY_MISSING:'La clave del proveedor no está configurada.',PROVIDER_CREDENTIAL_REJECTED:'El proveedor rechazó la credencial.',PROVIDER_RATE_LIMITED:'Se alcanzó el límite de consultas. Espera antes de volver a consultar.',SIXOFIRE_PERMISSION_DENIED:'La licencia no tiene el permiso SHOP_ORDER. Actívalo en Sixofire para consultar y crear órdenes.',SIXOFIRE_SUBSCRIPTION_REQUIRED:'Falta una suscripción activa que incluya SHOP_ORDER.',SIXOFIRE_SUBSCRIPTION_INACTIVE:'La suscripción de Sixofire está inactiva.',SIXOFIRE_SUBSCRIPTION_REQUESTS_EXHAUSTED:'La cuota de SHOP_ORDER está agotada.',PROVIDER_PERMISSION_OR_SUBSCRIPTION:'Sixofire denegó el acceso: revisa SHOP_ORDER y la suscripción/cuota.',PROVIDER_RESPONSE_FORMAT:'Sixofire respondió con un formato distinto del documentado. No se ha confirmado acceso a órdenes.',PROVIDER_PRICES_NOT_REPORTED:'El catálogo no informó precios válidos en USD.',INVALID_PLAYER_QUERY:'Revisa el ID y la región del jugador.'};
 Object.assign(errors,{PROVIDER_TIMEOUT:'Sixofire agotó el tiempo de respuesta. No se realizaron compras.',PROVIDER_CONNECTION_FAILED:'No se pudo conectar con Sixofire. No se realizaron compras.',PROVIDER_REDIRECT_REJECTED:'Sixofire devolvió una redirección no autorizada. No se reenviaron credenciales.',SIXOFIRE_INVALID_API_KEY:'Sixofire rechazó la licencia: puede ser inválida o estar pausada.',SIXOFIRE_MISSING_API_KEY:'Sixofire no reconoció la clave enviada por el servidor.',SIXOFIRE_RATE_LIMIT:'Sixofire limitó las consultas. Espera antes de intentarlo de nuevo.',SIXOFIRE_RATE_LIMITED:'Sixofire limitó las consultas. Espera antes de intentarlo de nuevo.',SIXOFIRE_INSUFFICIENT_FUNDS:'Sixofire informa saldo insuficiente.',SIXOFIRE_INSUFFICIENT_BALANCE:'Sixofire informa saldo GENERAL insuficiente.'});
 // Only numeric HTTP status is exposed, never a raw upstream body or message.
 for(let status=400;status<=599;status++)errors['PROVIDER_HTTP_'+status]=`Sixofire respondió HTTP ${status}. ${status===404?'La ruta de consulta no está disponible.':status>=500?'El proveedor no pudo completar la consulta.':'La consulta fue rechazada.'} No se realizaron compras.`;
 function clear(){generation++;for(const id of ['integrations-status','sixofire-status','sixofire-order-status','sixofire-quotes-status','ff-status','ra-catalog-status','ra-validate-status','sixofire-services-status','levelup-status'])q(id).textContent='';for(const id of ['sixofire-items','sixofire-quotes','ff-result','ra-catalog','sixofire-services','levelup-result'])q(id).replaceChildren();}
 async function read(path,status,button,render,method='GET',body=null){const current=token(),version=generation;if(!current)return;button.disabled=true;q(status).textContent='Consultando…';try{
  const response=await fetch(API+path,{method,headers:{Authorization:'Bearer '+current,...(body?{'Content-Type':'application/json'}:{})},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store',signal:AbortSignal.timeout(15000)}),data=await response.json();
  if(version!==generation||current!==token()||document.hidden)return;
  if(!response.ok||!data.ok)throw Error(errors[data.error]||'La consulta no está disponible. No se realizaron compras.');
  q(status).textContent='Consulta completada · '+new Date(data.queriedAt||Date.now()).toLocaleString('es-MX');render(data);
 }catch(e){if(version===generation&&current===token())q(status).textContent=Object.values(errors).includes(e.message)?e.message:'La consulta no está disponible. No se realizaron compras.';}finally{button.disabled=false;}}
 q('integrations-check').onclick=()=>read('integrations/status','integrations-status',q('integrations-check'),data=>{q('sixofire-status').textContent=data.integrations.find(i=>i.id==='sixofire')?.keyConfigured?'Clave configurada · conexión pendiente de consultar':'Clave pendiente';q('ff-status').textContent=data.integrations.find(i=>i.id==='freefire-info')?.keyConfigured?'Clave configurada · conexión pendiente de consultar':'Clave pendiente';});
 q('sixofire-check').onclick=()=>{q('sixofire-items').replaceChildren();read('sixofire/catalog','sixofire-status',q('sixofire-check'),({data})=>{const summary=document.createElement('li');summary.textContent=`${data.total} productos recibidos; se muestran hasta 100 referencias.`;q('sixofire-items').append(summary);for(const item of data.items){const li=document.createElement('li');li.textContent=[item.id,item.name,item.available?'Disponible':'No confirmado/disponible',item.itemType,item.priceUsd!=null?'USD '+item.priceUsd.toFixed(4):null,item.bonus?'Bono '+item.bonus:null,item.diamonds!=null?item.diamonds+' diamantes':null,...(item.regions||[])].filter(Boolean).join(' · ');q('sixofire-items').append(li);}if(data.total&&!data.items.length)summary.textContent='El proveedor respondió, pero su formato de catálogo requiere adaptar los campos.';});};
 q('sixofire-order-check').onclick=()=>read('sixofire/order-access','sixofire-order-status',q('sixofire-order-check'),()=>{q('sixofire-order-status').textContent='Consulta de órdenes autorizada. No confirma saldo ni permisos de escritura.';});
 q('sixofire-quotes-save').onclick=()=>read('sixofire/quotes','sixofire-quotes-status',q('sixofire-quotes-save'),d=>{q('sixofire-quotes-status').textContent=d.count+' precios guardados en USD. Consulta el historial para comparar.';},'POST');
 q('sixofire-quotes-read').onclick=()=>{q('sixofire-quotes').replaceChildren();read('sixofire/quotes','sixofire-quotes-status',q('sixofire-quotes-read'),d=>{if(!d.series.length){q('sixofire-quotes-status').textContent='Todavía no hay precios guardados.';return;}for(const s of d.series){const li=document.createElement('li'),title=document.createElement('strong'),note=document.createElement('p');title.textContent=s.id+' · '+s.name;const last=s.points.at(-1),first=s.points[0],delta=(last.micros-first.micros)/1e6;note.textContent='Último: USD '+(last.micros/1e6).toFixed(4)+' · Cambio registrado: '+(delta>0?'+':'')+delta.toFixed(4)+' USD · '+s.points.length+' consultas. Sin conversión a MXN.';li.append(title,note);if(s.points.length>1){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 300 80');svg.setAttribute('role','img');svg.setAttribute('aria-label','Precios históricos del proveedor en USD');const min=Math.min(...s.points.map(p=>p.micros)),max=Math.max(...s.points.map(p=>p.micros));const line=document.createElementNS(svg.namespaceURI,'polyline');line.setAttribute('points',s.points.map((p,i)=>(8+i*284/(s.points.length-1))+','+(max===min?40:70-(p.micros-min)/(max-min)*60)).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke','#8ef5a3');line.setAttribute('stroke-width','2');svg.append(line);li.append(svg);}else{const empty=document.createElement('p');empty.textContent='Una sola consulta: aún no existe una tendencia.';li.append(empty);}q('sixofire-quotes').append(li);}});};
 q('ff-query').addEventListener('submit',event=>{event.preventDefault();if(q('ff-check').disabled)return;q('ff-result').replaceChildren();read('freefire-info/player?'+new URLSearchParams({uid:q('ff-uid').value.trim(),region:q('ff-region').value}),'ff-status',q('ff-check'),({data})=>{for(const [key,label] of [['uid','ID'],['nickname','Jugador'],['region','Región'],['level','Nivel'],['rank','Rango'],['likes','Likes']]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=data[key]??'No informado';q('ff-result').append(dt,dd);}});});

 q('ra-catalog-check').onclick=()=>{q('ra-catalog').replaceChildren();read('recargas-america/catalog','ra-catalog-status',q('ra-catalog-check'),({data})=>{for(const p of data){const li=document.createElement('li');li.textContent=`${p.id} · ${p.sku} · ${p.name} · Precio proveedor ${p.price} (catálogo v1: USD) · ${p.type} · Campos: ${p.requiredFields.join(', ')}`;q('ra-catalog').append(li);}});};
 q('ra-validate-query').onsubmit=e=>{e.preventDefault();read('recargas-america/validate','ra-validate-status',q('ra-validate-check'),({data})=>{q('ra-validate-status').textContent=!data.supported?'Este producto no permite validar la cuenta en Recargas América. La verificación de Free Fire sigue siendo necesaria.':data.status?'Cuenta reconocida: '+(data.accountName||'sin nombre informado'):'El proveedor no confirmó esta cuenta.';},'POST',{productId:Number(q('ra-product-id').value),uid:q('ra-player-id').value.trim()});};
 q('sixofire-services-check').onclick=()=>{q('sixofire-services').replaceChildren();read('sixofire/services','sixofire-services-status',q('sixofire-services-check'),({data})=>{for(const p of data){const li=document.createElement('li');li.textContent=[p.id,p.name,p.category||'Pendiente de asociación',p.configured?'Código asociado':'Requiere asociar SKU',p.available?'Disponible':'No disponible',p.priceUsd!=null?'USD '+p.priceUsd:null,p.levelUpPackageId?'Paquete nivel '+p.levelUpPackageId:null].filter(Boolean).join(' · ');q('sixofire-services').append(li);}if(!data.length)q('sixofire-services-status').textContent='No se recibieron servicios compatibles. Las recargas de diamantes usan Recargas América.';});};
 q('levelup-query').onsubmit=e=>{e.preventDefault();q('levelup-result').replaceChildren();read('sixofire/level-up?'+new URLSearchParams({uid:q('levelup-uid').value.trim()}),'levelup-status',q('levelup-check'),({data})=>{q('levelup-status').textContent=(data.nickname||data.uid)+' · '+(data.region||'Sin región')+' · '+(data.levelUpAvailable?'Pases disponibles':'Sin pases disponibles');for(const p of data.packages){const li=document.createElement('li');li.textContent=p.itemId+' · '+p.name;q('levelup-result').append(li);}});};
 window.addEventListener('zx-control-clear',clear);window.addEventListener('pagehide',clear);
})();
