(()=>{
 const API='https://zerox-sixofire-api.westdark161208.workers.dev/api/admin/providers/',q=id=>document.getElementById(id);let generation=0;
 const token=()=>{try{return JSON.parse(localStorage.getItem('zerox-session')||'null')?.token}catch{return null}};
 const errors={PROVIDER_KEY_MISSING:'La clave del proveedor no está configurada.',PROVIDER_CREDENTIAL_REJECTED:'El proveedor rechazó la credencial.',PROVIDER_RATE_LIMITED:'Se alcanzó el límite de consultas. Espera antes de volver a consultar.',INVALID_PLAYER_QUERY:'Revisa el ID y la región del jugador.'};
 function clear(){generation++;for(const id of ['integrations-status','sixofire-status','ff-status'])q(id).textContent='';for(const id of ['sixofire-items','ff-result'])q(id).replaceChildren();}
 async function read(path,status,button,render){const current=token(),version=generation;if(!current)return;button.disabled=true;q(status).textContent='Consultando…';try{
  const response=await fetch(API+path,{headers:{Authorization:'Bearer '+current},cache:'no-store',signal:AbortSignal.timeout(15000)}),data=await response.json();
  if(version!==generation||current!==token()||document.hidden)return;
  if(!response.ok||!data.ok)throw Error(errors[data.error]||'La consulta no está disponible. No se realizaron compras.');
  render(data);q(status).textContent='Consulta completada · '+new Date(data.queriedAt||Date.now()).toLocaleString('es-MX');
 }catch(e){if(version===generation&&current===token())q(status).textContent=Object.values(errors).includes(e.message)?e.message:'La consulta no está disponible. No se realizaron compras.';}finally{button.disabled=false;}}
 q('integrations-check').onclick=()=>read('integrations/status','integrations-status',q('integrations-check'),data=>{q('sixofire-status').textContent=data.integrations.find(i=>i.id==='sixofire')?.keyConfigured?'Clave configurada · conexión pendiente de consultar':'Clave pendiente';q('ff-status').textContent=data.integrations.find(i=>i.id==='freefire-info')?.keyConfigured?'Clave configurada · conexión pendiente de consultar':'Clave pendiente';});
 q('sixofire-check').onclick=()=>{q('sixofire-items').replaceChildren();read('sixofire/catalog','sixofire-status',q('sixofire-check'),({data})=>{const summary=document.createElement('li');summary.textContent=`${data.total} productos recibidos; se muestran hasta 100 referencias.`;q('sixofire-items').append(summary);for(const item of data.items){const li=document.createElement('li');li.textContent=[item.id,item.name].filter(Boolean).join(' · ');q('sixofire-items').append(li);}if(data.total&&!data.items.length)summary.textContent='El proveedor respondió, pero su formato de catálogo requiere adaptar los campos.';});};
 q('ff-query').addEventListener('submit',event=>{event.preventDefault();if(q('ff-check').disabled)return;q('ff-result').replaceChildren();read('freefire-info/player?'+new URLSearchParams({uid:q('ff-uid').value.trim(),region:q('ff-region').value}),'ff-status',q('ff-check'),({data})=>{for(const [key,label] of [['uid','ID'],['nickname','Jugador'],['region','Región'],['level','Nivel'],['rank','Rango'],['likes','Likes']]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=data[key]??'No informado';q('ff-result').append(dt,dd);}});});
 window.addEventListener('zx-control-clear',clear);window.addEventListener('pagehide',clear);
})();
