(()=>{
 const API='https://zerox-sixofire-api.westdark161208.workers.dev/api/admin/providers/',q=id=>document.getElementById(id);let generation=0;
 const token=()=>{try{return JSON.parse(localStorage.getItem('zerox-session')||'null')?.token}catch{return null}};
 const errors={PROVIDER_KEY_MISSING:'La clave del proveedor no está configurada.',PROVIDER_CREDENTIAL_REJECTED:'El proveedor rechazó la credencial.',PROVIDER_RATE_LIMITED:'Se alcanzó el límite de consultas. Espera antes de volver a consultar.',SIXOFIRE_PERMISSION_DENIED:'La licencia no tiene el permiso SHOP_ORDER. Actívalo en Sixofire para consultar y crear órdenes.',SIXOFIRE_SUBSCRIPTION_REQUIRED:'Falta una suscripción activa que incluya SHOP_ORDER.',SIXOFIRE_SUBSCRIPTION_INACTIVE:'La suscripción de Sixofire está inactiva.',SIXOFIRE_SUBSCRIPTION_REQUESTS_EXHAUSTED:'La cuota de SHOP_ORDER está agotada.',PROVIDER_PERMISSION_OR_SUBSCRIPTION:'Sixofire denegó el acceso: revisa SHOP_ORDER y la suscripción/cuota.',PROVIDER_RESPONSE_FORMAT:'Sixofire respondió con un formato distinto del documentado. No se ha confirmado acceso a órdenes.',PROVIDER_PRICES_NOT_REPORTED:'El catálogo no informó precios válidos en USD.',INVALID_PLAYER_QUERY:'Revisa el ID y la región del jugador.'};
 function clear(){generation++;for(const id of ['integrations-status','sixofire-status','sixofire-order-status','sixofire-quotes-status','ff-status'])q(id).textContent='';for(const id of ['sixofire-items','sixofire-quotes','ff-result'])q(id).replaceChildren();}
 async function read(path,status,button,render,method='GET'){const current=token(),version=generation;if(!current)return;button.disabled=true;q(status).textContent='Consultando…';try{
  const response=await fetch(API+path,{method,headers:{Authorization:'Bearer '+current},cache:'no-store',signal:AbortSignal.timeout(15000)}),data=await response.json();
  if(version!==generation||current!==token()||document.hidden)return;
  if(!response.ok||!data.ok)throw Error(errors[data.error]||'La consulta no está disponible. No se realizaron compras.');
  q(status).textContent='Consulta completada · '+new Date(data.queriedAt||Date.now()).toLocaleString('es-MX');render(data);
 }catch(e){if(version===generation&&current===token())q(status).textContent=Object.values(errors).includes(e.message)?e.message:'La consulta no está disponible. No se realizaron compras.';}finally{button.disabled=false;}}
 q('integrations-check').onclick=()=>read('integrations/status','integrations-status',q('integrations-check'),data=>{q('sixofire-status').textContent=data.integrations.find(i=>i.id==='sixofire')?.keyConfigured?'Clave configurada · conexión pendiente de consultar':'Clave pendiente';q('ff-status').textContent=data.integrations.find(i=>i.id==='freefire-info')?.keyConfigured?'Clave configurada · conexión pendiente de consultar':'Clave pendiente';});
 q('sixofire-check').onclick=()=>{q('sixofire-items').replaceChildren();read('sixofire/catalog','sixofire-status',q('sixofire-check'),({data})=>{const summary=document.createElement('li');summary.textContent=`${data.total} productos recibidos; se muestran hasta 100 referencias.`;q('sixofire-items').append(summary);for(const item of data.items){const li=document.createElement('li');li.textContent=[item.id,item.name,item.available?'Disponible':'No confirmado/disponible',item.itemType,item.priceUsd!=null?'USD '+item.priceUsd.toFixed(4):null,item.bonus?'Bono '+item.bonus:null,item.diamonds!=null?item.diamonds+' diamantes':null,...(item.regions||[])].filter(Boolean).join(' · ');q('sixofire-items').append(li);}if(data.total&&!data.items.length)summary.textContent='El proveedor respondió, pero su formato de catálogo requiere adaptar los campos.';});};
 q('sixofire-order-check').onclick=()=>read('sixofire/order-access','sixofire-order-status',q('sixofire-order-check'),()=>{q('sixofire-order-status').textContent='Consulta de órdenes autorizada. No confirma saldo ni permisos de escritura.';});
 q('sixofire-quotes-save').onclick=()=>read('sixofire/quotes','sixofire-quotes-status',q('sixofire-quotes-save'),d=>{q('sixofire-quotes-status').textContent=d.count+' precios guardados en USD. Consulta el historial para comparar.';},'POST');
 q('sixofire-quotes-read').onclick=()=>{q('sixofire-quotes').replaceChildren();read('sixofire/quotes','sixofire-quotes-status',q('sixofire-quotes-read'),d=>{if(!d.series.length){q('sixofire-quotes-status').textContent='Todavía no hay precios guardados.';return;}for(const s of d.series){const li=document.createElement('li'),title=document.createElement('strong'),note=document.createElement('p');title.textContent=s.id+' · '+s.name;const last=s.points.at(-1),first=s.points[0],delta=(last.micros-first.micros)/1e6;note.textContent='Último: USD '+(last.micros/1e6).toFixed(4)+' · Cambio registrado: '+(delta>0?'+':'')+delta.toFixed(4)+' USD · '+s.points.length+' consultas. Sin conversión a MXN.';li.append(title,note);if(s.points.length>1){const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 300 80');svg.setAttribute('role','img');svg.setAttribute('aria-label','Precios históricos del proveedor en USD');const min=Math.min(...s.points.map(p=>p.micros)),max=Math.max(...s.points.map(p=>p.micros));const line=document.createElementNS(svg.namespaceURI,'polyline');line.setAttribute('points',s.points.map((p,i)=>(8+i*284/(s.points.length-1))+','+(max===min?40:70-(p.micros-min)/(max-min)*60)).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke','#8ef5a3');line.setAttribute('stroke-width','2');svg.append(line);li.append(svg);}else{const empty=document.createElement('p');empty.textContent='Una sola consulta: aún no existe una tendencia.';li.append(empty);}q('sixofire-quotes').append(li);}});};
 q('ff-query').addEventListener('submit',event=>{event.preventDefault();if(q('ff-check').disabled)return;q('ff-result').replaceChildren();read('freefire-info/player?'+new URLSearchParams({uid:q('ff-uid').value.trim(),region:q('ff-region').value}),'ff-status',q('ff-check'),({data})=>{for(const [key,label] of [['uid','ID'],['nickname','Jugador'],['region','Región'],['level','Nivel'],['rank','Rango'],['likes','Likes']]){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=data[key]??'No informado';q('ff-result').append(dt,dd);}});});
 window.addEventListener('zx-control-clear',clear);window.addEventListener('pagehide',clear);
})();
