(()=>{
const q=s=>document.querySelector(s),names=['Novato','Principiante','Élite','Maestro','Titán','Legendario','Zero’X Supreme'];
const fmt=c=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(c/100);
const labels={pending:'Pendiente',approved:'Acreditado',rejected:'Rechazado',completed:'Entregado',refunded:'Reembolsado',credit:'Abono',purchase:'Compra',refund:'Reembolso'};
const errors={LOGIN_REQUIRED:'Inicia sesión para acceder a tu cuenta de revendedor.',LEVEL_LOCKED:'Este nivel sigue bloqueado.',INSUFFICIENT_BALANCE:'No tienes saldo suficiente.',PLAYER_NOT_VERIFIED:'No pudimos validar este ID en la región seleccionada. No se descontó saldo.',PLAYER_VERIFICATION_UNAVAILABLE:'La verificación no está disponible. Intenta más tarde.',PENDING_TOPUP_EXISTS:'Ya tienes depósitos pendientes de revisión.',INVALID_ORDER_OR_LEVEL:'Revisa la cantidad, el ID y el nivel seleccionado.'};
let me=null,tier=0,catalog=[],selected=null,key=null,refreshId=0;
async function api(path,body){const d=await zeroxAuthRequest('/api/resellers'+path,body?{method:'POST',body:JSON.stringify(body)}:{});if(!d.ok)throw Error(d.error||'SERVICE_UNAVAILABLE');return d}
const failure=e=>errors[e.message]||'No se pudo completar la operación. Intenta nuevamente. ('+e.message+')';
const status=t=>q('#r-status').textContent=t;
function levels(){q('#r-levels').innerHTML=names.map((name,i)=>{const unlocked=!!me&&i<me.tier;return `<button type="button" data-r-tier="${i+1}" class="r-level ${unlocked?'is-open':'is-locked'}" aria-label="${esc(name)}: ${unlocked?'abrir panel':'bloqueado'}"><b>${String(i+1).padStart(2,'0')}</b><strong>${esc(name)}</strong><span>${unlocked?'◇ ENTRAR AL PANEL':'🔒 BLOQUEADO'}</span><small>${i===0?'Ingreso confirmado de $200 MXN':i<5?[0,10,30,50,100][i]+' ventas / 7 días':(i===5?'500':'1,000')+' ventas / 30 días'}</small></button>`}).join('')}
async function refresh(){const generation=++refreshId;status('Consultando acceso y saldo…');q('#r-shop').hidden=true;q('#r-levels').hidden=false;tier=0;me=null;catalog=[];q('#r-products').replaceChildren();q('#r-history').replaceChildren();q('#r-balance').textContent='—';q('#r-access').textContent='Inicia sesión';q('#r-progress').textContent='';levels();try{const d=await api('/me');if(generation!==refreshId)return;me=d;q('#r-balance').textContent=fmt(d.balanceCents);q('#r-access').textContent=d.isFounder?'Fundador · 7 paneles':d.tier?names[d.tier-1]:'Pendiente de activación';q('#r-progress').textContent=`Tus ventas completadas: ${d.weekly} en 7 días y ${d.monthly} en 30 días.`;levels();history();status(d.isFounder?'Acceso de fundador: elige cualquiera de los siete paneles.':d.tier?'Elige un nivel desbloqueado para entrar.':'Tus paneles se activan al acreditar tu primer ingreso de $200 MXN.')}catch(e){if(generation===refreshId)status(failure(e))}}
function history(){const root=q('#r-history');root.replaceChildren();for(const [title,rows] of [['Pedidos',me.orders],['Depósitos',me.topups],['Movimientos',me.ledger]]){const h=document.createElement('h4');h.textContent=title;root.append(h);if(!rows.length){const p=document.createElement('p');p.textContent='Sin registros todavía.';root.append(p)}for(const row of rows){const p=document.createElement('p');p.textContent=row.product_name?`${row.product_name} × ${row.quantity} · ${fmt(row.total)} · ${labels[row.status]} · ID ${row.uid} · Folio ${row.id}`:`${fmt(row.amount)} · ${labels[row.status||row.kind]} · ${row.created_at}`;root.append(p)}}}
async function openTier(n){if(!me||n>me.tier){status(!me?'Inicia sesión para consultar tu acceso.':n===1?'Registra tu ingreso de $200 MXN y espera su confirmación.':'Completa las ventas indicadas para desbloquear este nivel.');q('#r-status').scrollIntoView({behavior:'smooth',block:'center'});return}const generation=++refreshId;status('Abriendo '+names[n-1]+'…');try{const d=await api('/catalog?tier='+n);if(generation!==refreshId)return;tier=n;catalog=d.products;q('#r-levels').hidden=true;q('#r-shop').hidden=false;q('#r-shop-name').textContent=`${String(n).padStart(2,'0')} · ${d.name}`;q('#r-shop').dataset.tier=n;q('#r-categories').innerHTML=['Todos','Pases Booyah','Fragmentos','Cajas','Diamantes','Streaming'].map((c,i)=>`<button type="button" data-r-category="${c}" class="${i===0?'active':''}">${c}</button>`).join('');render('Todos');status('Precios del nivel '+d.name+' · Saldo '+fmt(me.balanceCents));q('#r-shop').scrollIntoView({behavior:'smooth'})}catch(e){status(failure(e))}}
function render(category){const rows=catalog.filter(p=>category==='Todos'||p.category===category);q('#r-products').innerHTML=rows.length?rows.map(p=>{const normal=PRODUCTS.find(x=>x.id===p.id);return `<article class="product-card r-product"><div class="r-art">${normal?artFor(normal):''}</div><small>${esc(p.category)}</small><h4>${esc(p.name)}</h4><p>Desde ${p.min} unidades</p><strong>${fmt(p.unitCents)} <small>por unidad</small></strong><p>Total mínimo: ${fmt(p.unitCents*p.min)}</p><button type="button" data-r-buy="${p.id}">COMPRAR CON SALDO →</button></article>`}).join(''):'<div class="zx-empty"><strong>PRECIOS EN PREPARACIÓN</strong><p>Pronto podrás consultar aquí los productos y precios de esta categoría.</p></div>'}
function checkout(id){selected=catalog.find(x=>x.id===id);if(!selected)return;key=crypto.randomUUID();const f=q('#r-buy-form');f.reset();f.elements.quantity.min=selected.min;f.elements.quantity.max=selected.max;f.elements.quantity.value=selected.min;q('#r-buy-name').textContent=selected.name;q('#r-unit').textContent=`Nivel ${names[tier-1]} · ${fmt(selected.unitCents)} por unidad`;q('#r-buy-status').textContent='';total();q('#r-checkout').showModal()}
function total(){if(selected)q('#r-total').textContent='Total: '+fmt(selected.unitCents*Number(q('#r-buy-form').elements.quantity.value||0))}
q('#r-levels').onclick=e=>{const b=e.target.closest('[data-r-tier]');if(b)openTier(Number(b.dataset.rTier))};q('#r-refresh').onclick=refresh;q('#r-back').onclick=refresh;
q('#r-categories').onclick=e=>{const b=e.target.closest('[data-r-category]');if(!b)return;q('#r-categories').querySelectorAll('button').forEach(x=>x.classList.toggle('active',x===b));render(b.dataset.rCategory)};
q('#r-products').onclick=e=>{const b=e.target.closest('[data-r-buy]');if(b)checkout(b.dataset.rBuy)};
q('#r-close').onclick=()=>q('#r-checkout').close();q('#r-buy-form').elements.quantity.oninput=total;
q('#r-buy-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,button=q('#r-pay');button.disabled=true;q('#r-close').disabled=true;q('#r-buy-status').textContent='Verificando ID y saldo…';try{const d=await api('/orders',{requestId:key,tier,productId:selected.id,quantity:Number(f.elements.quantity.value),uid:f.elements.uid.value.trim(),region:f.elements.region.value});q('#r-checkout').close();await refresh();status(`Pedido ${d.order.id} registrado para ${d.order.nickname}. Se descontaron ${fmt(d.order.total)}. Entrega manual pendiente.`)}catch(err){q('#r-buy-status').textContent=failure(err)}finally{button.disabled=false;q('#r-close').disabled=false}};
q('#r-deposit-form').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,b=e.submitter;b.disabled=true;try{await api('/topups',{requestId:crypto.randomUUID(),amountCents:Math.round(Number(f.elements.amount.value)*100),note:f.elements.note.value.trim()});f.reset();await refresh();status('Depósito registrado. El saldo se abonará cuando el fundador confirme que recibió el pago.')}catch(err){status(failure(err))}finally{b.disabled=false}};
window.zxResellerOpen=refresh;
})();
