(()=>{
 const API='https://zerox-sixofire-api.westdark161208.workers.dev';
 const el=id=>document.getElementById(id);let generation=0,pending=null,busy=false;
 const sessionToken=()=>{try{return JSON.parse(localStorage.getItem('zerox-session')||'null')?.token||null}catch{return null}};
 const date=value=>{const d=new Date(value.includes('T')?value:value.replace(' ','T')+'Z');return Number.isNaN(d.getTime())?'Fecha no disponible':d.toLocaleString('es-MX');};
 function clear(){generation++;el('private').hidden=true;el('sessions').replaceChildren();el('events').replaceChildren();el('confirm-dialog').close();pending=null;}
 async function request(path,body){const token=sessionToken();if(!token)throw Error('Inicia sesión desde la tienda.');const response=await fetch(API+'/api/security/'+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{}),cache:'no-store'});if(response.status===401){if(sessionToken()===token)localStorage.removeItem('zerox-session');clear();el('status').textContent='Tu sesión terminó. Vuelve a iniciar sesión desde la tienda.';throw Error('Tu sesión terminó. Vuelve a iniciar sesión.');}if(!response.ok)throw Error('No se pudo completar la operación. Intenta nuevamente.');if(sessionToken()!==token)throw Error('La sesión cambió. Vuelve a consultar.');return response.json();}
 function controls(disabled){busy=disabled;el('refresh').disabled=disabled;el('revoke-all').disabled=disabled;el('sessions').querySelectorAll('button').forEach(b=>b.disabled=disabled);}
 async function load(){if(busy)return;clear();const version=generation;if(!sessionToken()){el('status').textContent='Inicia sesión desde la tienda para consultar tu seguridad.';return;}controls(true);el('status').textContent='Consultando…';try{const [data,history]=await Promise.all([request('sessions'),request('events')]);if(version!==generation)return;for(const s of data.sessions){const row=document.createElement('li'),info=document.createElement('div'),title=document.createElement('strong'),detail=document.createElement('small'),button=document.createElement('button');title.textContent=s.current?'Esta sesión':'Otra sesión';detail.textContent='Inicio: '+date(s.created_at)+' · Vence: '+date(s.expires_at);button.type='button';button.textContent='Cerrar sesión';button.onclick=()=>confirm(s.id,s.current);info.append(title,detail);row.append(info,button);el('sessions').append(row);}for(const event of history.events){const li=document.createElement('li');li.textContent=({ 'sessions.revoke_all':'Cierre de todas las sesiones','sessions.revoke':'Cierre de una sesión'}[event.action]||'Acción de seguridad')+' · '+date(event.created_at);el('events').append(li);}if(!history.events.length){const li=document.createElement('li');li.textContent='Aún no hay cierres registrados.';el('events').append(li);}el('private').hidden=false;el('status').textContent=data.sessions.length+' sesión(es) activa(s).';}catch(e){if(version===generation)el('status').textContent=e.message;}finally{controls(false);}}
 function confirm(id,current=false){if(busy)return;pending={id,token:sessionToken(),version:generation};el('confirm-text').textContent=id?(current?'Se cerrará la sesión que estás usando.':'Esta sesión dejará de tener acceso a tu cuenta.'):'Se cerrarán todas las sesiones, incluida esta. Tendrás que iniciar sesión nuevamente.';el('confirm-dialog').returnValue='';el('confirm-dialog').showModal();}
 el('confirm-dialog').addEventListener('close',async()=>{const target=pending;pending=null;if(!target||el('confirm-dialog').returnValue!=='confirm'||target.token!==sessionToken()||target.version!==generation)return;controls(true);el('status').textContent='Cerrando sesión…';try{const result=await request('sessions/'+(target.id?'revoke':'revoke-all'),target.id?{sessionId:target.id}:{confirm:true});if(target.version!==generation||target.token!==sessionToken())return;if(result.signOut){localStorage.removeItem('zerox-session');clear();el('status').textContent='Sesión cerrada. Puedes volver a iniciar sesión desde la tienda.';}else{controls(false);await load();}}catch(e){if(target.version===generation)el('status').textContent=e.message;}finally{controls(false);}});
 el('refresh').onclick=load;el('revoke-all').onclick=()=>confirm(null);
 window.addEventListener('storage',e=>{if(e.key==='zerox-session'){clear();el('status').textContent='La sesión cambió. Actualiza para continuar.';}});window.addEventListener('pagehide',clear);document.addEventListener('visibilitychange',()=>{if(document.hidden)clear();else load();});load();
})();
