/* Editor on the actual storefront. Drafts require server authorization. */
(()=>{
 async function api(path,options){const token=getZeroXSession()?.token;const data=await zeroxAuthRequest(path,options);if(!token||getZeroXSession()?.token!==token)throw Error('Sesión finalizada');return data;}
 const base=new Map(PRODUCTS.filter(p=>p.zxDiamond).map(p=>[p.id,{...p}]));
 let published={},draft={},revision=0,editing=false,busy=false;
 const link=document.getElementById('creator-link');if(!link)return;
 const entry=document.createElement('button');entry.type='button';entry.className='zx-creator-link';entry.textContent='✎ Zero’X Editor · Diamantes';entry.hidden=true;link.after(entry);
 const bar=document.createElement('aside');bar.id='zx-editor-bar';bar.hidden=true;
 bar.innerHTML='<strong>Zero’X Editor</strong><span>Borrador · 50 paquetes de diamantes</span><button type="button" data-preview>Vista previa</button><button type="button" data-publish>Publicar borrador</button><button type="button" data-exit>Salir</button><p role="status"></p>';document.body.append(bar);
 const dialog=document.createElement('dialog');dialog.id='zx-editor-dialog';dialog.innerHTML=`<form><h2>Editar paquete</h2><p data-amount></p><label>Nombre<input name="name" maxlength="100" required></label><label>Personaje<input name="character" maxlength="100"></label><label>Precio MXN<input name="price" type="number" min="1" max="1000000" step="0.01" required></label><label>Descripción<textarea name="description" maxlength="1500"></textarea></label><label>Imagen<input name="image" required></label><label>Subir imagen<input name="upload" type="file" accept="image/png,image/jpeg,image/webp"></label><label><input name="active" type="checkbox"> Disponible</label><p role="status"></p><div><button type="submit">Guardar borrador</button><button type="button" data-cancel>Cancelar</button></div></form>`;document.body.append(dialog);
 const form=dialog.querySelector('form'),fields=form.elements;
 const status=text=>bar.querySelector('[role=status]').textContent=text;
 const message=text=>dialog.querySelector('[role=status]').textContent=text;
 function apply(map){for(const [id,b]of base){const p=PRODUCTS.find(p=>p.id===id),o=map[id];Object.assign(p,b);delete p.collectionOverride;if(o){Object.assign(p,{name:o.name,price:o.priceCents/100,description:o.description,active:o.active,collectionOverride:o});}}render();renderCart();decorate();}
 function decorate(){document.querySelectorAll('#products [data-product]').forEach(card=>{card.classList.toggle('zx-custom-name',!!PRODUCTS.find(p=>p.id===card.dataset.product)?.collectionOverride);if(!base.has(card.dataset.product)||card.querySelector('[data-zx-edit]')||!editing)return;const b=document.createElement('button');b.type='button';b.dataset.zxEdit=card.dataset.product;b.textContent='✎ Editar paquete';b.onclick=()=>open(b.dataset.zxEdit);card.append(b);});}
 // In editor mode show hidden packages too, without changing their saved availability.
 function preview(){apply(draft);for(const p of PRODUCTS)if(base.has(p.id))p.active=true;render();decorate();}
 function stop(){editing=false;bar.hidden=true;document.body.classList.remove('zx-editing');dialog.close();apply(published);document.querySelectorAll('[data-zx-edit]').forEach(b=>b.remove());}
 function current(id){const b=base.get(id),v=ZXDiamondCatalog.find(p=>p.id===id);return draft[id]||{id,name:b.name,character:v.character,priceCents:Math.round(b.price*100),description:b.description,active:b.active,image:v.image};}
 function open(id){const p=current(id);form.dataset.id=id;fields.name.value=p.name;fields.character.value=p.character;fields.price.value=(p.priceCents/100).toFixed(2);fields.description.value=p.description;fields.image.value=p.image;fields.active.checked=p.active;fields.upload.value='';dialog.querySelector('[data-amount]').textContent=base.get(id).diamonds.toLocaleString('es-MX')+' diamantes · Cantidad fija';message('');dialog.showModal();}
 async function run(fn){if(busy)return;busy=true;bar.querySelectorAll('button').forEach(b=>b.disabled=true);form.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn()}catch(e){const text=e.message==='EDITOR_CONFLICT'?'El borrador cambió en otra sesión. Sal y vuelve a abrir el editor.':'No se guardó: '+e.message;status(text);message(text);if(bar.hidden)alert(text)}finally{busy=false;bar.querySelectorAll('button').forEach(b=>b.disabled=false);form.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 entry.onclick=()=>run(async()=>{const data=await api('/api/admin/store-editor');revision=data.revision;draft=JSON.parse(data.draft);published=JSON.parse(data.published);editing=true;bar.hidden=false;document.body.classList.add('zx-editing');document.getElementById('account-modal')?.close();zxOpenCatalog('Diamantes ilimitados');preview();status('Toca «Editar paquete». Los cambios guardados aún no son públicos.');});
 form.onsubmit=e=>{e.preventDefault();run(async()=>{const cents=Number(fields.price.value)*100;if(Math.abs(cents-Math.round(cents))>0.00001)throw Error('Usa máximo dos decimales');const product={id:form.dataset.id,name:fields.name.value,character:fields.character.value,description:fields.description.value,image:fields.image.value,active:fields.active.checked,priceCents:Math.round(cents)};const data=await api('/api/admin/store-editor/draft',{method:'POST',body:JSON.stringify({revision,product})});revision=data.revision;draft[product.id]=product;dialog.close();preview();status('Borrador guardado. Revisa la vista previa antes de publicar.');});};
 fields.upload.onchange=()=>run(async()=>{const file=fields.upload.files[0];if(!file)return;if(file.size>8000000)throw Error('Máximo 8 MB');const body=new FormData();body.append('file',file);const response=await fetch(ZEROX_API+'/api/admin/catalog/media',{method:'POST',headers:{Authorization:'Bearer '+getZeroXSession()?.token},body});const data=await response.json();if(!response.ok)throw Error(data.error||'Error al subir imagen');fields.image.value=data.url;message('Imagen subida. Guarda el borrador para aplicarla.');});
 dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();
 bar.querySelector('[data-preview]').onclick=()=>{apply(draft);status('Vista previa: solo productos disponibles. Para editar ocultos vuelve a entrar al editor.');};
 bar.querySelector('[data-exit]').onclick=stop;
 bar.querySelector('[data-publish]').onclick=()=>run(async()=>{if(!confirm('¿Publicar los nombres, precios, imágenes y disponibilidad del borrador?'))return;const data=await api('/api/admin/store-editor/publish',{method:'POST',body:JSON.stringify({revision,confirm:true})});revision=data.revision;published=structuredClone(draft);apply(published);status('Publicado. La tienda ya utiliza este catálogo.');});
 new MutationObserver(decorate).observe(document.getElementById('products'),{childList:true});
 const sync=()=>{entry.hidden=link.hidden;if(link.hidden&&editing)stop();};new MutationObserver(sync).observe(link,{attributes:true,attributeFilter:['hidden']});sync();
 fetch(ZEROX_API+'/api/store-editor/catalog').then(r=>{if(!r.ok)throw Error('catalog');return r.json()}).then(d=>{published=d.products||{};if(!editing)apply(published)}).catch(()=>{});
 // Never permit test checkout or cart mutations while previewing unpublished values.
 document.addEventListener('click',e=>{if(editing&&e.target.closest('[data-buy-now],[data-add],[data-r-buy]')){e.preventDefault();e.stopImmediatePropagation();status('Sal del editor para comprar con el catálogo publicado.');}},true);
})();
