/* Editor on the actual storefront. Drafts require server authorization. */
(()=>{
 async function api(path,options){const token=getZeroXSession()?.token;const data=await zeroxAuthRequest(path,options);if(!token||getZeroXSession()?.token!==token)throw Error('Sesión finalizada');return data;}
 const base=new Map(PRODUCTS.map(p=>[p.id,{...p}]));
 let adBase=ZEROX_ADS.map(a=>({...a}));
 let published={},draft={},revision=0,editing=false,busy=false,selecting=false;
 const link=document.getElementById('creator-link');if(!link)return;
 const entry=document.createElement('button');entry.type='button';entry.className='zx-creator-link';entry.textContent='✎ Zero’X Editor · Toda la tienda';entry.hidden=true;link.after(entry);const control=document.createElement('a');control.href='./control.html';control.textContent='◈ Zero’X Control';control.className='zx-creator-link';control.hidden=true;entry.after(control);
 const bar=document.createElement('aside');bar.id='zx-editor-bar';bar.hidden=true;
 bar.innerHTML='<strong>Zero’X Editor</strong><span>Borrador · Contenido de la tienda</span><select aria-label="Seleccionar artículo o sección" data-target><option value="">Seleccionar elemento…</option></select><button type="button" data-select>Seleccionar en tienda</button><button type="button" data-preview>Vista previa</button><button type="button" data-publish>Publicar borrador</button><button type="button" data-exit>Salir</button><p role="status"></p>';document.body.append(bar);
 const dialog=document.createElement('dialog');dialog.id='zx-editor-dialog';dialog.innerHTML=`<form><h2>Editar elemento</h2><p data-amount></p><label>Nombre<input name="name" maxlength="100" required></label><label>Personaje<input name="character" maxlength="100"></label><label>Precio base MXN<input name="price" type="number" min="1" max="1000000" step="0.01" required></label><p>El precio público incluye costos de operación: referencia 3.49% + $4 MXN, más 16% de IVA sobre esa comisión. Se calcula una vez por paquete; todos los métodos usan el mismo precio.</p><p data-final-price></p><label>Categoría / etiqueta<input name="category" maxlength="80"></label><label>Región comercial<input name="region" maxlength="60"></label><label>Orden<input name="position" type="number" min="0" max="9999" step="1" value="0"></label><label>Descripción<textarea name="description" maxlength="1500"></textarea></label><label>Imagen<input name="image"></label><img data-image-preview alt="Vista previa de la imagen" hidden><label>Subir imagen<input name="upload" type="file" accept="image/png,image/jpeg,image/webp"></label><label><input name="active" type="checkbox"> Disponible</label><p role="status"></p><div><button type="submit">Guardar borrador</button><button type="button" data-cancel>Cancelar</button></div></form>`;document.body.append(dialog);
 const form=dialog.querySelector('form'),fields=form.elements;
 const pageOriginals=new Map();
 for(const e of ZXEditorElements){const node=document.querySelector(e.selector);if(!node)continue;const item={id:'page:'+e.id,label:e.label,name:e.imageOnly?e.label:(e.card?node.querySelector('strong')?.textContent:node.textContent)?.trim()||e.label,character:e.card?node.querySelector('small')?.textContent||'':'',description:e.card?node.querySelector('span')?.textContent||'':'',image:e.card?node.querySelector('img')?.getAttribute('src')||'':'',price:0,active:true,position:0};base.set(item.id,item);pageOriginals.set(item.id,{element:e,node,item,background:node.style.backgroundImage,backgroundPriority:node.style.getPropertyPriority('background-image'),display:node.style.display});}
 function pricePreview(){const value=Number(fields.price.value);dialog.querySelector('[data-final-price]').textContent=Number.isFinite(value)&&value>=0?'Precio público para una unidad: '+money(ZXRetailPricing.priceMXN(value))+' · En artículos por cantidad se calcula sobre el paquete completo.':'';}
 fields.price.oninput=pricePreview;
 function showImage(){const image=dialog.querySelector('[data-image-preview]');image.hidden=!fields.image.value;image.src=fields.image.value;}
 function applyAds(map){const rows=adBase.map(a=>{const o=map['entity:ads:'+a.id];return o?{...a,title:o.name,kicker:o.character,text:o.description,image:o.image||a.image,active:o.active,position:o.position,priceCents:o.priceCents}:a;}).filter(a=>a.active!==false).sort((a,b)=>(a.position||0)-(b.position||0));ZEROX_ADS.splice(0,ZEROX_ADS.length,...rows);const zone=document.querySelector('.zerox-ad-zone');if(zone)zone.style.display=rows.length?'':'none';buildAdDots();if(rows.length)renderZeroXAd(0);}
 document.addEventListener('zx-ads-loaded',()=>{adBase=ZEROX_ADS.map(a=>({...a}));applyAds(editing?draft:published);});
 function applyPage(map){for(const [id,{element:e,node,item,background,backgroundPriority,display}]of pageOriginals){const o=map[id]||{...item,priceCents:0};if(e.imageOnly){node.style.setProperty('background-image',o.image?'url("'+o.image+'")':background,o.image?'important':backgroundPriority);continue;}if(e.card){if(node.querySelector('strong'))node.querySelector('strong').textContent=o.name;if(node.querySelector('small'))node.querySelector('small').textContent=o.character;if(node.querySelector('span'))node.querySelector('span').textContent=o.description;if(o.image&&node.querySelector('img'))node.querySelector('img').src=o.image;node.style.order=String(o.position||0);}else node.textContent=o.name;node.style.display=o.active===false&&!editing?'none':display;}}
 async function loadElements(){
  const requests=[['catalog','/api/admin/catalog/products','products'],['streaming','/api/admin/content/streaming','products'],['ads','/api/admin/content/ads','ads']];
  for(const [kind,path,key]of requests){const data=await api(path);for(const p of data[key]||[]){const id='entity:'+kind+':'+p.id;base.set(id,{id,name:p.name||p.title,character:p.kicker||'',description:p.description||'',image:p.imageUrl||p.image||'',price:p.price||0,active:p.active!==false&&p.active!==0,category:p.section||kind,position:p.position||0,label:kind+' · '+(p.name||p.title)});}}
  const select=bar.querySelector('[data-target]');select.replaceChildren(new Option('Seleccionar elemento…',''));for(const [id,p]of base)select.add(new Option(p.label||p.category+' · '+p.name,id));
 }
 bar.querySelector('[data-select]').onclick=()=>{selecting=!selecting;bar.querySelector('[data-select]').textContent=selecting?'Volver a navegar':'Seleccionar en tienda';status(selecting?'Toca el título o bloque que quieres editar.':'Navega por la tienda; cada artículo muestra su botón de edición.');};
 bar.querySelector('[data-target]').onchange=e=>{if(e.target.value)open(e.target.value);e.target.value='';};
 document.addEventListener('click',event=>{if(!editing||!selecting||event.target.closest('#zx-editor-bar,#zx-editor-dialog'))return;for(const [id,{element:e}]of pageOriginals){if(e.imageOnly)continue;if(event.target.closest(e.selector)){event.preventDefault();event.stopImmediatePropagation();open(id);return;}}},true);

 const status=text=>bar.querySelector('[role=status]').textContent=text;
 fields.image.oninput=showImage;
 const message=text=>dialog.querySelector('[role=status]').textContent=text;
 function apply(map){for(const [id,b]of base){const p=PRODUCTS.find(p=>p.id===id),o=map[id];if(!p)continue;Object.assign(p,b);delete p.collectionOverride;delete p.editorImage;delete p.editorCategory;delete p.editorRegion;delete p.editorPosition;if(o){Object.assign(p,{name:o.name,price:o.priceCents/100,description:o.description,active:o.active,collectionOverride:o,editorImage:o.image,editorCategory:o.category,editorRegion:o.region,editorPosition:o.position});}}render();renderCart();applyPage(map);applyAds(map);decorate();}
 function decorate(){document.querySelectorAll('#products [data-product],#zx-managed-grid [data-product]').forEach(card=>{card.classList.toggle('zx-custom-name',!!PRODUCTS.find(p=>p.id===card.dataset.product)?.collectionOverride);const override=(editing?draft:published)[card.dataset.product];if(override&&card.dataset.product.startsWith('entity:')){const heading=card.querySelector('h3');if(heading)heading.textContent=override.name;let image=card.querySelector('.zx-media-art img');if(!image&&override.image){image=document.createElement('img');image.alt=override.name;card.querySelector('.zx-media-art')?.replaceChildren(image);}if(image&&override.image)image.src=override.image;const description=card.querySelector('h3 + p');if(description)description.textContent=override.description;const price=card.querySelector('.zx-managed-price');if(price){price.textContent=money(ZXRetailPricing.priceMXN(override.priceCents/100));price.dataset.zxBasePrice=ZXRetailPricing.priceMXN(override.priceCents/100);}}if(!base.has(card.dataset.product)||card.querySelector('[data-zx-edit]')||!editing)return;const b=document.createElement('button');b.type='button';b.dataset.zxEdit=card.dataset.product;b.textContent='✎ Editar artículo';b.onclick=()=>open(b.dataset.zxEdit);card.append(b);});}
 // In editor mode show hidden packages too, without changing their saved availability.
 function preview(){apply(draft);for(const p of PRODUCTS)if(base.has(p.id))p.active=true;render();decorate();}
 function stop(){editing=false;selecting=false;bar.hidden=true;document.body.classList.remove('zx-editing');dialog.close();apply(published);document.querySelectorAll('[data-zx-edit]').forEach(b=>b.remove());}
 function current(id){const b=base.get(id),v=ZXDiamondCatalog.find(p=>p.id===id);return draft[id]||{id,name:b.name,character:v?.character||b.character||'',priceCents:Math.round((b.price||0)*100),description:b.description||'',active:b.active!==false,image:v?.image||b.image||'',category:b.category||'',region:b.region||'',position:b.position||0};}
 function open(id){const p=current(id);form.dataset.id=id;fields.name.value=p.name;fields.character.value=p.character;fields.price.value=(p.priceCents/100).toFixed(2);fields.description.value=p.description;fields.image.value=p.image;fields.active.checked=p.active;fields.category.value=p.category||'';fields.region.value=p.region||'';fields.position.value=p.position||0;fields.upload.value='';dialog.querySelector('[data-amount]').textContent=base.get(id).diamonds?base.get(id).diamonds.toLocaleString('es-MX')+' diamantes · Cantidad fija':base.get(id).label||id;const content=id.startsWith('page:');fields.price.closest('label').hidden=content;fields.price.required=!content;fields.price.min=content?'0':'1';showImage();pricePreview();message('');dialog.showModal();}
 async function run(fn){if(busy)return;busy=true;bar.querySelectorAll('button').forEach(b=>b.disabled=true);form.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn()}catch(e){const text=e.message==='EDITOR_CONFLICT'?'El borrador cambió en otra sesión. Sal y vuelve a abrir el editor.':'No se guardó: '+e.message;status(text);message(text);if(bar.hidden)alert(text)}finally{busy=false;bar.querySelectorAll('button').forEach(b=>b.disabled=false);form.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 entry.onclick=()=>run(async()=>{const data=await api('/api/admin/store-editor');revision=data.revision;draft=JSON.parse(data.draft);published=JSON.parse(data.published);await loadElements();editing=true;bar.hidden=false;document.body.classList.add('zx-editing');document.getElementById('account-modal')?.close();preview();status('Selecciona un artículo o toca un bloque de la portada. Navega a cualquier sección para editar sus productos.');});
 form.onsubmit=e=>{e.preventDefault();run(async()=>{const cents=Number(fields.price.value)*100;if(Math.abs(cents-Math.round(cents))>0.00001)throw Error('Usa máximo dos decimales');const product={id:form.dataset.id,name:fields.name.value,character:fields.character.value,description:fields.description.value,image:fields.image.value,active:fields.active.checked,priceCents:Math.round(cents),category:fields.category.value,region:fields.region.value,position:Number(fields.position.value)};const data=await api('/api/admin/store-editor/draft',{method:'POST',body:JSON.stringify({revision,product})});revision=data.revision;draft[product.id]=product;dialog.close();preview();status('Borrador guardado. Revisa la vista previa antes de publicar.');});};
 fields.upload.onchange=()=>run(async()=>{const file=fields.upload.files[0];if(!file)return;if(file.size>8000000)throw Error('Máximo 8 MB');const token=getZeroXSession()?.token;const body=new FormData();body.append('file',file);const response=await fetch(ZEROX_API+'/api/admin/catalog/media',{method:'POST',headers:{Authorization:'Bearer '+getZeroXSession()?.token},body});const data=await response.json();if(!response.ok)throw Error(data.error||'Error al subir imagen');if(token!==getZeroXSession()?.token)throw Error('Sesión finalizada');fields.image.value=data.url;showImage();message('Imagen subida. Guarda el borrador para aplicarla.');});
 dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();
 bar.querySelector('[data-preview]').onclick=()=>{apply(draft);status('Vista previa: solo productos disponibles. Para editar ocultos vuelve a entrar al editor.');};
 bar.querySelector('[data-exit]').onclick=stop;
 bar.querySelector('[data-publish]').onclick=()=>run(async()=>{if(!confirm('¿Publicar los nombres, precios, imágenes y disponibilidad del borrador?'))return;const data=await api('/api/admin/store-editor/publish',{method:'POST',body:JSON.stringify({revision,confirm:true})});revision=data.revision;published=structuredClone(draft);apply(published);status('Publicado. La tienda ya utiliza este catálogo.');});
 for(const id of ['products','zx-managed-grid'])new MutationObserver(decorate).observe(document.getElementById(id),{childList:true});
 const sync=()=>{entry.hidden=link.hidden;control.hidden=link.hidden;if(link.hidden&&editing)stop();};new MutationObserver(sync).observe(link,{attributes:true,attributeFilter:['hidden']});sync();
 fetch(ZEROX_API+'/api/store-editor/catalog').then(r=>{if(!r.ok)throw Error('catalog');return r.json()}).then(d=>{published=d.products||{};if(!editing)apply(published)}).catch(()=>{});
 // Never permit test checkout or cart mutations while previewing unpublished values.
 document.addEventListener('click',e=>{if(editing&&e.target.closest('[data-buy-now],[data-add],[data-r-buy]')){e.preventDefault();e.stopImmediatePropagation();status('Sal del editor para comprar con el catálogo publicado.');}},true);
})();
