import test from 'node:test';
import assert from 'node:assert/strict';
import {database} from './helpers/d1.mjs';
import {walletAdminRoute} from '../cloudflare/wallet/admin.mjs';
import {walletSchema,postMovement} from '../cloudflare/wallet/ledger.mjs';
const founder={id:'founder',username:'Founder',status:'active',isFounder:true};
const reply=(b,s=200)=>Response.json(b,{status:s});
async function setup(){const DB=database();DB.sql.exec(`CREATE TABLE zx_users(id TEXT PRIMARY KEY,username TEXT,email TEXT,status TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);INSERT INTO zx_users(id,username,email,status) VALUES('founder','Founder','f@test','active'),('buyer','Buyer','b@test','active');CREATE TABLE zx_sessions(id TEXT,user_id TEXT,revoked_at TEXT);INSERT INTO zx_sessions VALUES('session','buyer',NULL);`);await walletSchema(DB);return {DB};}
const call=(env,body,user=founder)=>{const url=new URL('https://test/api/admin/customers/account');return walletAdminRoute(new Request(url,{method:'POST',body:JSON.stringify(body)}),env,url,user,reply);};
const deletion={userId:'buyer',username:'Buyer',confirmed:true,action:'delete'};
test('only founder can remove accounts; explicit account confirmation and founder protection required',async()=>{const env=await setup();assert.equal((await call(env,deletion,{...founder,isFounder:false})).status,403);assert.equal((await call(env,{...deletion,confirmed:false})).status,400);assert.equal((await call(env,{...deletion,username:'Another'})).status,409);assert.equal((await call(env,{...deletion,userId:'founder',username:'Founder'})).status,409);assert.equal(env.DB.sql.prepare("SELECT status FROM zx_users WHERE id='buyer'").get().status,'active');});
test('removal revokes sessions, retains records, audits once and restores without restoring sessions',async()=>{const env=await setup();assert.equal((await call(env,deletion)).status,200);assert.equal((await call(env,deletion)).status,409);assert.equal(env.DB.sql.prepare('SELECT COUNT(*) n FROM zx_account_actions').get().n,1);assert.equal(env.DB.sql.prepare("SELECT status FROM zx_users WHERE id='buyer'").get().status,'deleted');assert.ok(env.DB.sql.prepare('SELECT revoked_at FROM zx_sessions').get().revoked_at);assert.equal((await call(env,{...deletion,action:'restore'})).status,200);assert.equal(env.DB.sql.prepare("SELECT status FROM zx_users WHERE id='buyer'").get().status,'active');assert.ok(env.DB.sql.prepare('SELECT revoked_at FROM zx_sessions').get().revoked_at);});
test('balance and unsettled orders block removal without revoking sessions',async()=>{for(const kind of ['wallet','order','reseller']){const env=await setup();if(kind==='wallet')await postMovement(env.DB,{userId:'buyer',kind:'credit',amountCents:2000,currency:'MXN',source:'test',reference:'seed',requestKey:'seed',actor:'test'});if(kind==='order')env.DB.sql.exec("CREATE TABLE zx_service_orders(user_id TEXT,state TEXT);INSERT INTO zx_service_orders VALUES('buyer','PENDING_PAYMENT')");if(kind==='reseller')env.DB.sql.exec("CREATE TABLE zx_r_ledger(user_id TEXT,amount INTEGER);INSERT INTO zx_r_ledger VALUES('buyer',20000)");assert.equal((await call(env,deletion)).status,409);assert.equal(env.DB.sql.prepare("SELECT status FROM zx_users WHERE id='buyer'").get().status,'active');assert.equal(env.DB.sql.prepare('SELECT revoked_at FROM zx_sessions').get().revoked_at,null);}});
test('inactive filter uses recent activity when available and excludes removed accounts from country counts',async()=>{const env=await setup();env.DB.sql.exec("UPDATE zx_users SET created_at=datetime('now','-40 days') WHERE id='buyer'");const url=new URL('https://test/api/admin/customers?activity=inactive');let r=await(await walletAdminRoute(new Request(url),env,url,founder,reply)).json();assert.deepEqual(r.users.map(u=>u.id),['buyer']);env.DB.sql.exec("INSERT INTO zx_account_activity(user_id) VALUES('buyer')");r=await(await walletAdminRoute(new Request(url),env,url,founder,reply)).json();assert.equal(r.users.length,0);await call(env,deletion);const all=new URL('https://test/api/admin/customers');r=await(await walletAdminRoute(new Request(all),env,all,founder,reply)).json();assert.equal(r.users.length,1);assert.equal(r.countries[0].count,1);});
