import test from 'node:test';import assert from 'node:assert/strict';
import {database} from './helpers/d1.mjs';import {communityRoute,decodeReviewMedia} from '../cloudflare/community.mjs';
import {giftMessage,validGiftMessage} from '../cloudflare/providers/gift-message.mjs';
const user={id:'u',status:'active'},json=(b,s=200)=>new Response(JSON.stringify(b),{status:s});
function setup(){const DB=database(),objects=new Map();DB.sql.exec(`CREATE TABLE zx_r_orders(id TEXT,user_id TEXT,product_name TEXT,uid TEXT,status TEXT,total INTEGER,created_at TEXT,completed_at TEXT);CREATE TABLE zx_users(id TEXT,username TEXT,status TEXT);INSERT INTO zx_users VALUES('u','Player','active');`);return {DB,objects,MEDIA:{put:async(k,b,m)=>objects.set(k,{body:b,...m}),get:async k=>objects.get(k),delete:async k=>objects.delete(k)}};}
async function add(e,id,status='completed'){await e.DB.prepare("INSERT INTO zx_r_orders VALUES(?,'u','Pase','123456789',?,3500,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)").bind(id,status).run();}
async function call(e,path,u=null,b){const url=new URL('https://test/api/community'+path);return communityRoute(new Request(url,{method:b?'POST':'GET',body:b?JSON.stringify(b):undefined}),e,url,u,json);}
const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aZ1sAAAAASUVORK5CYII=';
test('review ownership, ten stars and explicit media publication consent',async()=>{const e=setup();await add(e,'a');await add(e,'pending','pending');const b={rating:10,comment:'Mi compra',public:false,media:[png,png]};assert.equal((await call(e,'/review?order=reseller:a',null,b)).status,401);assert.equal((await call(e,'/review?order=reseller:a',{id:'x',status:'active'},b)).status,404);assert.equal((await call(e,'/review?order=reseller:pending',user,b)).status,409);assert.equal((await call(e,'/review?order=reseller:a',user,{...b,rating:11})).status,400);let r=await (await call(e,'/review?order=reseller:a',user,b)).json();assert.equal(r.ok,true);assert.equal((await (await call(e,'/reviews')).json()).items.length,0);assert.equal((await call(e,'/media/'+r.id+'/0')).status,404);assert.equal((await call(e,'/media/'+r.id+'/0',user)).status,200);await call(e,'/review?order=reseller:a',user,{...b,public:true,media:[]});let d=await (await call(e,'/reviews')).json();assert.equal(d.items[0].rating,10);assert.equal(d.items[0].media.length,2);assert.equal(d.items[0].username,'Player');assert.doesNotMatch(JSON.stringify(d),/123456789|reseller:a|review-media/);assert.equal((await call(e,'/media/'+r.id+'/0')).headers.get('content-type'),'image/png');await call(e,'/review?order=reseller:a',user,{...b,public:false,media:[]});assert.equal((await call(e,'/media/'+r.id+'/0')).status,404);assert.equal(e.DB.sql.prepare('SELECT COUNT(*) n FROM zx_reviews').get().n,1);});
test('leaderboard unlocks at 100 completed sales, never pending or duplicate review counts',async()=>{const e=setup();for(let i=0;i<99;i++)await add(e,'s'+i);for(let i=0;i<10;i++)await add(e,'p'+i,'pending');let d=await (await call(e,'/top')).json();assert.equal(d.unlocked,false);assert.equal(d.completedSales,99);assert.deepEqual(d.items,[]);await add(e,'100');d=await (await call(e,'/top?period=year')).json();assert.equal(d.unlocked,true);assert.equal(d.items[0].purchases,100);assert.equal(d.items[0].username,'Player');assert.doesNotMatch(JSON.stringify(d),/user_id|123456789/);});
test('old public reviews retain anonymity; old private screenshots never migrate to public',async()=>{const e=setup();await add(e,'a');e.DB.sql.exec("CREATE TABLE zx_order_references(order_key TEXT,user_id TEXT,rating INTEGER,comment TEXT,image_key TEXT,public INTEGER,created_at TEXT);INSERT INTO zx_order_references VALUES('reseller:a','u',5,'Anterior','secret',1,CURRENT_TIMESTAMP)");const d=await (await call(e,'/reviews')).json();assert.equal(d.items[0].rating,10);assert.equal(d.items[0].username,'Cliente');assert.equal(d.items[0].id,null);assert.deepEqual(d.items[0].media,[]);});
test('media validation rejects executable content and excessive files; gift message is bounded',()=>{assert.throws(()=>decodeReviewMedia(['data:image/png;base64,PHN2Zz4=']));assert.throws(()=>decodeReviewMedia(Array(6).fill(png)));assert.equal(decodeReviewMedia([png]).length,1);assert.equal(validGiftMessage('x'.repeat(101)),false);assert.equal(validGiftMessage('hola\n'),false);assert.match(giftMessage({}),/zeroxstore.com/);assert.equal(giftMessage({giftMessage:'Gracias Zero X'}),'Gracias Zero X');});
test('Sixofire GIFT orders carry configured message; other item types do not',async()=>{const {submitDelivery}=await import('../cloudflare/services/delivery.mjs');const base={provider:'sixofire',productId:'1042',name:'Booyah Pass',price:1,quantity:1,region:'US',itemType:'GIFT',message:'Gracias ZeroX https://zeroxstore.com'};for(const itemType of ['GIFT','DIAMONDS_DIRECT']){let body;const plan={...base,itemType};await submitDelivery({SIXOFIRE_DELIVERY_ENABLED:'true',SIXOFIRE_API_KEY:'test'},plan,'123456789','key',async(url,opts)=>{if(url.endsWith('/items'))return new Response(JSON.stringify({data:{items:[{id:'1042',name:plan.name,available:true,isActive:true,itemType,priceUsd:1}]}}));body=JSON.parse(opts.body);return new Response(JSON.stringify({status:true,code:201,data:{id:123,gameAccount:{uid:'123456789',region:'US'},totalPriceUsd:1,status:'COMPLETED',items:[{name:plan.name,itemType,quantity:1,status:'COMPLETED'}]}}));});assert.equal(body.message,itemType==='GIFT'?base.message:undefined);assert.equal(body.product_id,'1042');}});
