import test from 'node:test';import assert from 'node:assert/strict';
import {gameItem,gameDelivery} from '../cloudflare/services/games.mjs';
import {database} from './helpers/d1.mjs';
import {editorSchema,validateEdit} from '../cloudflare/editor/catalog.mjs';
import {serviceRoute} from '../cloudflare/services/purchases.mjs';
import {walletSchema,postMovement,walletState} from '../cloudflare/wallet/ledger.mjs';
const product={id:34,sku:'ASD035',name:'PUBG Mobile 57 + 3 Extra UC',type:'recharge',price:1,required_fields:['player_id']};
const source={id:34,sku:product.sku,name:product.name,field:'player_id'};
async function setup(){const DB=database();DB.sql.exec("CREATE TABLE zx_users(id TEXT PRIMARY KEY,status TEXT); INSERT INTO zx_users VALUES('buyer','active')");await editorSchema(DB);await DB.prepare('UPDATE zx_store_editor SET published=?').bind(JSON.stringify({'ra-game-34':{name:product.name,priceCents:3500,active:true,deliverySource:source}})).run();await walletSchema(DB);await postMovement(DB,{userId:'buyer',kind:'credit',amountCents:4132,currency:'MXN',source:'test',reference:'seed',requestKey:'seed',actor:'test'});return {DB,PUBLIC_COMMERCE_ENABLED:'true',RA_DELIVERY_ENABLED:'true',RA_CONTRACT_VERIFIED:'true',RA_READ_ENABLED:'true',RECARGAS_AMERICA_API_KEY:'fixture'};}
function upstream({changed=false,invalid=false}={}){let buys=0;const fetcher=async(url,opts={})=>{let data;if(url.endsWith('/products/catalog'))data=[{...product,...(changed?{sku:'OTHER'}:{})}];else if(url.endsWith('/catalog/validate'))data={supported:true,status:!invalid,account_name:'PUBG Player'};else if(url.endsWith('/wallet'))data={balance:20,currency:'USD'};else if(url.endsWith('/buy/catalog')){buys++;assert.deepEqual(JSON.parse(opts.body),{product_id:34,quantity:1,player_id:'123456789'});data={order_id:'RA-TEST',item:product.name,amount_charged:1,status:'COMPLETED'};}else throw Error('Unexpected '+url);return new Response(JSON.stringify({success:true,data}));};return {fetcher,buys:()=>buys};}
const user={id:'buyer',status:'active'},body={productId:'ra-game-34',quantity:1,playerId:'123456789',playerConfirmed:true,contactPhone:'+529511234567',method:'wallet',maxAmountCents:4132};
const call=(env,body,up,key=crypto.randomUUID(),path='checkout')=>serviceRoute(new Request('https://test/api/services/purchase/'+path,{method:'POST',headers:{'Idempotency-Key':key},body:JSON.stringify(body)}),env,new URL('https://test/api/services/purchase/'+path),user,(b,s=200)=>new Response(JSON.stringify(b),{status:s}),up.fetcher);
test('game catalogue requires explicit supported game and exact player-only contract',()=>{const p={...product,requiredFields:['player_id']};assert.equal(gameItem(p).category,'PUBG Mobile');assert.equal(gameItem({...p,type:'pin'}),null);assert.equal(gameItem({...p,requiredFields:['player_id','server_id']}),null);assert.equal(gameItem({...p,name:'Unknown Game'}),null);assert.equal(gameItem({...p,name:'Arena Breakout - 60 + 6 Bonds'}).platformPending,true);});
test('game checkout uses RA validation, exact published retail total and a single debit/delivery',async()=>{const env=await setup(),up=upstream(),key=crypto.randomUUID();const q=await call(env,body,up,undefined,'game/quote');assert.equal(q.status,200);assert.equal((await q.json()).amountCents,4132);assert.equal(up.buys(),0);for(let n=0;n<2;n++){const r=await call(env,body,up,key);assert.equal(r.status,200,await r.text());}assert.equal(up.buys(),1);assert.equal((await walletState(env.DB,'buyer')).availableCents,0);});
test('changed SKU, rejected ID, missing price and wrong retail total never charge or deliver',async()=>{for(const kind of ['changed','invalid','price','amount']){const env=await setup(),up=upstream({[kind]:true});if(kind==='price')env.DB.sql.exec("UPDATE zx_store_editor SET published='{}'");const r=await call(env,{...body,...(kind==='amount'?{maxAmountCents:3500}:{})},up);assert.equal(r.status,409);assert.equal(up.buys(),0);assert.equal((await walletState(env.DB,'buyer')).availableCents,4132);}});
test('editor accepts recoverable custom blocks and zero-price pending game products, not external URLs',()=>{const p={id:'custom:block:11111111-1111-4111-8111-111111111111',name:'Games',description:'',character:'',priceCents:0,active:true,image:''};assert.ok(validateEdit(p));assert.ok(validateEdit({...p,id:'ra-game-34'}));assert.equal(validateEdit({...p,image:'https://untrusted.test/x.png'}),null);});
