import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
function setup(initial='one'){
 class El extends EventTarget{textContent='';hidden=false;open=false;children=[];attrs={};click(){this.dispatchEvent(new Event('click'));}replaceChildren(){this.children=[];}append(...c){this.children.push(...c);}setAttribute(k,v){this.attrs[k]=v;}showModal(){this.open=true;}close(){this.open=false;}focus(){}}
 const e=Object.fromEntries(['zx-header-wallet','zx-header-wallet-value','open-account','zx-wallet-refresh','zx-wallet-island','zx-wallet-island-value','zx-wallet-island-status','zx-wallet-island-methods','zx-wallet-island-topup','zx-wallet-island-close','zx-wallet-island-refresh'].map(id=>[id,new El()]));let token=initial;const win=new EventTarget(),doc=new EventTarget(),calls=[];doc.getElementById=id=>e[id];doc.createElement=()=>new El();doc.hidden=false;
 vm.runInNewContext(readFileSync(new URL('../header-wallet.js',import.meta.url),'utf8'),{document:doc,window:win,Intl,AbortController,getZeroXSession:()=>({token}),zeroxAuthRequest:(path,opts)=>new Promise((resolve,reject)=>calls.push({path,opts,resolve,reject}))});return {e,win,doc,calls,change:t=>{token=t;win.dispatchEvent(new Event('zx-session-change'));}};
}
const settle=()=>new Promise(r=>setImmediate(r));
test('header shows own authoritative MXN balance and never fabricates zero on errors',async()=>{const s=setup();assert.equal(s.calls[0].path,'/api/wallet/me');s.calls[0].resolve({currency:'MXN',availableCents:1250});await settle();assert.match(s.e['zx-header-wallet-value'].textContent,/12.50.*MXN/);s.win.dispatchEvent(new Event('zx-account-ready'));s.calls[1].reject(Error('unavailable'));await settle();assert.equal(s.e['zx-header-wallet-value'].textContent,'Saldo no disponible');});
test('guest does not query wallet and changed account cannot display an old response',async()=>{const guest=setup(null);assert.equal(guest.calls.length,0);assert.equal(guest.e['zx-header-wallet-value'].textContent,'Inicia sesión');const s=setup();s.change('two');assert.equal(s.calls[0].opts.signal.aborted,true);s.calls[0].resolve({currency:'MXN',availableCents:9900});await settle();assert.equal(s.e['zx-header-wallet-value'].textContent,'Consultar saldo');});
test('page hiding clears the amount and rejects a late wallet response',async()=>{const s=setup();s.doc.hidden=true;s.doc.dispatchEvent(new Event('visibilitychange'));s.calls[0].resolve({currency:'MXN',availableCents:9900});await settle();assert.equal(s.e['zx-header-wallet-value'].textContent,'Consultar saldo');});
test('wallet island requires login, keeps recarga unavailable unless server enables pilot and clears on logout',async()=>{
 const guest=setup(null);let login=0;guest.e['open-account'].addEventListener('click',()=>login++);guest.e['zx-header-wallet'].click();assert.equal(login,1);assert.equal(guest.e['zx-wallet-island'].open,false);
 const s=setup();s.calls[0].resolve({currency:'MXN',availableCents:0,fundingPilotAvailable:false});await settle();assert.equal(s.e['zx-wallet-island-topup'].hidden,true);assert(s.e['zx-wallet-island-methods'].children.every(c=>!c.href));
 s.e['zx-header-wallet'].click();assert.equal(s.e['zx-wallet-island'].open,true);s.calls[1].resolve({currency:'MXN',availableCents:1000,fundingPilotAvailable:true});await settle();assert.equal(s.e['zx-wallet-island-topup'].hidden,false);assert.equal(s.e['zx-wallet-island-methods'].children[1].href,'wallet-payment.html?method=oxxo');s.change(null);assert.equal(s.e['zx-wallet-island'].open,false);assert.equal(s.e['zx-wallet-island-value'].textContent,'—');assert.equal(s.e['zx-wallet-island-topup'].hidden,true);
});
