import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
function setup(initial='one'){
 class El extends EventTarget{textContent='';click(){this.dispatchEvent(new Event('click'));}}
 const e=Object.fromEntries(['zx-header-wallet','zx-header-wallet-value','open-account','zx-wallet-refresh'].map(id=>[id,new El()]));let token=initial;const win=new EventTarget(),doc=new EventTarget(),calls=[];doc.getElementById=id=>e[id];doc.hidden=false;
 vm.runInNewContext(readFileSync(new URL('../header-wallet.js',import.meta.url),'utf8'),{document:doc,window:win,Intl,AbortController,getZeroXSession:()=>({token}),zeroxAuthRequest:(path,opts)=>new Promise((resolve,reject)=>calls.push({path,opts,resolve,reject}))});return {e,win,doc,calls,change:t=>{token=t;win.dispatchEvent(new Event('zx-session-change'));}};
}
const settle=()=>new Promise(r=>setImmediate(r));
test('header shows own authoritative MXN balance and never fabricates zero on errors',async()=>{const s=setup();assert.equal(s.calls[0].path,'/api/wallet/me');s.calls[0].resolve({currency:'MXN',availableCents:1250});await settle();assert.match(s.e['zx-header-wallet-value'].textContent,/12.50.*MXN/);s.win.dispatchEvent(new Event('zx-account-ready'));s.calls[1].reject(Error('unavailable'));await settle();assert.equal(s.e['zx-header-wallet-value'].textContent,'Saldo no disponible');});
test('guest does not query wallet and changed account cannot display an old response',async()=>{const guest=setup(null);assert.equal(guest.calls.length,0);assert.equal(guest.e['zx-header-wallet-value'].textContent,'Inicia sesión');const s=setup();s.change('two');assert.equal(s.calls[0].opts.signal.aborted,true);s.calls[0].resolve({currency:'MXN',availableCents:9900});await settle();assert.equal(s.e['zx-header-wallet-value'].textContent,'Consultar saldo');});
test('page hiding clears the amount and rejects a late wallet response',async()=>{const s=setup();s.doc.hidden=true;s.doc.dispatchEvent(new Event('visibilitychange'));s.calls[0].resolve({currency:'MXN',availableCents:9900});await settle();assert.equal(s.e['zx-header-wallet-value'].textContent,'Consultar saldo');});
