import test from 'node:test';
import assert from 'node:assert/strict';
import {database} from './helpers/d1.mjs';
import {diamondSchema} from '../cloudflare/diamonds/schema.mjs';
import {orderHistoryRoute} from '../cloudflare/order-history.mjs';
const user={id:'owner',status:'active'},reply=(body,status=200)=>new Response(JSON.stringify(body),{status});
async function setup(){const DB=database();await diamondSchema(DB);DB.sql.exec("CREATE TABLE zx_product_payments(order_id TEXT,method TEXT,state TEXT);CREATE TABLE zx_r_orders(id TEXT,user_id TEXT,product_name TEXT,uid TEXT,status TEXT,total INTEGER,created_at TEXT,completed_at TEXT)");const objects=new Map();return {DB,MEDIA:{put:async(k,b,m)=>objects.set(k,{body:b,...m}),get:async k=>objects.get(k),delete:async k=>objects.delete(k)},objects};}
async function add(env,id,owner='owner',state='COMPLETED',method='wallet'){await env.DB.prepare("INSERT INTO zx_diamond_orders(id,user_id,request_key,product_id,player_id,diamonds,sale_price_cents,provider_cost_cents,snapshot_json,state,paid_at,delivered,created_at,updated_at) VALUES(?,?,?,'product','123456789',220,5000,123,?,?,CURRENT_TIMESTAMP,220,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)").bind(id,owner,id,JSON.stringify({fulfillmentPlan:{provider:'secret supplier',packs:[{diamonds:110,quantity:2}],totalMicros:1338000,currency:'USD'}}),state).run();await env.DB.prepare('INSERT INTO zx_product_payments VALUES(?,?,?)').bind(id,method,'paid').run();}
async function call(env,path,u=user,body){const url=new URL('https://test/api/orders'+path);return orderHistoryRoute(new Request(url,{method:body?'POST':'GET',body:body?JSON.stringify(body):undefined}),env,url,u,reply);}
const reference={rating:5,comment:'Recibí mi recarga',public:false};
test('existing purchases are account-scoped, paginated, searchable, and sanitized',async()=>{const env=await setup();for(let i=0;i<28;i++)await add(env,'id-'+String(i).padStart(2,'0'));await add(env,'other','other');await add(env,'api-funds','owner','COMPLETED','ra-funds');const r=await call(env,'/me');assert.match(r.headers.get('Cache-Control'),/no-store/);const b=await r.json();assert.equal(b.items.length,25);assert.equal(b.hasMore,true);assert.equal((await (await call(env,'/me?page=1')).json()).items.length,4);assert.equal((await (await call(env,'/me?q=ZX-other')).json()).items.length,0);const funds=(await (await call(env,'/me?q=ZX-api-funds')).json()).items[0];assert.equal(funds.amountMicros,1338000);assert.equal(funds.currency,'USD');assert.equal(funds.method,'Saldo de cuenta');assert.doesNotMatch(JSON.stringify(b),/secret supplier|packs|provider|snapshot|request_key/);assert.equal((await call(env,'/me',null)).status,401);});
test('references require completed owned purchase and preserve rating/consent edits without duplicates',async()=>{const env=await setup();await add(env,'a');await add(env,'pending','owner','PROCESSING');assert.equal((await call(env,'/reference?order=diamond:a',{id:'other',status:'active'},reference)).status,404);assert.equal((await call(env,'/reference?order=diamond:pending',user,reference)).status,409);assert.equal((await call(env,'/reference?order=diamond:a',user,{...reference,rating:6})).status,400);assert.equal((await call(env,'/reference?order=diamond:a',user,reference)).status,200);assert.equal((await (await call(env,'/activity',null)).json()).references.length,0);await call(env,'/reference?order=diamond:a',user,{...reference,rating:1,public:true});const b=await (await call(env,'/activity',null)).json();assert.equal(b.references[0].rating,1);assert.equal(env.DB.sql.prepare('SELECT count(*) n FROM zx_order_references').get().n,1);await call(env,'/reference?order=diamond:a',user,reference);assert.equal((await (await call(env,'/activity',null)).json()).references.length,0);});
test('public activity only discloses real completed products with opaque deduplication keys',async()=>{const env=await setup();await add(env,'done');await add(env,'pending','owner','PROCESSING');await add(env,'broken');env.DB.sql.exec("UPDATE zx_diamond_orders SET delivered=0 WHERE id='broken'");const b=await (await call(env,'/activity',null)).json();assert.equal(b.items.length,1);assert.equal(b.items[0].product,'220 diamantes Free Fire');assert.equal(b.items[0].event.length,64);assert.doesNotMatch(JSON.stringify(b),/123456789|owner|done|supplier|folio|110|packs/);});
test('image upload signature checks and private owner-only retrieval',async()=>{const env=await setup();await add(env,'a');assert.equal((await call(env,'/reference?order=diamond:a',user,{...reference,image:'data:image/png;base64,PHN2Zz4='})).status,400);const image='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aZ1sAAAAASUVORK5CYII=';assert.equal((await call(env,'/reference?order=diamond:a',user,{...reference,image})).status,200);assert.equal(env.objects.size,1);assert.ok([...env.objects.keys()][0].startsWith('private-references/'));assert.equal((await call(env,'/reference/image?order=diamond:a',{id:'other',status:'active'})).status,404);const r=await call(env,'/reference/image?order=diamond:a');assert.equal(r.headers.get('content-type'),'image/png');assert.match(r.headers.get('cache-control'),/no-store/);await call(env,'/reference?order=diamond:a',user,{...reference,image});assert.equal(env.objects.size,1);const history=await (await call(env,'/me')).json();assert.equal(history.items[0].reference.hasImage,1);assert.doesNotMatch(JSON.stringify(history),/private-references/);});
test('empty databases and reseller purchases are supported without importing browser drafts',async()=>{const env={DB:database()};assert.deepEqual((await (await call(env,'/me')).json()).items,[]);const full=await setup();full.DB.sql.exec("INSERT INTO zx_r_orders VALUES('res','owner','Membresía','123','completed',15000,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)");const b=await (await call(full,'/me')).json();assert.equal(b.items[0].kind,'reseller');assert.equal(b.items[0].amountCents,15000);assert.equal((await call(full,'/reference?order=reseller:res',user,reference)).status,200);});
test('non-founder may read only their own confirmed receipt while purchase creation stays restricted',async()=>{const {purchaseRoute}=await import('../cloudflare/diamonds/purchases.mjs');const env=await setup(),id=crypto.randomUUID();await add(env,id);const url=new URL('https://test/api/diamonds/purchase/orders/'+id+'/receipt');assert.equal((await purchaseRoute(new Request(url),env,url,{...user,isFounder:false},reply)).status,409);assert.equal((await purchaseRoute(new Request(url),env,url,{id:'other',status:'active',isFounder:false},reply)).status,404);const post=new URL('https://test/api/diamonds/purchase/wallet');assert.equal((await purchaseRoute(new Request(post,{method:'POST'}),env,post,{...user,isFounder:false},reply)).status,403);});
test('purchase activity publishes handles and public avatars without exposing private profile data',async()=>{const env=await setup();env.DB.sql.exec("CREATE TABLE zx_users(id TEXT,username TEXT,status TEXT,email TEXT);CREATE TABLE zx_profile_style(user_id TEXT,is_public INTEGER,avatar TEXT);INSERT INTO zx_users VALUES('owner','ZeroPlayer','active','private@example.test');INSERT INTO zx_profile_style VALUES('owner',1,'data:image/png;base64,aGVsbG8=')");await add(env,'purchase');let data=await (await call(env,'/activity',null)).json();assert.equal(data.items[0].customer,'@ZeroPlayer');assert.equal(data.items[0].avatar,'data:image/png;base64,aGVsbG8=');assert.doesNotMatch(JSON.stringify(data),/private@example|123456789|user_id|owner|packs/);env.DB.sql.exec('UPDATE zx_profile_style SET is_public=0');data=await (await call(env,'/activity',null)).json();assert.equal(data.items[0].customer,'@ZeroPlayer');assert.equal(data.items[0].avatar,null);});

test('activity shows actual retail MXN and founder identity, never provider-fund test amounts',async()=>{
 const env=await setup(),founder='d8573fe7-331f-4248-a0ad-d99288c9a472';env.DB.sql.exec("CREATE TABLE zx_users(id TEXT,username TEXT,status TEXT);INSERT INTO zx_users VALUES('owner','ZeroX_Store','active')");await env.DB.prepare('INSERT INTO zx_users VALUES(?,?,?)').bind(founder,'Founder','active').run();await add(env,'retail');await add(env,'founder-sale',founder);await add(env,'provider-test',founder,'COMPLETED','ra-funds');const data=await(await call(env,'/activity',null)).json();assert.equal(data.items.length,2);assert.equal(data.items.find(i=>i.customer==='@ZeroX_Store').isFounder,false);assert.equal(data.items.find(i=>i.customer==='@Founder').isFounder,true);assert.ok(data.items.every(i=>i.amountCents===5000&&i.currency==='MXN'));assert.doesNotMatch(JSON.stringify(data),/1338000|d8573fe7|123456789/);
});
