import test from 'node:test';import assert from 'node:assert/strict';
import {database} from './helpers/d1.mjs';import {walletAdminRoute} from '../cloudflare/wallet/admin.mjs';import {walletSchema,walletState,postMovement} from '../cloudflare/wallet/ledger.mjs';import {fundingRoute} from '../cloudflare/payments/funding-routes.mjs';import {serviceRoute,reconcileServicePayment} from '../cloudflare/services/purchases.mjs';import {editorSchema} from '../cloudflare/editor/catalog.mjs';import {publicMethods} from '../cloudflare/payments/public-checkout.mjs';import {purchaseRoute} from '../cloudflare/diamonds/purchases.mjs';
const reply=(b,s=200)=>new Response(JSON.stringify(b),{status:s}),owner={id:'founder',status:'active',isFounder:true},customer={id:'customer',status:'active',isFounder:false};
async function setup(){const DB=database();DB.sql.exec("CREATE TABLE zx_users(id TEXT PRIMARY KEY,username TEXT,email TEXT,status TEXT,created_at TEXT);INSERT INTO zx_users VALUES('founder','Founder','founder@test','active',CURRENT_TIMESTAMP),('customer','Player','player@test','active',CURRENT_TIMESTAMP),('other','Other','other@test','active',CURRENT_TIMESTAMP)");await walletSchema(DB);return {DB,PUBLIC_COMMERCE_ENABLED:'true',MP_WALLET_PILOT_ENABLED:'true',MP_PRODUCTION_READ_ENABLED:'true',MP_ACCESS_TOKEN:'fixture',MP_COLLECTOR_ID_PRODUCTION:'123',MP_WEBHOOK_SECRET_PRODUCTION:'fixture',RA_DELIVERY_ENABLED:'true',RA_CONTRACT_VERIFIED:'true',RA_READ_ENABLED:'true',RECARGAS_AMERICA_API_KEY:'fixture',FF_INFO_API_KEY:'fixture'};}
const call=(handler,env,path,user,body,key=crypto.randomUUID(),fetcher)=>{const url=new URL('https://fixture'+path),r=new Request(url,{method:body?'POST':'GET',headers:{'Idempotency-Key':key},body:body?JSON.stringify(body):undefined});return handler(r,env,url,user,reply,fetcher);};
test('customer directory and immutable manual credits/debits are founder-only and reject duplicates/overdrafts',async()=>{const env=await setup();assert.equal((await call(walletAdminRoute,env,'/api/admin/customers',customer)).status,403);let data=await (await call(walletAdminRoute,env,'/api/admin/customers?q=player@test',owner)).json();assert.equal(data.users.length,1);assert.equal(data.users[0].id,'customer');const body={userId:'customer',action:'credit',source:'oxxo',amountCents:20000,reference:'TICKET-123',reason:'Comprobante de depósito verificado',confirmed:true},key=crypto.randomUUID();for(let i=0;i<2;i++)assert.equal((await call(walletAdminRoute,env,'/api/admin/customers/balance',owner,body,key)).status,200);assert.equal((await walletState(env.DB,'customer')).availableCents,20000);assert.equal((await call(walletAdminRoute,env,'/api/admin/customers/balance',owner,{...body,userId:'other'})).status,409);assert.equal((await call(walletAdminRoute,env,'/api/admin/customers/balance',owner,{...body,action:'debit',source:'adjustment',amountCents:25000,reference:'CORRECTION-1'})).status,409);assert.equal((await call(walletAdminRoute,env,'/api/admin/customers/balance',owner,{...body,action:'debit',source:'adjustment',amountCents:5000,reference:'CORRECTION-2'})).status,200);assert.equal((await walletState(env.DB,'customer')).availableCents,15000);assert.equal(env.DB.sql.prepare('SELECT COUNT(*) n FROM zx_wallet_ledger').get().n,2);});
test('public wallet checkout supports active non-founder accounts and excludes OXXO',async()=>{const env=await setup();let sent;const fetcher=async(u,o)=>{sent=JSON.parse(o.body);return new Response(JSON.stringify({id:'pref',collector_id:123,init_point:'https://www.mercadopago.com.mx/checkout/x'}));};assert.equal((await call(fundingRoute,env,'/api/payments/mercadopago/funding/checkout',customer,{amountCents:50000,method:'all'},crypto.randomUUID(),fetcher)).status,200);assert.ok(sent.payment_methods.excluded_payment_types.some(p=>p.id==='ticket'));assert.equal((await call(fundingRoute,env,'/api/payments/mercadopago/funding/checkout',customer,{amountCents:1000,method:'oxxo'})).status,400);assert.throws(()=>publicMethods('oxxo'));assert.equal((await walletState(env.DB,'customer')).availableCents,0);});
test('public access never grants customers use of founder provider funds',async()=>{const env=await setup();const r=await call(purchaseRoute,env,'/api/diamonds/purchase/supplier/buy',customer,{},undefined,async()=>{throw Error('NO_FETCH')});assert.equal(r.status,403);});
async function services(){const env=await setup();await editorSchema(env.DB);env.DB.sql.exec(`UPDATE zx_store_editor SET published='{"ff-ra-weekly":{"name":"Membresía semanal","priceCents":5000,"active":true}}';CREATE TABLE zx_market_settings(id INTEGER,settings_json TEXT);`);await env.DB.prepare('INSERT INTO zx_market_settings VALUES(1,?)').bind(JSON.stringify({mappings:[{productKey:'weekly',provider:'recargas-america',productId:'2',sku:'WEEKLY',name:'Weekly card',regions:['US']}]})).run();await postMovement(env.DB,{userId:'customer',kind:'credit',amountCents:20000,currency:'MXN',source:'fixture',reference:'initial',requestKey:'initial',actor:'fixture'});return env;}
const body={productId:'ff-ra-weekly',quantity:1,maxAmountCents:5000,playerId:'123456789',playerConfirmed:true,contactPhone:'+52 951 123 4567',method:'wallet'};
function upstream({lost=false}={}){const counts={buys:0,preferences:0};return {counts,fetcher:async(url,options={})=>{let b;if(url.includes('freefirecommunity'))b={basicInfo:{accountId:'123456789',nickname:'Player',region:'US'}};else if(url.endsWith('/products/catalog'))b={success:true,data:[{id:2,sku:'WEEKLY',name:'Weekly card',price:1,type:'recharge',required_fields:['player_id']}]};else if(url.endsWith('/wallet'))b={success:true,data:{balance:100,currency:'USD'}};else if(url.endsWith('/catalog/validate'))b={success:true,data:{supported:true,status:true}};else if(url.endsWith('/buy/catalog')){counts.buys++;assert.deepEqual(JSON.parse(options.body),{product_id:2,quantity:1,player_id:'123456789'});if(lost)throw Error('TIMEOUT');b={success:true,data:{order_id:'RA-123',item:'Weekly card',status:'COMPLETED',amount_charged:1}};}else if(url.endsWith('/users/me'))b={id:123,site_id:'MLM'};else if(url.endsWith('/checkout/preferences')){counts.preferences++;b={id:'pref',collector_id:123,init_point:'https://www.mercadopago.com.mx/checkout/service'};}else throw Error('UNEXPECTED '+url);return new Response(JSON.stringify(b));}};}
test('service wallet purchase uses published price, saves private contact and delivers once on retries',async()=>{const env=await services(),u=upstream(),key=crypto.randomUUID();const callBuy=()=>call(serviceRoute,env,'/api/services/purchase/checkout',customer,body,key,u.fetcher);const r=await callBuy();assert.equal(r.status,200);const {orderId}=await r.json();await callBuy();assert.equal(u.counts.buys,1);assert.equal((await walletState(env.DB,'customer')).availableCents,15000);assert.equal(env.DB.sql.prepare('SELECT phone FROM zx_purchase_contacts').get().phone,body.contactPhone);const receipt=await (await call(serviceRoute,env,'/api/services/purchase/orders/'+orderId+'/receipt',customer)).json();assert.equal(receipt.receipt.amountCents,5000);assert.doesNotMatch(JSON.stringify(receipt),/RA-123|WEEKLY|provider|contactPhone/);assert.equal((await call(serviceRoute,env,'/api/services/purchase/orders/'+orderId,{...customer,id:'other'})).status,404);});
test('service price change, missing mapping or invalid contact cannot charge or deliver',async()=>{for(const kind of ['price','mapping','contact']){const env=await services(),u=upstream();if(kind==='mapping')env.DB.sql.exec('DELETE FROM zx_market_settings');const r=await call(serviceRoute,env,'/api/services/purchase/checkout',customer,{...body,...(kind==='price'?{maxAmountCents:4000}:kind==='contact'?{contactPhone:''}:{})},crypto.randomUUID(),u.fetcher);assert.ok(r.status>=400);assert.equal(u.counts.buys,0);assert.equal((await walletState(env.DB,'customer')).availableCents,20000);}});
test('lost service delivery remains review and never resubmits after a repeated checkout',async()=>{const env=await services(),u=upstream({lost:true}),key=crypto.randomUUID();for(let i=0;i<2;i++)await call(serviceRoute,env,'/api/services/purchase/checkout',customer,body,key,u.fetcher);assert.equal(u.counts.buys,1);assert.equal(env.DB.sql.prepare('SELECT state FROM zx_service_orders').get().state,'REQUIRES_REVIEW');});
test('service Mercado Pago checkout never delivers until server payment evidence matches; repeated approval delivers once',async()=>{const env=await services(),u=upstream();const result=await (await call(serviceRoute,env,'/api/services/purchase/checkout',customer,{...body,method:'all'},crypto.randomUUID(),u.fetcher)).json();assert.equal(u.counts.preferences,1);assert.equal(u.counts.buys,0);const payment={id:123456,live_mode:true,external_reference:result.orderId,collector_id:123,currency_id:'MXN',transaction_amount:50,status:'approved'};await assert.rejects(reconcileServicePayment(env,{...payment,transaction_amount:1},u.fetcher));await reconcileServicePayment(env,payment,u.fetcher);await reconcileServicePayment(env,payment,u.fetcher);assert.equal(u.counts.buys,1);assert.equal((await walletState(env.DB,'customer')).availableCents,20000);});

import {couponSchema} from '../cloudflare/coupons.mjs';
test('service discounts debit net total once and MP requires net payment evidence',async()=>{
 for(const method of ['wallet','all']){
  const env=await services(),u=upstream(),key=crypto.randomUUID();await couponSchema(env.DB);env.DB.sql.exec("INSERT INTO zx_discount_codes VALUES('ZX-ABCDEF123456',10,'2099-01-01T00:00:00.000Z',1,'founder','fixture',CURRENT_TIMESTAMP)");
  const discounted={...body,method,couponCode:'ZX-ABCDEF123456',maxAmountCents:4500};
  const r=await call(serviceRoute,env,'/api/services/purchase/checkout',customer,discounted,key,u.fetcher),d=await r.json();assert.equal(r.status,200,JSON.stringify(d));
  const row=env.DB.sql.prepare('SELECT * FROM zx_service_orders').get();assert.equal(row.amount_cents,4500);assert.equal(JSON.parse(row.plan_json).price,1);
  env.DB.sql.exec('UPDATE zx_discount_codes SET active=0');await call(serviceRoute,env,'/api/services/purchase/checkout',customer,discounted,key,u.fetcher);
  assert.equal((await call(serviceRoute,env,'/api/services/purchase/checkout',customer,{...discounted,couponCode:''},key,u.fetcher)).status,409);
  if(method==='wallet'){assert.equal((await walletState(env.DB,'customer')).availableCents,15500);assert.equal(u.counts.buys,1);}else{const evidence={id:789,live_mode:true,external_reference:d.orderId,collector_id:123,currency_id:'MXN',transaction_amount:45,status:'approved'};await assert.rejects(reconcileServicePayment(env,{...evidence,transaction_amount:50},u.fetcher));await reconcileServicePayment(env,evidence,u.fetcher);assert.equal(u.counts.buys,1);}
 }
});
