import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const app=readFileSync(new URL('../app.js',import.meta.url),'utf8');const start=app.indexOf('    pay.onclick=async()=>{');const handler=app.slice(start,app.indexOf('\n    };',start)+7);
function checkout(method,accepted){const calls=[],storage=[],watched=[];const element=()=>({disabled:false,hidden:true,textContent:'',append(){}});const pay=element(),notes=element();const ctx={phone:{value:"+52 951 123 4567"},service:false,apiPath:"/api/diamonds/purchase",pay,paymentBusy:false,createdOrder:'',realAvailable:true,confirmedUid:'123456789',uidInput:{value:'123456789'},requestVersion:0,getZeroXSession:()=>({token:'owner'}),zeroxUser:{id:'owner'},product:{id:'ff-110',name:'110 diamantes',price:18},sessionStorage:{getItem:()=>null,setItem:(...x)=>storage.push(x),removeItem(){}},methodSelect:{value:method},attempt:'',supplierQuote:null,purchaseStarted:false,intent:{querySelectorAll:()=>[]},dialog:{open:true,isConnected:true,querySelectorAll:()=>[]},note:notes,payLink:element(),payments:element(),money:n=>n+' MXN',crypto:{randomUUID:()=> '12345678-1234-1234-1234-123456789abc'},Event,URL,document:{hidden:false,createElement:element},window:{dispatchEvent(){},ZXPurchaseFlow:{confirmBalance:async()=>accepted,watchOrder:id=>watched.push(id)}},zeroxAuthRequest:async(path,options)=>{calls.push({path,options});return path.endsWith('/quote')?{totalMicros:669000,playerId:'123456789',currency:'USD'}:{orderId:'12345678-1234-1234-1234-123456789abc',delivery:{state:'COMPLETED',delivered:110}};}};vm.runInNewContext(handler,ctx);return {ctx,calls,storage,watched};}
for(const method of ['wallet','ra']){
 test(method+': cancel never charges and accept submits one purchase before automatic tracking',async()=>{const no=checkout(method,false);await no.ctx.pay.onclick();assert.equal(no.calls.filter(x=>!x.path.endsWith('/quote')).length,0);assert.equal(no.storage.length,0);assert.equal(no.ctx.pay.disabled,false);const yes=checkout(method,true);await yes.ctx.pay.onclick();await yes.ctx.pay.onclick();assert.equal(yes.calls.filter(x=>!x.path.endsWith('/quote')).length,1);assert.equal(yes.watched.length,1);});
}
const tick=()=>new Promise(r=>setImmediate(r));
function flow(){const win=new EventTarget(),doc=new EventTarget(),timers=[],calls=[];let owner='owner';doc.hidden=false;const context={window:win,document:doc,localStorage:{getItem:()=>JSON.stringify({token:owner})},setTimeout:f=>{timers.push(f);return timers.length;},clearTimeout(){},Promise};vm.runInNewContext(readFileSync(new URL('../purchase-flow.js',import.meta.url),'utf8'),context);return {ui:win.ZXPurchaseFlow,doc,win,timers,calls,setOwner:v=>owner=v};}
test('automatic tracking opens only after COMPLETED and performs read requests only',async()=>{const s=flow(),shown=[];let state='PROCESSING';s.ui.watchOrder('12345678-1234-1234-1234-123456789abc',{request:async path=>{s.calls.push(path);return {order:{state}};},onComplete:id=>shown.push(id)});await tick();assert.equal(shown.length,0);state='COMPLETED';await s.timers[0]();assert.equal(shown.length,1);assert.equal(s.calls.length,2);assert.ok(s.calls.every(p=>p.startsWith('/orders/')));});
test('late completion after logout cannot open private receipt',async()=>{const s=flow(),shown=[];let resolve;s.ui.watchOrder('12345678-1234-1234-1234-123456789abc',{request:()=>new Promise(r=>resolve=r),onComplete:id=>shown.push(id)});s.setOwner('other');s.win.dispatchEvent(new Event('zx-session-change'));resolve({order:{state:'COMPLETED'}});await tick();assert.equal(shown.length,0);});
