import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import {database} from './helpers/d1.mjs';import worker from '../cloudflare/worker.js';
test('real routes identify current session, revoke it, and reject the old token',async()=>{const DB=database(),env={DB},token='test-session-token',id=crypto.randomUUID();const call=(path,opts={})=>worker.fetch(new Request('https://test'+path,{...opts,headers:{Authorization:'Bearer '+token}}),env);await call('/api/auth/features');DB.sql.prepare('INSERT INTO zx_users(id,email,username,password_hash) VALUES(?,?,?,?)').run('user','test@example.invalid','test-user','unused');DB.sql.prepare('INSERT INTO zx_sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,?)').run(id,'user',createHash('sha256').update(token).digest('base64'),'2099-01-01T00:00:00.000Z');let r=await call('/api/security/sessions');assert.equal(r.status,200);assert.equal(r.headers.get('Cache-Control'),'no-store');assert.equal((await r.json()).sessions[0].current,true);r=await call('/api/security/sessions/revoke',{method:'POST',body:JSON.stringify({sessionId:id})});assert.equal((await r.json()).signOut,true);assert.equal((await call('/api/auth/me')).status,401);assert.equal((await call('/api/security/events')).status,401);assert.equal(DB.sql.prepare('SELECT COUNT(*) n FROM zx_security_events WHERE user_id=?').get('user').n,1);});
test('disabled account token cannot authenticate',async()=>{const DB=database(),env={DB};await worker.fetch(new Request('https://test/api/auth/features'),env);DB.sql.prepare('INSERT INTO zx_users(id,email,username,password_hash,status) VALUES(?,?,?,?,?)').run('user','disabled@example.invalid','disabled','unused','disabled');DB.sql.prepare('INSERT INTO zx_sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,?)').run(crypto.randomUUID(),'user',createHash('sha256').update('disabled').digest('base64'),'2099-01-01T00:00:00.000Z');assert.equal((await worker.fetch(new Request('https://test/api/auth/me',{headers:{Authorization:'Bearer disabled'}}),env)).status,401);});
test('wallet/provider worker routes remain authenticated, disabled, and read-only',async()=>{
 const DB=database(),env={DB},token='wallet-route-fixture';const call=(path,options={})=>worker.fetch(new Request('https://test'+path,{...options,headers:{Authorization:'Bearer '+token}}),env);
 await call('/api/auth/features');DB.sql.prepare('INSERT INTO zx_users(id,email,username,password_hash) VALUES(?,?,?,?)').run('wallet-user','wallet@example.invalid','wallet-user','unused');DB.sql.prepare('INSERT INTO zx_sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,?)').run(crypto.randomUUID(),'wallet-user',createHash('sha256').update(token).digest('base64'),'2099-01-01T00:00:00.000Z');
 assert.equal((await worker.fetch(new Request('https://test/api/wallet/me'),env)).status,401);
 const r=await call('/api/wallet/me');assert.equal(r.status,503);assert.equal(r.headers.get('Cache-Control'),'no-store');assert.equal((await r.json()).error,'WALLET_NOT_ACTIVE');
 assert.equal(DB.sql.prepare("SELECT COUNT(*) n FROM sqlite_master WHERE name='zx_wallet_ledger'").get().n,0);
 assert.equal((await call('/api/wallet/me',{method:'POST',body:'{}'})).status,405);
 assert.equal((await call('/api/admin/providers/recargas-america/status')).status,403);
});
