import {getProduct} from '../diamonds/catalog.mjs';
import {deliveryQuote,submitDelivery,lookupDelivery} from './delivery.mjs';
import {publishedCatalog} from '../editor/catalog.mjs';
import {readRecargasAmerica,validateRecargasAccount} from '../providers/recargas-america.mjs';
import {verifiedPlayer} from '../diamonds/purchases.mjs';
import {productionToken,productionEvidence,productionAccount} from '../payments/mercadopago-production.mjs';
import {publicMethods,validContact,saveContact} from '../payments/public-checkout.mjs';
import {walletSchema,postMovement} from '../wallet/ledger.mjs';
const ROOT='/api/services/purchase';
export const serviceProducts={'ff-ra-weekly-basic':{key:'weekly-basic',name:'Membresía semanal básica'},'ff-ra-weekly':{key:'weekly',name:'Membresía semanal'},'ff-ra-monthly':{key:'monthly',name:'Membresía mensual'},'ff-ra-booyah-premium':{key:'booyah-premium',name:'Pase Booyah Premium'},'ff-booyah-76828':{key:'booyah-normal',name:'Pase Booyah',priceCents:3500},'ff-frag-17729':{key:'fragment',name:'Fragmentos universales',priceCents:100,min:40,max:1400},'ff-cajas-8816':{key:'fragment-box',name:'Cajas de fragmentos',priceCents:350,min:7,max:100}};
export async function serviceSchema(db){await walletSchema(db);await db.prepare(`CREATE TABLE IF NOT EXISTS zx_service_orders(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,request_key TEXT NOT NULL,product_id TEXT NOT NULL,product_name TEXT NOT NULL,player_id TEXT NOT NULL,quantity INTEGER NOT NULL,amount_cents INTEGER NOT NULL,method TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'PENDING_PAYMENT',payment_state TEXT NOT NULL DEFAULT 'creating',collector_id TEXT,checkout_url TEXT,payment_id TEXT UNIQUE,plan_json TEXT NOT NULL,provider_reference TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(user_id,request_key))`).run();}
export async function quote(env,id,uid,quantity,fetcher,preferred=null){
 const diamond=getProduct(id),base=serviceProducts[id]||(diamond?{key:'diamonds:'+diamond.diamonds,name:diamond.diamonds+' diamantes Free Fire',priceCents:diamond.salePriceCents}:null);if(!base)throw Error('PRODUCT_NOT_CONNECTED');const published=await publishedCatalog(env.DB),p=published[id],price=p?.priceCents??base.priceCents;
 if(p?.active===false||!Number.isSafeInteger(price)||price<1)throw Error('PRODUCT_PRICE_REQUIRED');
 if(!Number.isSafeInteger(quantity)||quantity<(base.min||1)||quantity>(base.max||1))throw Error('INVALID_QUANTITY');
 const amount=price*quantity;if(amount>1000000)throw Error('AMOUNT_LIMIT');
 const region=await verifiedPlayer(env,uid,fetcher),plan=await deliveryQuote(env,base.key,uid,quantity,region,fetcher,preferred);
 return {productName:p?.name||base.name,amountCents:amount,plan};
}
async function deliver(env,id,fetcher){
 const o=await env.DB.prepare('SELECT * FROM zx_service_orders WHERE id=?').bind(id).first();if(!o||o.payment_state!=='paid'||o.state!=='PAID')return;
 const plan=JSON.parse(o.plan_json);
 const claim=await env.DB.prepare("UPDATE zx_service_orders SET state='DELIVERING',updated_at=CURRENT_TIMESTAMP WHERE id=? AND state='PAID' AND payment_state='paid'").bind(id).run();if(!claim.meta.changes)return;
 let result;try{result=await submitDelivery(env,plan,o.player_id,id,fetcher);}catch{result={state:'REQUIRES_REVIEW'};}
 await env.DB.prepare("UPDATE zx_service_orders SET state=?,provider_reference=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND state='DELIVERING'").bind(result.state,result.reference||null,id).run();
}
export async function reconcileServicePayment(env,payment,fetcher=fetch){const t=await env.DB.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='zx_service_orders'").first();if(!t)return false;const row=await env.DB.prepare('SELECT * FROM zx_service_orders WHERE id=?').bind(String(payment.external_reference||'')).first();if(!row)return false;if(['wallet','ra','sf'].includes(row.method)||!productionEvidence(payment,row))throw Error('SERVICE_PAYMENT_EVIDENCE_REJECTED');if(row.payment_id&&row.payment_id!==String(payment.id))throw Error('SERVICE_PAYMENT_CONFLICT');if(['refunded','charged_back','in_mediation'].includes(payment.status)||Number(payment.transaction_amount_refunded||0)>0){await env.DB.prepare("UPDATE zx_service_orders SET payment_state='review_required' WHERE id=?").bind(row.id).run();return true;}if(payment.status!=='approved'||row.payment_state==='review_required')return true;await env.DB.prepare("UPDATE zx_service_orders SET payment_id=?,payment_state='paid',state=CASE WHEN state='PENDING_PAYMENT' THEN 'PAID' ELSE state END WHERE id=? AND (payment_id IS NULL OR payment_id=?)").bind(String(payment.id),row.id,String(payment.id)).run();await deliver(env,row.id,fetcher);return true;}
function projection(o){return {id:o.id,state:o.state==='DELIVERING'?'PROCESSING':o.state,product:o.product_name,quantity:o.quantity,paymentState:o.payment_state,paymentMethod:o.method,checkout_url:o.checkout_url};}
export async function serviceRoute(request,env,url,user,json,fetcher=fetch){const reply=(b,s=200)=>{const r=json(b,s);r.headers?.set('Cache-Control','private, no-store');return r;};if(!user||user.status!=='active')return reply({ok:false,error:'LOGIN_REQUIRED'},401);if(env.PUBLIC_COMMERCE_ENABLED!=='true')return reply({ok:false,error:'COMMERCE_DISABLED'},503);await serviceSchema(env.DB);
 try{if(url.pathname===ROOT+'/status'&&request.method==='GET'){const walletEnabled=env.RA_DELIVERY_ENABLED==='true'&&env.RA_CONTRACT_VERIFIED==='true'||env.SIXOFIRE_DELIVERY_ENABLED==='true';const enabled=walletEnabled&&!!productionToken(env)&&!!env.MP_WEBHOOK_SECRET_PRODUCTION;return reply({ok:true,enabled,walletEnabled,supplierEnabled:user.isFounder===true&&walletEnabled});}const match=url.pathname.match(/^\/api\/services\/purchase\/orders\/([a-f0-9-]{36})(\/receipt)?$/);if(match&&request.method==='GET'){const o=await env.DB.prepare('SELECT * FROM zx_service_orders WHERE id=? AND user_id=?').bind(match[1],user.id).first();if(!o)return reply({ok:false,error:'NOT_FOUND'},404);if(o.state==='PROCESSING'&&o.provider_reference){try{const result=await lookupDelivery(env,JSON.parse(o.plan_json),o.player_id,o.provider_reference,fetcher);await env.DB.prepare("UPDATE zx_service_orders SET state=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND state='PROCESSING'").bind(result.state,o.id).run();o.state=result.state;}catch{}}if(match[2]){if(o.state!=='COMPLETED'||o.payment_state!=='paid'||!o.provider_reference)return reply({ok:false,error:'RECEIPT_NOT_READY'},409);return reply({ok:true,receipt:{orderId:o.id,number:'ZX-'+o.id,product:o.product_name+(o.quantity>1?' × '+o.quantity:''),playerId:o.player_id,confirmedAt:o.updated_at,method:['ra','sf'].includes(o.method)?'balance':o.method,...(['ra','sf'].includes(o.method)?{amountMicros:Math.ceil(JSON.parse(o.plan_json).price*o.quantity*1e6),currency:'USD',amountLabel:'Saldo autorizado'}:{amountCents:o.amount_cents,currency:'MXN',amountLabel:'Total pagado'}),notice:'Comprobante Zero’X Store. No es una factura fiscal.'}});}return reply({ok:true,order:projection(o)});}
 if(request.method==='POST'&&url.pathname===ROOT+'/supplier/quote'){if(!user.isFounder)return reply({ok:false,error:'FORBIDDEN'},403);const b=await request.json();if(!['ra','sf'].includes(b.method)||!/^\d{5,15}$/.test(b.playerId||'')||b.playerConfirmed!==true)return reply({ok:false,error:'INVALID_REQUEST'},400);const q=await quote(env,b.productId,b.playerId,b.quantity,fetcher,b.method==='ra'?'recargas-america':'sixofire');return reply({ok:true,playerId:b.playerId,currency:'USD',totalMicros:Math.ceil(q.plan.price*q.plan.quantity*1e6)});}
 if(request.method!=='POST'||url.pathname!==ROOT+'/checkout')return reply({ok:false,error:'NOT_FOUND'},404);
 const b=await request.json(),key=request.headers.get('Idempotency-Key');if(!/^[a-f0-9-]{36}$/.test(key||'')||!/^\d{5,15}$/.test(b.playerId||'')||b.playerConfirmed!==true||!validContact(b.contactPhone)||!['wallet','all','card','spei','ra','sf'].includes(b.method))return reply({ok:false,error:'INVALID_REQUEST'},400);
 if(['ra','sf'].includes(b.method)&&!user.isFounder)return reply({ok:false,error:'FORBIDDEN'},403);
 if(!(env.RA_DELIVERY_ENABLED==='true'&&env.RA_CONTRACT_VERIFIED==='true')&&env.SIXOFIRE_DELIVERY_ENABLED!=='true')return reply({ok:false,error:'DELIVERY_DISABLED'},503);
 let o=await env.DB.prepare('SELECT * FROM zx_service_orders WHERE user_id=? AND request_key=?').bind(user.id,key).first();if(o){if(o.product_id!==b.productId||o.player_id!==b.playerId||o.method!==b.method||o.quantity!==b.quantity)return reply({ok:false,error:'IDEMPOTENCY_CONFLICT'},409);if(o.method==='wallet'&&o.payment_state==='creating'){const debit=await env.DB.prepare("SELECT id FROM zx_wallet_ledger WHERE user_id=? AND source='service-wallet' AND reference=? AND amount_cents=?").bind(user.id,o.id,-o.amount_cents).first();if(debit){await env.DB.prepare("UPDATE zx_service_orders SET state='PAID',payment_state='paid' WHERE id=? AND payment_state='creating'").bind(o.id).run();await deliver(env,o.id,fetcher);}}return reply({ok:true,orderId:o.id,checkoutUrl:o.checkout_url,order:projection(o)});}
 const q=await quote(env,b.productId,b.playerId,b.quantity,fetcher,b.method==='ra'?'recargas-america':b.method==='sf'?'sixofire':null);if(['ra','sf'].includes(b.method)&&(!b.supplierConfirmed||!Number.isSafeInteger(b.maxTotalMicros)||b.maxTotalMicros<Math.ceil(q.plan.price*q.plan.quantity*1e6)))throw Error('PRODUCT_PRICE_CHANGED');if(!Number.isSafeInteger(b.maxAmountCents)||q.amountCents!==b.maxAmountCents)throw Error('PRODUCT_PRICE_CHANGED');if(!['wallet','ra','sf'].includes(b.method)){if(!productionToken(env)||!env.MP_WEBHOOK_SECRET_PRODUCTION)throw Error('PAYMENT_CONFIG_MISSING');await productionAccount(env,fetcher);}
 const id=crypto.randomUUID();await env.DB.prepare('INSERT INTO zx_service_orders(id,user_id,request_key,product_id,product_name,player_id,quantity,amount_cents,method,collector_id,plan_json) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT DO NOTHING').bind(id,user.id,key,b.productId,q.productName,b.playerId,b.quantity,q.amountCents,b.method,String(env.MP_COLLECTOR_ID_PRODUCTION||''),JSON.stringify(q.plan)).run();o=await env.DB.prepare('SELECT * FROM zx_service_orders WHERE user_id=? AND request_key=?').bind(user.id,key).first();if(o.id!==id)return reply({ok:false,error:'ORDER_ALREADY_CREATED'},409);await saveContact(env.DB,id,user.id,b.contactPhone);
 if(['wallet','ra','sf'].includes(b.method)){if(b.method==='wallet')await postMovement(env.DB,{userId:user.id,kind:'purchase',amountCents:o.amount_cents,currency:'MXN',source:'service-wallet',reference:id,requestKey:'service:'+id,orderId:id,actor:user.id});await env.DB.prepare("UPDATE zx_service_orders SET state='PAID',payment_state='paid' WHERE id=?").bind(id).run();try{await deliver(env,id,fetcher);}catch{}return reply({ok:true,orderId:id});}
 const back='https://zerox-store.pages.dev/product-payment.html?kind=service&order='+id;try{const r=await fetcher('https://api.mercadopago.com/checkout/preferences',{method:'POST',redirect:'manual',headers:{Authorization:'Bearer '+productionToken(env),'Content-Type':'application/json'},signal:AbortSignal.timeout(12000),body:JSON.stringify({items:[{id:o.product_id,title:o.product_name,quantity:1,currency_id:'MXN',unit_price:o.amount_cents/100}],external_reference:id,payment_methods:publicMethods(b.method),notification_url:'https://zerox-sixofire-api.westdark161208.workers.dev/api/payments/mercadopago/funding/webhook',back_urls:{success:back,pending:back,failure:back}})}),pref=await r.json(),link=new URL(pref.init_point);if(!r.ok||link.protocol!=='https:'||!['www.mercadopago.com.mx','www.mercadopago.com'].includes(link.hostname)||link.username||link.password||String(pref.collector_id)!==o.collector_id)throw Error('CHECKOUT_FAILED');await env.DB.prepare("UPDATE zx_service_orders SET checkout_url=?,payment_state='ready' WHERE id=?").bind(link.href,id).run();return reply({ok:true,orderId:id,checkoutUrl:link.href});}catch{return reply({ok:false,error:'CHECKOUT_RECONCILIATION_REQUIRED',orderId:id},503);}
 }catch(e){return reply({ok:false,error:['PRODUCT_PRICE_CHANGED','PRODUCT_NOT_CONNECTED','PRODUCT_PRICE_REQUIRED','INVALID_QUANTITY','AMOUNT_LIMIT','PRODUCT_DELIVERY_MAPPING_REQUIRED','PRODUCT_NOT_AVAILABLE','DELIVERY_FUNDS_UNAVAILABLE','DELIVERY_CONNECTION_FAILED','PLAYER_REJECTED','PAYMENT_CONFIG_MISSING','WALLET_MOVEMENT_REJECTED'].includes(e.message)?e.message:'SERVICE_UNAVAILABLE',...(user.isFounder&&e.deliveryIssues?{deliveryIssues:e.deliveryIssues}: {})},409);}}
