import '../../retail-pricing.js';
import {retailDiscount,assertCouponRetry} from '../coupons.mjs';
import {publishedCatalog} from '../editor/catalog.mjs';
import {verifiedPlayer} from '../diamonds/purchases.mjs';
import {resolvedRaEnvironment} from '../providers/ra-associations.mjs';
import {raAmountPreflight} from '../diamonds/recargas-america.mjs';
import {deliveryQuote,submitDelivery,lookupDelivery} from '../services/delivery.mjs';
import {walletSchema,postMovement} from '../wallet/ledger.mjs';
import {productionToken,productionAccount,productionEvidence} from '../payments/mercadopago-production.mjs';
import {publicMethods,validContact,saveContact} from '../payments/public-checkout.mjs';
const ROOT='/api/promotions',keys=new Set(['wallet','all','card','spei','ra','sf']);
// Only explicit units are executable. "Cajas" alone does not identify Evo versus fragments.
export function parsePromotion(text){const parts=String(text).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/(\d),(?=\d{3}(?:\D|$))/g,'$1').replace(/💎/g,' diamantes').trim().split(/\s*\+\s*/);if(parts.length<1||parts.length>10)throw Error('PROMOTION_DESCRIPTION_REQUIRED');const lines=[];for(const part of parts){const m=part.match(/^(\d{1,6})\s+(diamantes|fragmentos?|cajas? (?:de )?(?:fragmentos|tokens)|cajas? evo|pases?(?: booyah)?|membresias? semanales? basicas?|membresias? semanales?|membresias? mensuales?)$/);if(!m||Number(m[1])<1)throw Error('PROMOTION_DESCRIPTION_REQUIRED');const quantity=Number(m[1]),label=m[2],kind=label==='diamantes'?'diamonds':/^pase/.test(label)?'booyah-normal':/evo/.test(label)?'evo-box':/^caja/.test(label)?'fragment-box':/^fragmento/.test(label)?'fragment':/basica/.test(label)?'weekly-basic':/mensual/.test(label)?'monthly':'weekly';if(quantity>(kind==='diamonds'?100930:kind==='fragment'?1400:kind==='fragment-box'||kind==='evo-box'?100:10))throw Error('PROMOTION_QUANTITY_LIMIT');if(['booyah-normal','weekly-basic','weekly','monthly'].includes(kind)){for(let n=0;n<quantity;n++)lines.push({kind,quantity:1,label:`${label} · cuenta ${n+1} de ${quantity}`});}else lines.push({kind,quantity,label:quantity+' '+label});}if(lines.length>20)throw Error('PROMOTION_QUANTITY_LIMIT');return lines;}
async function schema(db){await walletSchema(db);await db.prepare('CREATE TABLE IF NOT EXISTS zx_bundle_discounts(order_id TEXT PRIMARY KEY,pricing_json TEXT NOT NULL)').run();for(const sql of ["CREATE TABLE IF NOT EXISTS zx_bundle_orders(id TEXT PRIMARY KEY,user_id TEXT NOT NULL,request_key TEXT NOT NULL,ad_id TEXT NOT NULL,product_name TEXT NOT NULL,amount_cents INTEGER NOT NULL,funds_micros INTEGER NOT NULL DEFAULT 0,method TEXT NOT NULL,collector_id TEXT NOT NULL,payment_id TEXT UNIQUE,payment_state TEXT NOT NULL DEFAULT 'creating',state TEXT NOT NULL DEFAULT 'PENDING_PAYMENT',checkout_url TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(user_id,request_key))","CREATE TABLE IF NOT EXISTS zx_bundle_lines(order_id TEXT NOT NULL,sequence INTEGER NOT NULL,label TEXT NOT NULL,kind TEXT NOT NULL,quantity INTEGER NOT NULL,max_micros INTEGER NOT NULL,player_id TEXT,state TEXT NOT NULL DEFAULT 'WAITING_ID',PRIMARY KEY(order_id,sequence))","CREATE TABLE IF NOT EXISTS zx_bundle_ops(order_id TEXT NOT NULL,line INTEGER NOT NULL,sequence INTEGER NOT NULL,plan_json TEXT NOT NULL,player_id TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'PENDING',reference TEXT,PRIMARY KEY(order_id,line,sequence))"])await db.prepare(sql).run();}
async function promotion(env,id){const ad=await env.DB.prepare("SELECT * FROM zx_ads WHERE id=? AND active=1 AND (starts IS NULL OR starts<=?) AND (ends IS NULL OR ends>?)").bind(id,new Date().toISOString(),new Date().toISOString()).first();if(!ad)throw Error('PROMOTION_UNAVAILABLE');const p=(await publishedCatalog(env.DB))['entity:ads:'+id];if(!p||p.active===false||!Number.isSafeInteger(p.priceCents)||p.priceCents<100||p.priceCents>1000000)throw Error('PROMOTION_PRICE_REQUIRED');let lines;try{lines=parsePromotion(p.description||ad.description);}catch{lines=parsePromotion(p.character||ad.kicker);}return {name:p.name||ad.title,amountCents:globalThis.ZXRetailPricing.priceCents(p.priceCents),lines};}
async function plans(env,line,uid,fetcher,preferred=null){const region=await verifiedPlayer(env,uid,fetcher);if(line.kind!=='diamonds')return [await deliveryQuote(env,line.kind,uid,line.quantity,region,fetcher,preferred)];if(preferred==='sixofire')return [await deliveryQuote(env,'diamonds:'+line.quantity,uid,1,region,fetcher,preferred)];const ra=await resolvedRaEnvironment(env,fetcher),plan=await raAmountPreflight(ra,line.quantity,region,uid,fetcher);return plan.packs.flatMap(p=>Array.from({length:p.quantity},()=>({provider:'recargas-america',productId:p.productId,sku:p.catalogSku,name:p.providerItemName,price:Number(p.price),field:p.playerField,quantity:1,region})));}
const cost=ps=>ps.reduce((n,p)=>n+Math.ceil(p.price*p.quantity*1e6),0);
async function view(db,id){const o=await db.prepare('SELECT * FROM zx_bundle_orders WHERE id=?').bind(id).first(),lines=(await db.prepare('SELECT sequence,label,player_id AS playerId,state FROM zx_bundle_lines WHERE order_id=? ORDER BY sequence').bind(id).all()).results;return {id:o.id,product:o.product_name,amountCents:o.amount_cents,fundsMicros:o.funds_micros,state:o.state,paymentState:o.payment_state,checkoutUrl:o.checkout_url,lines};}
async function updateState(db,id){const lines=(await db.prepare('SELECT sequence,state FROM zx_bundle_lines WHERE order_id=? ORDER BY sequence').bind(id).all()).results;for(const l of lines){if(l.state==='WAITING_ID')continue;const ops=(await db.prepare('SELECT state FROM zx_bundle_ops WHERE order_id=? AND line=?').bind(id,l.sequence).all()).results;const state=ops.length&&ops.every(o=>o.state==='COMPLETED')?'COMPLETED':ops.some(o=>o.state==='REQUIRES_REVIEW')?'REQUIRES_REVIEW':'PROCESSING';await db.prepare('UPDATE zx_bundle_lines SET state=? WHERE order_id=? AND sequence=?').bind(state,id,l.sequence).run();l.state=state;}const state=lines.length&&lines.every(l=>l.state==='COMPLETED')?'COMPLETED':lines.some(l=>l.state==='REQUIRES_REVIEW')?'REQUIRES_REVIEW':lines.some(l=>l.state==='PROCESSING')?'PROCESSING':'PAID';await db.prepare("UPDATE zx_bundle_orders SET state=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND payment_state='paid'").bind(state,id).run();}
export async function reconcileBundlePayment(env,p){const t=await env.DB.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name='zx_bundle_orders'").first();if(!t)return false;const o=await env.DB.prepare('SELECT * FROM zx_bundle_orders WHERE id=?').bind(String(p.external_reference||'')).first();if(!o)return false;if(['wallet','ra','sf'].includes(o.method)||!productionEvidence(p,o)||o.payment_id&&o.payment_id!==String(p.id))throw Error('BUNDLE_PAYMENT_EVIDENCE_REJECTED');if(['refunded','charged_back','in_mediation'].includes(p.status)||Number(p.transaction_amount_refunded||0)>0){await env.DB.prepare("UPDATE zx_bundle_orders SET payment_state='review_required',state='REQUIRES_REVIEW' WHERE id=?").bind(o.id).run();return true;}if(p.status==='approved'&&o.payment_state!=='review_required')await env.DB.prepare("UPDATE zx_bundle_orders SET payment_state='paid',payment_id=?,state=CASE WHEN state='PENDING_PAYMENT' THEN 'PAID' ELSE state END WHERE id=? AND (payment_id IS NULL OR payment_id=?)").bind(String(p.id),o.id,String(p.id)).run();return true;}
export async function promotionRoute(request,env,url,user,json,fetcher=fetch){const reply=(b,s=200)=>{const r=json(b,s);r.headers?.set('Cache-Control','private, no-store');return r;};if(!user||user.status!=='active')return reply({ok:false,error:'LOGIN_REQUIRED'},401);if(env.PUBLIC_COMMERCE_ENABLED!=='true')return reply({ok:false,error:'COMMERCE_DISABLED'},503);await schema(env.DB);try{
 const match=url.pathname.match(/^\/api\/promotions\/orders\/([a-f0-9-]{36})(?:\/(destination|run|receipt))?$/);
 if(match){const o=await env.DB.prepare('SELECT * FROM zx_bundle_orders WHERE id=? AND user_id=?').bind(match[1],user.id).first();if(!o)return reply({ok:false,error:'NOT_FOUND'},404);
  if(!match[2]&&request.method==='GET'){const ops=(await env.DB.prepare("SELECT * FROM zx_bundle_ops WHERE order_id=? AND state='PROCESSING' AND reference IS NOT NULL LIMIT 4").bind(o.id).all()).results;for(const op of ops){try{const r=await lookupDelivery(env,JSON.parse(op.plan_json),op.player_id,op.reference,fetcher);await env.DB.prepare("UPDATE zx_bundle_ops SET state=? WHERE order_id=? AND line=? AND sequence=? AND state='PROCESSING'").bind(r.state,o.id,op.line,op.sequence).run();}catch{}}if(o.payment_state==='paid')await updateState(env.DB,o.id);return reply({ok:true,order:await view(env.DB,o.id)});}
  if(o.payment_state!=='paid')return reply({ok:false,error:'PAYMENT_NOT_CONFIRMED'},409);
  if(match[2]==='receipt'&&request.method==='GET'){if(o.state!=='COMPLETED')return reply({ok:false,error:'RECEIPT_NOT_READY'},409);return reply({ok:true,receipt:{orderId:o.id,number:'ZX-'+o.id,product:o.product_name,playerId:'Ver destinos en Mis pedidos',confirmedAt:o.updated_at,method:['ra','sf'].includes(o.method)?'balance':o.method,...(['ra','sf'].includes(o.method)?{amountMicros:o.funds_micros,currency:'USD',amountLabel:'Saldo autorizado'}:{amountCents:o.amount_cents,currency:'MXN'}),notice:'Comprobante Zero’X Store. No es una factura fiscal.'}});}
  if(request.method!=='POST')return reply({ok:false,error:'METHOD_NOT_ALLOWED'},405);
  const line=await env.DB.prepare("SELECT * FROM zx_bundle_lines WHERE order_id=? AND state!='COMPLETED' ORDER BY sequence LIMIT 1").bind(o.id).first();if(!line)return reply({ok:true,order:await view(env.DB,o.id)});
  if(match[2]==='destination'){const b=await request.json();if(b.sequence!==line.sequence||b.confirmed!==true||!/^\d{5,15}$/.test(b.playerId||''))throw Error('INVALID_DESTINATION');if(line.player_id){if(line.player_id!==b.playerId)throw Error('DESTINATION_LOCKED');return reply({ok:true,order:await view(env.DB,o.id)});}const ps=await plans(env,line,b.playerId,fetcher,o.method==='ra'?'recargas-america':o.method==='sf'?'sixofire':null);if(cost(ps)>line.max_micros||ps.length>100)throw Error('DELIVERY_PRICE_CHANGED');const stmts=[env.DB.prepare("UPDATE zx_bundle_lines SET player_id=?,state='PROCESSING' WHERE order_id=? AND sequence=? AND player_id IS NULL").bind(b.playerId,o.id,line.sequence)];for(let i=0;i<ps.length;i++)stmts.push(env.DB.prepare("INSERT INTO zx_bundle_ops SELECT ?,?,?,?,?, 'PENDING',NULL WHERE EXISTS(SELECT 1 FROM zx_bundle_lines WHERE order_id=? AND sequence=? AND player_id=?) ON CONFLICT DO NOTHING").bind(o.id,line.sequence,i,JSON.stringify(ps[i]),b.playerId,o.id,line.sequence,b.playerId));await env.DB.batch(stmts);return reply({ok:true,order:await view(env.DB,o.id)});}
  if(match[2]==='run'){if(!line.player_id)throw Error('DESTINATION_REQUIRED');const ops=(await env.DB.prepare('SELECT * FROM zx_bundle_ops WHERE order_id=? AND line=? ORDER BY sequence').bind(o.id,line.sequence).all()).results;let submitted=0;for(const op of ops){if(op.state==='COMPLETED')continue;if(op.state!=='PENDING'||submitted>=4)break;const claim=await env.DB.prepare("UPDATE zx_bundle_ops SET state='PROCESSING' WHERE order_id=? AND line=? AND sequence=? AND state='PENDING' AND EXISTS(SELECT 1 FROM zx_bundle_orders WHERE id=? AND payment_state='paid')").bind(o.id,line.sequence,op.sequence,o.id).run();if(!claim.meta.changes)break;submitted++;let r;try{r=await submitDelivery(env,JSON.parse(op.plan_json),op.player_id,o.id+':'+line.sequence+':'+op.sequence,fetcher);}catch{r={state:'REQUIRES_REVIEW'};}await env.DB.prepare("UPDATE zx_bundle_ops SET state=?,reference=? WHERE order_id=? AND line=? AND sequence=? AND state='PROCESSING' AND reference IS NULL").bind(r.state,r.reference||null,o.id,line.sequence,op.sequence).run();if(r.state!=='COMPLETED')break;}await updateState(env.DB,o.id);return reply({ok:true,order:await view(env.DB,o.id)});}
 }
 if(![ROOT+'/quote',ROOT+'/checkout'].includes(url.pathname)||request.method!=='POST')return reply({ok:false,error:'NOT_FOUND'},404);const b=await request.json();if(!/^[a-f0-9-]{36}$/.test(b.adId||'')||!/^\d{5,15}$/.test(b.playerId||'')||b.playerConfirmed!==true)throw Error('INVALID_REQUEST');
 if(['ra','sf'].includes(b.method)&&!user.isFounder)return reply({ok:false,error:'FORBIDDEN'},403);const preferred=b.method==='ra'?'recargas-america':b.method==='sf'?'sixofire':null;const key=request.headers.get('Idempotency-Key');if(url.pathname.endsWith('/checkout')){if(!/^[a-f0-9-]{36}$/.test(key||'')||!keys.has(b.method)||!validContact(b.contactPhone))throw Error('INVALID_REQUEST');const old=await env.DB.prepare('SELECT * FROM zx_bundle_orders WHERE user_id=? AND request_key=?').bind(user.id,key).first();if(old){const saved=await env.DB.prepare('SELECT pricing_json FROM zx_bundle_discounts WHERE order_id=?').bind(old.id).first();assertCouponRetry(saved?JSON.parse(saved.pricing_json):null,b.couponCode);if(old.ad_id!==b.adId||old.method!==b.method||old.amount_cents!==b.maxAmountCents)throw Error('IDEMPOTENCY_CONFLICT');if(old.method==='wallet'&&old.payment_state==='creating'){const debit=await env.DB.prepare("SELECT id FROM zx_wallet_ledger WHERE source='bundle-wallet' AND reference=? AND user_id=? AND amount_cents=?").bind(old.id,user.id,-old.amount_cents).first();if(debit)await env.DB.prepare("UPDATE zx_bundle_orders SET payment_state='paid',state='PAID' WHERE id=? AND payment_state='creating'").bind(old.id).run();}return reply({ok:true,order:await view(env.DB,old.id)});}}
 const p=await promotion(env,b.adId),quoted=[];const pricing=await retailDiscount(env.DB,p.amountCents,b.couponCode,b.method);p.amountCents=pricing.amountCents;for(const line of p.lines){const ps=await plans(env,line,b.playerId,fetcher,preferred);if(ps.length>100)throw Error('PROMOTION_QUANTITY_LIMIT');quoted.push({...line,maxMicros:cost(ps)});}if(url.pathname.endsWith('/quote'))return reply({ok:true,name:p.name,amountCents:p.amountCents,pricing,...(preferred?{totalMicros:quoted.reduce((n,l)=>n+l.maxMicros,0)}:{}),lines:quoted.map(({kind,quantity,label})=>({kind,quantity,label}))});
 const fundsMicros=preferred?quoted.reduce((n,l)=>n+l.maxMicros,0):0;if(preferred&&(!b.supplierConfirmed||b.maxTotalMicros!==fundsMicros))throw Error('PRODUCT_PRICE_CHANGED');if(b.maxAmountCents!==p.amountCents)throw Error('PRODUCT_PRICE_CHANGED');if(!['wallet','ra','sf'].includes(b.method)){if(!productionToken(env)||!env.MP_WEBHOOK_SECRET_PRODUCTION)throw Error('PAYMENT_CONFIG_MISSING');await productionAccount(env,fetcher);}const id=crypto.randomUUID(),stmts=[env.DB.prepare('INSERT INTO zx_bundle_orders(id,user_id,request_key,ad_id,product_name,amount_cents,funds_micros,method,collector_id) VALUES(?,?,?,?,?,?,?,?,?)').bind(id,user.id,key,b.adId,p.name,p.amountCents,fundsMicros,b.method,String(env.MP_COLLECTOR_ID_PRODUCTION||''))];stmts.push(env.DB.prepare('INSERT INTO zx_bundle_discounts(order_id,pricing_json) VALUES(?,?)').bind(id,JSON.stringify(pricing)));quoted.forEach((l,i)=>stmts.push(env.DB.prepare('INSERT INTO zx_bundle_lines(order_id,sequence,label,kind,quantity,max_micros) VALUES(?,?,?,?,?,?)').bind(id,i,l.label,l.kind,l.quantity,l.maxMicros)));await env.DB.batch(stmts);await saveContact(env.DB,id,user.id,b.contactPhone);
 if(['wallet','ra','sf'].includes(b.method)){if(b.method==='wallet')await postMovement(env.DB,{userId:user.id,kind:'purchase',amountCents:p.amountCents,currency:'MXN',source:'bundle-wallet',reference:id,requestKey:'bundle:'+id,orderId:id,actor:user.id});await env.DB.prepare("UPDATE zx_bundle_orders SET state='PAID',payment_state='paid' WHERE id=?").bind(id).run();return reply({ok:true,order:await view(env.DB,id)});}
 const back='https://zerox-store.pages.dev/promotions.html?order='+id;try{const r=await fetcher('https://api.mercadopago.com/checkout/preferences',{method:'POST',redirect:'manual',headers:{Authorization:'Bearer '+productionToken(env),'Content-Type':'application/json'},signal:AbortSignal.timeout(12000),body:JSON.stringify({items:[{id:b.adId,title:p.name,quantity:1,currency_id:'MXN',unit_price:p.amountCents/100}],external_reference:id,payment_methods:publicMethods(b.method),notification_url:'https://zerox-sixofire-api.westdark161208.workers.dev/api/payments/mercadopago/funding/webhook',back_urls:{success:back,pending:back,failure:back}})}),pref=await r.json(),link=new URL(pref.init_point);if(!r.ok||link.protocol!=='https:'||!['www.mercadopago.com.mx','www.mercadopago.com'].includes(link.hostname)||link.username||link.password||String(pref.collector_id)!==String(env.MP_COLLECTOR_ID_PRODUCTION))throw Error('CHECKOUT_FAILED');await env.DB.prepare("UPDATE zx_bundle_orders SET checkout_url=?,payment_state='ready' WHERE id=?").bind(link.href,id).run();return reply({ok:true,order:await view(env.DB,id)});}catch{return reply({ok:false,error:'CHECKOUT_RECONCILIATION_REQUIRED',orderId:id},503);}
 }catch(e){return reply({ok:false,error:/^(COUPON_|PROMOTION_|PRODUCT_|DELIVERY_|DESTINATION_|INVALID_|PAYMENT_|IDEMPOTENCY_|WALLET_)/.test(e.message)?e.message:'PROMOTION_UNAVAILABLE'},409);}}
