import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {resellerRoute,schema,state} from './resellers.js';
const db=new DatabaseSync(':memory:');
const DB={prepare(sql){let args=[];return {bind(...values){args=values;return this},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){return this.runSync()},runSync(){return {meta:{changes:Number(db.prepare(sql).run(...args).changes)}}}}},async batch(rows){db.exec('BEGIN');try{const result=rows.map(x=>x.runSync());db.exec('COMMIT');return result}catch(e){db.exec('ROLLBACK');throw e}}};
const env={DB,FF_INFO_API_KEY:'test'},founder={id:'founder',status:'active',isFounder:true},user={id:'buyer',status:'active',isFounder:false};
const json=(d,status=200)=>new Response(JSON.stringify(d),{status});
async function call(path,actor=user,body){const url=new URL('https://test/api/'+path);const r=await resellerRoute(new Request(url,{method:body?'POST':'GET',...(body?{body:JSON.stringify(body)}:{})}),env,url,actor,json);return {status:r.status,...await r.json()}}
globalThis.fetch=async()=>json({basicInfo:{accountId:'10000001',nickname:'Test Player'}});
assert.equal((await call('resellers/me',null)).status,401);
assert.equal((await call('admin/resellers',user)).status,403);
await schema(env);
assert.equal((await call('resellers/me')).tier,0);
assert.equal((await call('resellers/catalog?tier=7')).status,403);
assert.equal((await call('resellers/catalog?tier=7',founder)).products[0].unitCents,2600);
const deposit=crypto.randomUUID();
await call('resellers/topups',user,{requestId:deposit,amountCents:20000,note:'receipt'});
assert.equal((await state(env,user)).balanceCents,0);
assert.equal((await call('admin/resellers/topups/review',user,{id:deposit,action:'approve'})).status,403);
const approval={id:deposit,action:'approve',paymentReference:'Bank001',paymentConfirmed:true};
assert.equal((await call('admin/resellers/topups/review',founder,approval)).ok,true);
assert.equal((await call('admin/resellers/topups/review',founder,approval)).status,409);
assert.equal((await state(env,user)).balanceCents,20000);
assert.equal((await state(env,user)).tier,1);
const second=crypto.randomUUID();await call('resellers/topups',user,{requestId:second,amountCents:20000,note:'duplicate receipt'});
assert.equal((await call('admin/resellers/topups/review',founder,{...approval,id:second})).error,'PAYMENT_ALREADY_CREDITED');
assert.equal((await state(env,user)).balanceCents,20000);
const order={requestId:crypto.randomUUID(),tier:1,productId:'ff-frag-17729',quantity:40,uid:'10000001',region:'sg',price:0,total:0};
assert.equal((await call('resellers/orders',user,{...order,tier:7})).status,400);
const result=await call('resellers/orders',user,order);assert.equal(result.order.total,3800);
assert.equal((await state(env,user)).balanceCents,16200);
await call('resellers/orders',user,order);assert.equal((await state(env,user)).balanceCents,16200);
await call('admin/resellers/orders/review',founder,{id:result.order.id,action:'refund'});
await call('admin/resellers/orders/review',founder,{id:result.order.id,action:'refund'});
assert.equal((await state(env,user)).balanceCents,20000);
const orders=await Promise.all([1,2].map(()=>call('resellers/orders',user,{...order,requestId:crypto.randomUUID(),quantity:150})));
assert.equal(orders.filter(x=>x.ok).length,1);assert.equal((await state(env,user)).balanceCents,5750);
const badUid=await call('resellers/orders',user,{...order,requestId:crypto.randomUUID(),uid:'10000002'});assert.equal(badUid.error,'PLAYER_NOT_VERIFIED');assert.equal((await state(env,user)).balanceCents,5750);
const good=orders.find(x=>x.ok);await call('admin/resellers/orders/review',founder,{id:good.order.id,action:'complete',deliveryConfirmed:true});
await call('admin/resellers/orders/review',founder,{id:good.order.id,action:'refund'});assert.equal((await state(env,user)).balanceCents,5750);
for(let i=0;i<9;i++)db.prepare("INSERT INTO zx_r_orders(id,user_id,request_key,product_id,product_name,tier,quantity,total,uid,region,nickname,status,completed_at) VALUES(?,?,?,?,?,1,40,3800,'10000001','sg','test','completed',CURRENT_TIMESTAMP)").run(crypto.randomUUID(),user.id,crypto.randomUUID(),'p','test');
assert.equal((await state(env,user)).tier,2);
db.exec("UPDATE zx_r_orders SET completed_at=datetime('now','-60 days')");assert.equal((await state(env,user)).tier,2);
assert.equal((await state(env,founder)).balanceCents,0);
console.log('PASS: authentication, founder access, locks, pending deposits, duplicate bank reference, price tampering, verified ID, idempotent orders, concurrent overspend, refunds, earned levels and retention. No live balances modified.');
